GoogleChromeLabs/chromium-bidi

- package.json
- src/bidiMapper/mapper.ts
- src/bidiMapper/rollup.config.js
- src/bidiMapper/tsconfig.json
- src/bidiMapper/utils/cdpClient.ts
- src/mapperReader.ts
This change adds a dependency on https://www.npmjs.com/package/devtools-protocol which contains updated .json and .d.ts files for CDP.
To enable the mapper script to import this module, I've added a rollup config to be run during build. It is configured to allow node module imports.
As a quick test, I've imported the `version` property from `devtools-protocol` module to verify that this builds and is rolled up into the output file as expected.
A follow-up change will add a strongly-typed layer on top of CdpClient.
> Typed CDP Bindings - Part 1

- package.json
- src/bidiMapper/commandProcessor.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/domains/context/targetInfo.ts
- src/bidiMapper/mapper.ts
- src/bidiMapper/tsconfig.json
- src/bidiMapper/utils/bidiServer.ts
- src/bidiMapper/utils/cdpClient.ts
- src/bidiMapper/utils/events.ts
- src/bidiMapper/utils/iServer.ts
- src/browserLauncher.ts
- src/mapperServer.ts
- src/tsconfig.json
This changes implements a strongly-typed CdpClient object that implements the interface provided in devtools-protocol module. CdpClient callers have been updated to use the new style.
Before:
```js
await cdpServer.sendMessage({
method: 'Target.setAutoAttach',
params: {
autoAttach: true,
waitForDebuggerOnStart: false,
flatten: true,
},
});
```
After:
```js
await cdpClient.Target.setAutoAttach({
autoAttach: true,
waitForDebuggerOnStart: false,
flatten: true,
});
```
Events:
```js
this._cdpClient.Target.on('attachedToTarget', (params) => {
this._contextProcessor.handleAttachedToTargetEvent(params);
});
```
Command and event parameters are fully typed. TypeScript interfaces for CDP types are also available from the `Protocol` namespace. e.g.: `Protocol.Target.TargetInfo`. Some functions that …
> Typed CDP Bindings - Part 2

- package.json
Use the cross-env module for setting environment variables in package.json scripts. This lets the script work on Windows.
> Use cross-env for script environment variables

- .vscode/tasks.json
- src/bidiMapper/tsconfig.json
- src/configs/tsconfig.common.json
- src/tsconfig.json
Adds a new tsconfig.common.json file which holds compiler options common to both the server and mapper code. The server and mapper tsconfig files "extend" this file. This helps ensure both components are built with the same options.
Also adding a default build task for vscode. This lets the user trigger a full build using ctrl+shift+B and vscode will show any typescript errors in the "errors" panel.
> Share common tsconfig options

- prettier.config.cjs
- src/bidiMapper/commandProcessor.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/mapper.ts
- src/bidiMapper/rollup.config.js
- src/bidiMapper/utils/bidiServer.ts
- src/bidiServerRunner.ts
- src/cdp/cdpClient.spec.ts
- src/cdp/cdpClient.ts
- src/cdp/cdpConnection.spec.ts
- src/cdp/cdpConnection.ts
- src/cdp/cdpMessage.ts
- src/cdp/index.ts
- src/cdp/websocketTransport.ts
- src/index.ts
- src/mapperReader.ts
- src/mapperServer.ts
- src/tests/stubTransport.spec.ts
- src/utils/log.ts
- src/utils/transport.ts
- tests/test_bidi.py
Updating the copyright notice based on the discussion at the last Chromium bidi sync. The new text reads:
```
/**
* Copyright 2021 Google LLC.
* Copyright (c) Microsoft Corporation.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
```
> Update copyright notice

- package.json
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/scripts/eval.es
- src/bidiMapper/scripts/eval.spec.ts
- tests/test_bidi.py
* Adding unit tests for serialization/deserialization logic.
Referencing `eval.es` from `eval.spec.ts` wouldn't work, because `eval.es` is excluded from the compilation. So the test reads the script code and eval it, as Mapper will do in the page context.
> unit tests on `eval.es`

- src/bidiMapper/bidiProtocolTypes.ts
- src/bidiMapper/commandProcessor.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/scripts/eval.es
- src/bidiMapper/scripts/eval.spec.ts
- tests/test_bidi.py
To provide a stacktrace in case of not-`Error` thrown, the exception should not be caught in the evaluated script itself.
Another advantage of splitting `eval` and `serialize` is there is no need in parsing text stacktrace from JS `Error` object, and no need in correction stacktrace positions because of the script wrapping.
> Split `script.evaluate` into `eval` and `serialize`

- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/scripts/eval.es
- src/bidiMapper/scripts/eval.spec.ts
- tests/test_bidi.py
I make this in separate PR to keep previous PR reviewable.
In this PR the [suggestion to avoid race condition](https://github.com/GoogleChromeLabs/chromium-bidi/pull/51#issuecomment-931737752) is implemented. Evaluation and serialization are done in the same call, and serialization results retrieved by another call.
`test_scriptEvaluateChangingObject_resultObjectDidNotChange` fails on the #51 but passes in this PR.
> Evaluate and serialize in the same call.

- src/bidiMapper/bidiProtocolTypes.ts
- src/bidiMapper/commandProcessor.ts
- src/bidiMapper/domains/context/browsingContextProcessor.spec.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/mapper.ts
- src/cdp/cdpClient.spec.ts
- src/cdp/cdpConnection.spec.ts
- src/cdp/cdpConnection.ts
- src/mapperServer.ts
- src/tests/stubTransport.spec.ts
- tests/test_bidi.py
* Implement [`browsingContext.navigate`](https://w3c.github.io/webdriver-bidi/#command-browsingContext-navigate) command.
* Add `browsingContext.create` -> `params.type`.
* Add unit test for different event orders in `browsingContext.create`.
* Made `EVALUATOR_SCRIPT` a property to allow unit testing.
* `BrowsingContextProcessor` is responsible for handling events for testability.
> `create` and `navigate.browsingContext`

- examples/cross-browser.py
- src/bidiMapper/bidiProtocolTypes.ts
- src/bidiMapper/commandProcessor.ts
- src/bidiMapper/domains/context/browsingContextProcessor.spec.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- tests/test_bidi.py
After https://github.com/w3c/webdriver-bidi/pull/142 is merged, `script.callFunction` is not a prototype anymore.
> Rename `PROTO.script.callFunction` -> `script.callFunction`

- src/bidiMapper/bidiProtocolTypes.ts
- src/bidiMapper/domains/context/context.ts
- tests/_helpers.py
- tests/test_browsing_context.py
1. Emit `browsingContext.load` when `Page.lifecycleEvent` fired with `name="load"`.
2. Emit `browsingContext.domContentLoaded` when `Page.lifecycleEvent` fire with `name="DOMContentLoaded"`.
3. Added and implement `interactive` and `complete` params to `browsingContext.navigate` command.
> `browsingContext` events + `browsingContext.navigate` `wait` param.

- README.md
- src/bidiMapper/bidiProtocolTypes.ts
- src/bidiMapper/domains/context/browsingContextProcessor.spec.ts
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/scripts/eval.es
- tests/test_script.py
https://github.com/GoogleChromeLabs/chromium-bidi/issues/79
Based on discussion https://github.com/w3c/webdriver-bidi/issues/157
> Instead of adding global bindings, pass bindings as deserializable arguments to `script.callFunction`. 
...
The argument can be something like:
> 
> ```
> {
>   type: "binding", 
>   value: "SOME_BINDING_NAME"
> }
> ```
> 
> , which will be deserialized to a callback. Calling that callback with any arguments will cause the BiDi event with those arguments like:
> 
> ```
> {
>   method: "script.bindingCalled",
>   params: {
>     arguments: [... remote values ...],
>     name: "SOME_BINDING_NAME"
>   }
> }
> ```
> Add `PROTO.binding` type to Local Value.

- examples/cross-browser.py
- src/bidiServerRunner.ts
Per step 2 of https://w3c.github.io/webdriver-bidi/#transport, the endpoint is supposed to be `/session` (with an optional query string attached to it).
Issue: #110
> Use the proper WebSocket endpoint

- README.md
- package.json
I’m still trying to work out some issues with the Wombat service, but once those are resolved this patch describes how the process will work.
> Document how to `npm publish`

- examples/cross-browser.py
Addressing #110 
**Chroimum:** 
* The script with runs well and returns the list of the articles.
**Firefox:**
* The script with runs well till the `script.callFunction` command, which is not implemented yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1750541 
```
"error":"unknown command","message":"script.callFunction"
```
> Fix `cross-browser.py` for Firefox

- examples/cross-browser.py
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/domains/context/scriptEvaluator.ts
- src/bidiMapper/domains/protocol/bidiProtocolTypes.ts
- tests/test_browsing_context.py
- tests/test_script.py
- tests/test_serialization.py
Align CallFunction and Evaluate results with the [W3C BiDi spec](https://w3c.github.io/webdriver-bidi/#type-script-Result):
```
{
result: {
result | exceptionDetails: {...}
}
}
```
> Fix Evaluate and CallFunction types

- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/domains/protocol/bidiProtocolTypes.ts
- tests/test_browsing_context.py
- wpt-metadata/webdriver/tests/bidi/browsing_context/context_created/context_created.py.ini
- wpt-metadata/webdriver/tests/bidi/log/entry_added/stacktrace.py.ini
Required by `browsing_context/navigate` WPT tests:
* [getTree](https://github.com/web-platform-tests/wpt/blob/b293894e545af62931b996700bcfe06b5786414b/webdriver/tests/bidi/browsing_context/navigate/__init__.py#L8)
* [handle in-the-same-document navigation](https://github.com/web-platform-tests/wpt/blob/b293894e545af62931b996700bcfe06b5786414b/webdriver/tests/bidi/browsing_context/navigate/hash.py) 
Done:
* Add `root` parameter to `browsingContext.getTree`
* Handle in-the-same-document navigation
* Add e2e test
Out of scope: 
* Handle nested contexts.
> Improvements for WPT

- runWPT.sh
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/scriptEvaluator.ts
- src/bidiMapper/domains/protocol/bidiProtocolTypes.ts
- tests/_helpers.py
- tests/test_browsing_context.py
- tests/test_cdp.py
- tests/test_events.py
- tests/test_script.py
- tests/test_serialization.py
- wpt-metadata/webdriver/tests/bidi/browsing_context/navigate/invalid.py.ini
* Align `browsingContext.created` with spec.
* Delegate waiting for initiated logic to `Context`.
* Refactor `recursive_compare` to support custom validators.
> Align implementation with spec

- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/domains/context/iContext.ts
- src/bidiMapper/domains/context/targetContext.ts
- tests/test_browsing_context.py
`parent` should be present only in the root serialized context: https://w3c.github.io/webdriver-bidi/#type-browsingContext-BrowsingContextInfo
> Align BrowsingContextInfo serialization with spec

- package.json
- src/bidiMapper/rollup.config.js
The rolled-up src/.build/bidiMapper/mapper.js script has a size of 936K.
With the terser minification it gets reduced to 528K (43% size
reduction).
Integrate terser to the build process as a rollup plug-in.
Bug: #89
> Add terser minification

- .github/workflows/unit.js.yml
This adds a straightforward way to measure the effectiveness of #89
wherein we intend to optimize mapper compiled code.
> github workflow: add step to print the mapper file size

- src/bidiMapper/mapper.ts
- src/bidiMapper/rollup.config.js
From follow-up comments on #221, we do not need all copyright notices to
be preserved, only one of them should be enough.
> Terser minification: preserve only one copyright notice.

- src/bidiMapper/domains/context/browsingContextProcessor.ts
- tests/test_browsing_context.py
- tests/test_nested_browsing_context.py
- wpt-metadata/webdriver/tests/bidi/browsing_context/navigate/hash.py.ini
1. Respect `urlFragment` when processing event [`Page.frameNavigated`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-frameNavigated):
* `url`: Frame document's URL without fragment.
* `urlFragment`: Frame document's URL fragment including the '#'.
2. Respect `url` change from `Page.navigatedWithinDocument`.
> Respect `url` changes from `Page` events

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
- tests/test_sandbox.py
- wpt-metadata/webdriver/tests/bidi/script/call_function/invalid.py.ini
- wpt-metadata/webdriver/tests/bidi/script/call_function/sandbox.py.ini
- wpt-metadata/webdriver/tests/bidi/script/evaluate/invalid.py.ini
- wpt-metadata/webdriver/tests/bidi/script/evaluate/sandbox.py.ini
Addressing #241 :
* Added `sandbox` logic.
* Added e2e tests.
* Throwing "not implemented error" in case of `realm` parameter.
* Updating WPT expectations (after exception is thrown).
TBD in another PR:
* Adding `realm` support.
> Support Sandboxes

- src/bidiMapper/commandProcessor.ts
- tests/test_protocol_basics.py
As we don't support creating additional sessions, the `ready` state should be `false`:
> The readiness state of a [remote end](https://w3c.github.io/webdriver/#dfn-remote-ends) indicates whether it is free to accept new connections.
> Align `session.status` with spec

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/protocol/bidiProtocolTypes.ts
- tests/test_browsing_context.py
- tests/test_nested_browsing_context.py
- wpt-metadata/webdriver/tests/bidi/browsing_context/load/load.py.ini
* Add `url` to `browsingContext.load` and `browsingContext.domContentLoaded`.
* Raise loading events for initial `about:blank` loading.
* Other failures should be fixed by https://github.com/web-platform-tests/wpt/pull/35848.
> Fix `BrowsingContext` WPT tests

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- tests/test_browsing_context.py
- tests/test_nested_browsing_context.py
- wpt-metadata/webdriver/tests/bidi/browsing_context/load/load.py.ini
Addressing the issue https://crbug.com/chromedriver/4204.
Whenever the page is navigated, the child browsing contexts should be removed.
WPT test `webdriver/tests/bidi/browsing_context/load/load.py` was disabled due to instability: https://github.com/web-platform-tests/wpt/issues/35846
> Clear child browsing contexts on `Page.frameNavigated`

- src/bidiMapper/commandProcessor.ts
- src/bidiMapper/domains/protocol/bidiProtocolTypes.ts
- src/bidiMapper/mapper.ts
- src/bidiMapper/utils/bidiServer.ts
- tests/test_protocol_basics.py
Extend BiDi+ command with an optional field `channel`. If set, the same `channel` is set in response.
Out of scope - respect `channel` in EventManager.
> Add `channel` to command

- src/bidiMapper/domains/log/logManager.ts
- src/bidiMapper/domains/protocol/bidiProtocolTypes.ts
- tests/test_log_events.py
- wpt-metadata/webdriver/tests/bidi/log/entry_added/console.py.ini
Align with [specification](https://github.com/w3c/webdriver-bidi/pull/259).
> Rename `warning` -> `warn`

- src/bidiMapper/commandProcessor.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/domains/log/logManager.ts
- src/bidiMapper/domains/protocol/bidiProtocolTypes.ts
- src/bidiMapper/mapper.ts
- src/bidiMapper/utils/bidiServer.ts
- src/utils/processingQueue.spec.ts
- src/utils/processingQueue.ts
- tests/_helpers.py
- tests/test_log_events.py
- tests/test_serialization.py
- tests/test_subscription.py
Implementation of the "processing queue with promises": http://go/webdriver-non-racy-serialization-proposal.
To provide serialization of the events, additional CDP call is required. When such a call is done, the order of the events can be changed. This PR implements `ProcessingQueue`, which allows adding Promises instead of the real values, and guarantee the order of the messages are kept.
The promise queue is for consoleAPI events.
Extended e2e tests to cover result, exception and log serialization.
> Non-racy serialization with message queue

- examples/app.html
- examples/cross-browser.py
The previous selector is broken as of ~2 months ago, c.f. https://news.ycombinator.com/item?id=33027700
Changed from:
<a class="titlelink"></a>
To:
<span class="titleline">
<a></a>
</span>
> Fix Hacker News `cross-browser.py` example

- src/cdp/cdpConnection.ts
This logs are redundant, as the logged messages are parsed and logged again.
> Remove redundant logs

- src/bidiMapper/mapper.ts
- src/cdp/cdpConnection.ts
It is useful to have the CDP logs of the Mapper, but from the other side, CDP log of the server is too noisy.  This PR allows providing a custom log for `CdpConnection`, which is used both in the Mapper and in the server.
Example output:
```
bidiMapper:log   'BiDi Messages',
bidiMapper:log   'received < {"method": "PROTO.browsingContext.findElement", "params": {"selector": "body > div", "context": "50D4E0F9CC72E109250C8EA8E20242F7"}, "id": 4}'
bidiMapper:log ] +3ms
bidiMapper:log consoleAPICalled log [
bidiMapper:log   'CDP',
bidiMapper:log   'sent > {"id":10,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(...args)=>{ return _callFunction((\\ne=>document.querySelector(e)\\n), args);\\n      function _callFunction(f, args) {\\n        const deserializedThis = …
```
> Log CDP commands

- .github/workflows/unit.js.yml
- configs/rollup.config.js
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiServer/mapperReader.ts
- src/bidiServer/tsconfig.json
- src/bidiTab/bidiTab.ts
- src/bidiTab/mapperTabPage.ts
- src/bidiTab/tsconfig.json
- src/tsconfig.json
- src/utils/log.ts
This PR separates the mapper tab from the mapper implementation. This allows compiling the mapper implementation without DOM APIs. As the next step we can turn bidiMapper/bidiTab/bidiServer into composite projects to reduce duplication in the build output.
> Separate mapper tab from the mapper

- src/bidiMapper/domains/context/browsingContextImpl.ts
- tests/test_script.py
This should fix the [get_realm](https://wpt.fyi/results/webdriver/tests/bidi/script/get_realms/get_realms.py?label=experimental&label=master&aligned&view=subtest) WPT tests.
> Destroy realms when a BrowsingContext is destroyed

- configs/rollup.config.js
> (!) If you do not supply "output.name", you may not be able to access
> the exports of an IIFE bundle.
Tested: `npm run build` does not produce a warning
> Add output.name to rollup config to resolve warning

- configs/rollup.config.js
- package-lock.json
- package.json
Fix the following warning:
> npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been
deprecated and is no longer maintained. Please use @rollup/plugin-terser
> replace rollup-plugin-terser with @rollup/plugin-terser

- .github/workflows/e2e.js.yml
- .github/workflows/publish-on-tag.yml
- .github/workflows/wpt.yml
Reference: https://github.blog/changelog/2021-11-23-github-actions-setup-python-now-supports-dependency-caching/
> github actions: add dependency caching for pip to speed up workflows

- .github/workflows/e2e.js.yml
- .github/workflows/publish-on-tag.yml
- .github/workflows/unit.js.yml
- .github/workflows/wpt.yml
Reference: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
> github actions: add dependency caching for npm to speed up workflows

- .github/workflows/e2e.js.yml
It is already included out-of-the-box:
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
Same for 18.04 and 20.04, thus it is unlikely to be removed.
> github workflow: remove redundant apt install xvfb from ubuntu-latest

- .eslintrc.js
- src/bidiTab/mapperTabPage.ts
> Users who come from a OOP paradigm may wrap their utility functions in
an extra class, instead of putting them at the top level of an ECMAScript module. Doing so is generally unnecessary in JavaScript and TypeScript projects.
Bug: #392
> eslint: add no-extraneous-class rule and fix most of mapperTabPage

- .github/workflows/wpt.yml
> Node.js 12 actions are deprecated. Please update the following actions
to use Node.js 16: actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> github workflow: fix warning: update upload-artifact action to v3

- .github/workflows/e2e.js.yml
- .github/workflows/pre-commit.yml
- .github/workflows/publish-on-tag.yml
- .github/workflows/unit.js.yml
- .github/workflows/wpt.yml
"npm run prepare" is always executed as part of "npm install".
Currently, CI is running "npm run build" redundantly twice, once as part
of "install", and once as part of an explicit build step.
"npm ci" does not execute "npm run prepare".
> github workflows: run npm ci instead of npm install

- .github/workflows/e2e.js.yml
- .github/workflows/publish-on-tag.yml
- .github/workflows/unit.js.yml
- .github/workflows/wpt.yml
as it is already implicitly run as part of "npm ci"
c.f. #413
> github workflows: do not run "npm run build" explicitly

- src/bidiServer/bidiServerRunner.ts
- src/bidiServer/index.ts
> Users who come from a OOP paradigm may wrap their utility functions in
an extra class, instead of putting them at the top level of an ECMAScript module. Doing so is generally unnecessary in JavaScript and TypeScript projects.
Bug: #392
> eslint: no-extraneous-class: fix BidiServerRunner

- src/bidiMapper/domains/context/browsingContextProcessor.ts
> eslint: no-extraneous-class: fix BrowsingContextProcessor

- .eslintrc.js
- src/bidiMapper/BidiServer.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/browsingContextStorage.ts
- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/bidiMapper/domains/events/SubscriptionManager.ts
- src/bidiMapper/domains/script/realm.ts
As a side effect it is now possible to have multiple
`#BrowsingContextStorage.contexts`.
Furthermore, enforce the `no-extraneous-class` ESLint rule.
The following classes were refactored in order to accommodate that:
- BidiServer
- BrowsingContextImpl
- BrowsingContextProcessor
- EventManager
- Realm
- SubscriptionManager
Bug: https://github.com/GoogleChromeLabs/chromium-bidi/issues/392
> Make BrowsingContextStorage non-static, and an instance of BidiServer

- package.json
- pytest.ini
- Issue 1: python version mismatch. macOS 13.2 python is 3.9.6. Homebrew python is 3.10.9. If we run our e2e tests with python 3.9.x they fail with the following message:
> AttributeError: module 'pytest_asyncio' has no attribute 'fixture'
This error message is confusing and it's not obvious it is related to the python version. By introducing `minversion = 7.0` in pytest.ini, the error message then becomes
> 'minversion' requires pytest-7.0, actual pytest-6.1.2
...which makes it much clearer it's an issue related to an old pytest version. pytest 7.x matches what is in 'requirements.txt'.
This is relevant because VSCode's integrated terminal and tmux do not pick up custom $PATH settings in the user shell rc file, thus python3 is /usr/bin/python3 instead of /opt/homebrew/bin/python3.
- …
> fix a couple of pytest issues by introducing a pytest.ini file

- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
With the intent of making it possible to have multiple realm maps at some point, to support the ability to run multiple bidi sessions simultaneously.
Bug: #392
> Move ScriptEvaluator.#knownHandlesToRealm to a newly introduced RealmStorage

- src/utils/EventEmitter.spec.ts
- src/utils/EventEmitter.ts
Currently there is no type safety when calling `emit`.
Bug: #433
> EventEmitter: fix type signature to match mitt's

- .github/workflows/unit.yml
- README.md
- package-lock.json
- package.json
Remove "unit" target, default to standard "test" target. Previously the "unit" target would not recompile sources.
Side effect: It's possible to do "npm test" in lieu of "npm run test".
> npm: always recompile sources upon running unit tests

- package-lock.json
- package.json
In Puppeteer we moved away from bundling for now and, thus, mitt would be needed as a prod dependency.
> Add mitt as a prod dependency

- .github/workflows/e2e.yml
- .github/workflows/generate-wpt-report.yml
- .github/workflows/pre-commit.yml
- .github/workflows/publish-on-tag.yml
- .github/workflows/wpt-chromedriver.yml
- .github/workflows/wpt-mapper.yml
Not sure if this fixes flakiness, but it's worth a try.
On my macOS M1, python 3.9 fails immediately when running those tests. Python 3.10 works (go/bidi-g3doc#e2e)
> upgrade python: 3.9 -> 3.10

- src/bidiMapper/domains/context/browsingContextImpl.ts
- wpt-metadata/chromedriver/webdriver/tests/bidi/browsing_context/navigate/error.py.ini
In case of 2 consequent "same document navigation", the `navigatedWithinDocument` deferred was kept finished instead of being re-created.
This PR should fix the issue and flakiness of e2e tests
> Fix same document navigation race condition

- src/bidiMapper/domains/script/scriptEvaluator.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
The BiDi spec was updated to only include `Infinity` and `-Infinity`.
> chore: Remove +Infinity from SpecialNumber

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
- tests/test_helpers.py
- tests/test_shared_id.py
Addressing [4373 - Fix loader id information in the ids generated by BiDiMapper - chromedriver](https://crbug.com/chromedriver/4373).
At the moment the `realm` (`executionContext`) is created, there is no `navigableId` (`loaderId`) yet. Get the current `navigableId` on-demand from the `browsingContext` (`target`). The problem disappears after first navigation.
> Fix Realm's `navigableId`

- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
- remove unused types
- make `realm: Realm` instead of `realm: string`
Bug: #294
> protocol parser prefactoring

- tests/test_helpers.py
- tests/test_subscription.py
The fact it starts from 2 today seems to have been a tiny mistake.
> _command_counter: start from 1 instead of 2

- tests/conftest.py
- tests/test_helpers.py
And move helpers to a separate module.
This is the idiomatic way. Fixtures defined in `conftest.py` are automatically loaded for every test.
This approach is also adopted by WPT, c.f.
https://github.com/web-platform-tests/wpt/search?q=filename%3Aconftest.py
References:
- https://docs.pytest.org/en/6.2.x/fixture.html#conftest-py-sharing-fixtures-across-multiple-files
- https://stackoverflow.com/questions/34466027/in-pytest-what-is-the-use-of-conftest-py-files
> pytest: store test fixtures in conftest.py

- tests/requirements.txt
- tests/test_browsing_context.py
- tests/test_cdp.py
- tests/test_helpers.py
- tests/test_log_events.py
- tests/test_nested_browsing_context.py
- tests/test_script.py
- tests/test_serialization.py
- tests/test_shared_id.py
- tests/test_subscription.py
- introduce and use `anys` pytest matchers
- use native assert comparisons instead of custom `recursive_compare`
- use type comparisons instead of `any_value` in some circumstances
Reference: https://github.com/jwodder/anys
As of now:
With Anys, but without icdiff:
With this PR (=Anys + icdiff):
> improve pytest ergonomics with native assertions

- examples/classic_to_bidi_example.py
- examples/console_log_example.py
- examples/script_example.py
- tests/conftest.py
- tests/test_browsing_context.py
- tests/test_cdp.py
- tests/test_log_events.py
- tests/test_nested_browsing_context.py
- tests/test_protocol_basics.py
- tests/test_sandbox.py
- tests/test_script.py
- tests/test_serialization.py
- tests/test_shared_id.py
- tests/test_subscription.py
https://docs.python.org/3/faq/programming.html?highlight=faq#what-are-the-best-practices-for-using-import-in-a-module:
> In general, don’t use from modulename import *. Doing so clutters the
importer’s namespace, and makes it much harder for linters to detect undefined names.
Reference: https://www.asmeurer.com/removestar/
> python: do not use wildcard imports

- .vscode/launch.json
- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/bidiMapper/domains/events/SubscriptionManager.ts
- tests/test_subscription.py
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/session/unsubscribe/invalid.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/session/unsubscribe/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/session/unsubscribe/invalid.py.ini
If an operation failed for some reason (not subscribed, browsing context not found, etc), do not unsubscribe partially.
Closes #482
> make session.unsubscribe command atomic

- src/bidiMapper/CommandProcessor.ts
Remove a forgotten `console.error`. If you think we should use the logger here, happy to make the change.
> chore: remove console.error statement

- .github/workflows/e2e.yml
- .github/workflows/generate-wpt-report.yml
- .github/workflows/wpt-chromedriver.yml
- .github/workflows/wpt-mapper.yml
- package-lock.json
- package.json
Make the installation method platform-agnostic, in order to eventually support running CI on Windows and macOS.
While we're here, add macOS to E2E tests.
Bug: #361
Docs: https://github.com/puppeteer/puppeteer/tree/main/packages/browsers
> use puppeteer/browsers to install google chrome in CI and add macOS E2E tests

- .github/workflows/wpt-mapper.yml
For some reason, using chrome latest is making the CI fail. Revert back to chrome dev.
Bug: #361
> revert CI mapper change back to not using puppeteer/browsers

- src/bidiMapper/CommandProcessor.ts
- src/bidiTab/bidiTab.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
- ~remove redundant comments, as they are hard to keep up-to-date as the spec evolves: http://go/java-practices/comments#what_for~
- `params: unknown` -> `params: object`
- add type to attributes: from "unknown" to "Record<string, string>" (`?attributes: {*text => text}`)
- add documentation links to all top-level modules
- group methods by module
- introduce a type for all BiDi commands
> miscellaneous protocol improvements

- runBiDiServer.sh
- runWPT.sh
Because of `set -euo pipefail`, we need to explicitly check that `"$1"` is a valid expression before referencing it.
Follow-up-of: #524
> `run*.sh` scripts: check number of arguments before evaluating `"$1"`

- package.json
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiTab/bidiTab.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
- src/utils/unitConversions.spec.ts
- src/utils/unitConversions.ts
- tests/test_print.py
Bug: #518
Spec: https://w3c.github.io/webdriver-bidi/#command-browsingContext-print
CDP method: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF
> Implement `browsingContext.print` command

- .mocharc.json
- package-lock.json
- package.json
This improves debugging natively with our original TS files.
Previously, we would need to debug using the generated JS files.
References:
- https://jonnyreeves.co.uk/2015/getting-proper-stack-traces-with-mocha-and-typescript/
- https://futurestud.io/tutorials/mocha-migrating-from-mocha-opts-to-mocharc-js-configuration-file
> use source maps when running mocha unit tests

- src/bidiMapper/domains/script/scriptEvaluator.ts
In preparation for the introduction of the binding mechanism.
- 1) move public methods to the top, and private methods to the bottom of the class, for readability
- 2) move a few methods to within ScriptEvaluator, because we will need to use `this` to access the to be introduced event manager member variable
This is intended to reduce diff noise in the main PR (#319).
Furthermore, remove unnecessary switch case braces.
This is a no-op.
Bug: #294
> refactor script evaluator

- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/bidiMapper/domains/events/SubscriptionManager.ts
- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
References:
- `s/OwnershipModel/ResultOwnership/` to align with the spec
- `script.Channel`: https://pr-preview.s3.amazonaws.com/w3c/webdriver-bidi/pull/361.html#type-script-Channel
- `script.Message`: https://pr-preview.s3.amazonaws.com/w3c/webdriver-bidi/pull/361.html#event-script-message
Bug: #294
Reference: https://github.com/GoogleChromeLabs/chromium-bidi/pull/319#issuecomment-1453236068
> Align binding (script message and channel) protocol with the spec

- src/bidiMapper/domains/events/EventManager.ts
- tests/conftest.py
- tests/test_browsing_context.py
- tests/test_helpers.py
- tests/test_network.py
When user subscribes to `network` events globally, all new browsing contexts should enable it.
> Enable `Network` domain globally

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
- tests/test_channel.py
- tests/test_serialization.py
Provide a way to communicate from scripts evaluated on the page side to
the BiDi client.
This is a safe (non-observable by the page script) analog of the `Runtime.addBinding` CDP command.
Prototype the mechanism using long-poll. Implementation details: http://go/webdriver-binding-implementation.
Reference: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-callFunctionOn
Bug: https://github.com/GoogleChromeLabs/chromium-bidi/issues/294
> Prototype channel mechanism (`script.MessageEvent`)

- src/bidiMapper/domains/script/scriptEvaluator.ts
> make `initChannelListener` a method of ScriptEvaluator

- runWPT.sh
Otherwise the expectations would never get updated if there's at least one failing WPT test, which defeats the purpose of having the UPDATE_EXPECTATIONS variable in the first place.
> runWPT.sh: remove set -e

- .gitignore
- package-lock.json
- package.json
Use https://istanbul.js.org/ and its `nyc` command-line utility.
Introduce a "npm run coverage" command for that.
Bug: #17
> add test code coverage for TypeScript / Mocha

- src/bidiMapper/domains/context/browsingContextImpl.ts
The CDP equivalent is `preferCSSPageSize`, it is the negation of `shrinkToFit`.
We can also observe this in [webdriver classic][1].
[1]: https://source.chromium.org/chromium/chromium/src/+/main:chrome/test/chromedriver/window_commands.cc;l=2287;drc=90ebbc5baf7104797970c7cfa5b22689f6f904c1
Bug: #518
Docs: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF
> `browsingContext.print`: use `shrinkToFit` parameter

- .github/dependabot.yml
With a cadence of monthly updates, restricting the PR limits to 1 proves to be too restrictive. The default is 5.
Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
> Remove "open-pull-requests-limit" from dependabot

- tests/test_browsing_context.py
- tests/test_helpers.py
- tests/test_log_events.py
- tests/test_nested_browsing_context.py
- tests/test_script.py
- tests/test_subscription.py
- remove redundant comments in E2E tests
- remove unnecessary explicit IDs in BiDi commands
- turn method comments into docstrings
- other miscellaneous changes
- add unit tests and type hints to `AnyExtending`
> Misc refactoring in python E2E tests

- src/protocol/protocol.ts
The `Record<string,never>` brakes the Type checking (example `'error' in object` that will always be resolved as the `EmpyResult` type which is not true.
This still allows us to give it value of `{}` [Sandbox Example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAogTnA9nAKuaBeKBvAUFKCBZALigGdg4BLAOwHMAafKagEzNoFcBbAIyK4AvrlyhIsHmFBoJWAEoQAxsjYAeSjQaMotCADciAPlEB6U1AASiQ3Cg2i9vgCtlwVsADk5KAEMANgDuviA+8Eio6LjmUADCABa+DNDAiFCKKnDqmnRMugbG0RbWtrqIgU6uSu7UPnyIwPFQ4hA+lNT+-rgAZly01dSItM2twAAUiC5uZDBSMuhQAD6wxJGQAJR4BNTdY55EEZ6sw5NVwJssBCq05Ij+EAB0-oj0E1PVD+zrLCIiuEA)
> Fix type for `EmptyResult`

- src/bidiMapper/domains/script/realm.ts
- tests/test_serialization.py
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/call_function/result.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/evaluate/result.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/call_function/result.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/evaluate/result.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/call_function/result.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/evaluate/result.py.ini
According to the serialization algorithm, platform objects should be treated in a special way, and have only `type: "object"` and maybe `handle`.
Related WPT test: [`test_remote_values[new URL('https://example.com')-expected17-True]`](https://wpt.fyi/results/webdriver/tests/bidi/script/call_function/result.py?label=experimental&label=master&aligned)
> Treat `platformobject` in a special way.

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/OutgoingBidiMessage.ts
- src/utils/deferred.spec.ts
- src/utils/deferred.ts
- src/utils/processingQueue.ts
Closes #528
I didn't find a way to add an auto test for it, but I was able to reproduce the issue manually, and it's gone after the fix.
The following exception is gone:
```
bidiMapper:log exceptionThrown {
timestamp: 1681290303299.3938,
exceptionDetails: {
exceptionId: 1,
text: 'Uncaught (in promise)',
lineNumber: 0,
columnNumber: 73033,
scriptId: '6',
stackTrace: { callFrames: [Array] },
exception: {
type: 'object',
className: 'Object',
description: 'Object',
objectId: '-111297914861493100.1.1',
preview: [Object]
},
executionContextId: 1
}
} +0ms
```
> Make deferred don't  raise `Uncaught (in promise)`

- .pre-commit-config.yaml
- examples/_helpers.py
- tests/conftest.py
- tests/requirements.txt
- tests/test_helpers.py
Makes it a bit more consistent with WPT.
> python: add typing support with mypy

- .eslintrc.js
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/domains/events/SubscriptionManager.ts
- src/bidiMapper/domains/script/realmStorage.ts
- src/cdp/cdpConnection.ts
Currently our codebase is adopting a mixed style. Make it uniform to increase readability.
> eslint: add consistent-generic-constructors rule

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextStorage.spec.ts
- src/bidiMapper/domains/context/browsingContextStorage.ts
- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/bidiMapper/domains/events/SubscriptionManager.ts
- src/bidiMapper/domains/script/realm.ts
- Use CommonDataTypes.BrowsingContext type instead of string
- Move findTopLevelContextId method to Browsing Context Storage
> Improve browsing context storage encapsulation

- src/utils/DefaultMap.spec.ts
This was mistakenly leftover in a prior CL.
> hotfix: describe.only -> describe

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
The root cause of the #620 was exactly as described @Lightning00Blade. While `Page.frameNavigated` event was fired before `Runtime.executionContextCreated`, as it's async, it's last part with cleaning realms was run after `Runtime.executionContextCreated` handled.
This fix includes 2 parts:
1. Remove all the async event handlers.
2. Rely on the `Runtime.executionContextsCleared` event rather then `Page.frameNavigated` to clean Realms.
Tested manually with Puppeteer and repro script from the https://github.com/puppeteer/puppeteer/issues/10032. Couldn't reproduce with Mapper Tab and therefor couldn't add e2e test.
> Fix BrowsingContext re-initialisation race condition

- package.json
- rollup.config.mjs
Otherwise the mapper times out. This fixes the following error message in the logs:
lib/cjs/bidiTab/bidiTab.js → lib/iife/mapperTab.js...
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
crypto (guessing 'require$$0')
created lib/iife/mapperTab.js in 1s
✅ [rollup] Executed successfully
> rollup: add output.globals for crypto module

- .github/workflows/e2e.yml
- .github/workflows/generate-wpt-report.yml
- .github/workflows/wpt-chromedriver.yml
- .github/workflows/wpt-mapper.yml
All other CI actions already use it, this is the last one left to migrate.
> CI: make wpt-mapper use @puppeteer/browsers package

- .github/workflows/e2e.yml
- .github/workflows/generate-wpt-report.yml
- .github/workflows/publish-on-tag.yml
- .github/workflows/wpt-chromedriver.yml
- .github/workflows/wpt-mapper.yml
- README.md
- runBiDiServer.sh
- runWPT.sh
- src/bidiServer/index.ts
And do a bunch of CI standardization and cleanup:
- add CHROMEDRIVER variable to runWPT.sh
- do not update expectations by default
- expose --timeout-multiplier as a variable
- github actions: simplify matrix
- github actions: use env: construct
- pip: set PIP_DISABLE_PIP_VERSION_CHECK=1 to reduce log noise in CI
- rename WPT_BROWSER_PATH / CHROME_BIN -> BROWSER_BIN for simplicity
> Uniformly use runWPT.sh everywhere in CI

- package-lock.json
- package.json
Building mapper locally (`npm link`) will use it's `node_modules` so we will have two different version of `devtools-protocol` of the Puppeteer side. That makes the Types incompatible with each other. Let's keep them in sync unless that is something that mapper need.
> chore: revert Protocol to Puppeteer's version

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextStorage.ts
The main purpose of this PR is to add `allChildren()` (flattened), but I did some prefactoring as well.
The main benefit now is that `BrowsingContextImpl` is now only stored in the storage. It's not duplicated in the `Impl` class itself via children. This makes it easier to maintain it / reason about it.
> prefactor browsing context classes and add all children method

- tests/test_serialization.py
Fixes e.g. https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/4929488274/jobs/8809183115, which is failing at HEAD (due to `chromium@latest` in CI).
> hotfix: fix test_serialization: include children in assertion

- .eslintrc.js
- src/bidiMapper/BidiServer.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/cdpTarget.ts
- src/bidiMapper/domains/script/realm.ts
- src/cdp/cdpConnection.ts
- src/utils/processingQueue.spec.ts
- src/utils/processingQueue.ts
We saw that in our (Puppeteer) test we never close the page. [Action](https://github.com/puppeteer/puppeteer/actions/runs/4936034522/jobs/8823137946?pr=10121). 
For some of our test that don't require a browser, this open -> close happens too fast so the initialization never succeeded and Mapper throws Unhandled Errors.
This PR is an attempt to fix it, but can't verify as test pass locally.
> fix: suppress error for Target closed

- .github/workflows/e2e.yml
- .github/workflows/generate-wpt-report.yml
- .github/workflows/unit.yml
- .github/workflows/wpt.yml
so that GitHub actions can cancel the runs for outdated commits.
See https://docs.github.com/en/actions/using-jobs/using-concurrency
> chore: add concurrency options to workflows

- src/utils/EventEmitter.ts
Similar to how the NodeJS EventEmitter is type we should expect to return this, this make it easier to extend.
> chore: EventEmitter should return type this

- package.json
Spec files are not necessary.
Bug: #727
Closes: #727
Docs: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files
Test: `npm publish --dry-run`
> Remove unneeded files from npm package

- .pre-commit-config.yaml
- test-report/htmlWptReportFormatter.mjs
v3.0.0-alpha* behaves differently than v2.8.8. Since we use v2.8.8 in package.json (via `npm run prettier` / `npm run format`), we should be consistent in pre-commit, otherwise formatting behaviors may differ.
The `additional_dependencies` workaround comes from https://github.com/pre-commit/mirrors-prettier/issues/29#issuecomment-1332667344 and it is needed because of
https://github.com/pre-commit/mirrors-prettier/issues/29. An upstream bug is available at
https://github.com/pre-commit/mirrors-prettier/pull/39
> pre-commit: add prettier v2.8.8

- src/bidiMapper/domains/script/scriptEvaluator.ts
`InvalidArgumentException` is not spec-compliant for deserializing; it states to use `NoSuchNodeException` if the Node cannot be found (e.g. an invalid sharedId will yield no Node). It should be also opaque whether a given `sharedId` fails to get a Node. See https://w3c.github.io/webdriver-bidi/#:~:text=To%20deserialize%20shared%20reference
> Use `NoSuchNodeException` instead of `InvalidArgumentException`

- .pre-commit-config.yaml
- src/utils/uuid.ts
Verified the pre-commit hook works:
```
check nodejs `self.`.....................................................Failed
- hook id: node-self
- exit code: 1
src/utils/uuid.ts:35:  self.crypto.getRandomValues(randomValues);
```
Follow-up-of: https://github.com/GoogleChromeLabs/chromium-bidi/pull/753
> Remove `self.` from TypeScript code

- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigate/error.py.ini
[Re-enable browsing_context/navigate/error.py](https://github.com/GoogleChromeLabs/chromium-bidi/pull/757/commits/448ada1ab793fc847b4e57dfef5615d7fb81da0c) 
It does not appear to be flaky anymore.
`wpt run` flags for debugging: https://web-platform-tests.org/running-tests/command-line-arguments.html?highlight=rerun#debugging
Closes: #463
> Re-enable `browsing_context/navigate/error.py`

- rollup.config.mjs
- src/utils/uuid.ts
Checks which crypto module to use. Possible environments are:
1) browser in a secure context
2) browser in a insecure context
3) node with the webcrypto enabled (--experimental-global-webcrypto)
4) node with the webcrypto disabled (current LTS)
> chore: remove global crypto

- .github/workflows/wpt.yml
This would allow us to manually trigger WPT jobs on-demand.
Potential future use cases:
- manually re-run, with verbose logging
- manually re-run, but only a subset of tests
- manually re-run, and auto-commit WPT expectations
Since this seems to only take effect when it's merged in main, also add one checkbox input which we can use for testing / iteration later on.
This is similar to how chrome for testing does it: https://github.com/GoogleChromeLabs/chrome-for-testing/blob/c0c46b46178cb4aa2d2897496ae902125e8e575b/.github/workflows/build.yml#L24
Bug: #361
Docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
> Add workflow_dispatch to WPT workflow

- .github/workflows/wpt.yml
Recreates #747, with support from #768, to only auto-commit when explicitly running the WPT workflow manually and selecting the "auto-commit" checkbox.
Bug: #361
> CI: add support for auto-commiting WPT expectations

- src/bidiMapper/domains/network/networkProcessor.ts
- src/bidiMapper/domains/network/networkRequest.ts
It looks like if the network serves from `Memory Cache` a separate event is send that signals that.
That brakes Mapper as the network deferred are never resolved.
> fix: Network Module stuck if ServedFromCache is send

- .github/workflows/wpt.yml
We need to add `always()` otherwise the child job never runs on failure (which is exactly when we want it to run!).
Source: https://stackoverflow.com/questions/71430668/how-to-run-a-github-actions-job-on-workflow-failure
This is a small follow-up from https://github.com/GoogleChromeLabs/chromium-bidi/pull/774
> Force wpt auto-commit to run when the wpt job fails

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextStorage.ts
Placing `findTopLevelContext` in a class getter improves semantics since it will always exist if the initial context can be obtained.
> Remove `findTopLevelContext` in favor of class getter

- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/bidiMapper/domains/network/networkProcessor.ts
- src/bidiMapper/domains/network/networkRequest.ts
- src/protocol/protocol.ts
- tests/test_network.py
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_started/response_started_cached.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/network/response_started/response_started.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/network/response_started/response_started_cached.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_started/response_started_cached.py.ini
See commit history for changes.
Bug: https://github.com/GoogleChromeLabs/chromium-bidi/issues/765
Spec: https://w3c.github.io/webdriver-bidi/#module-network
> network: miscellaneous changes

- package-lock.json
- package.json
Unblocks use of `reload` in Puppeteer.
> Release 0.4.11

- src/bidiMapper/domains/network/networkRequest.ts
In https://github.com/GoogleChromeLabs/chromium-bidi/pull/764/files#diff-8dae632dd7e595539b5d6e2772f812e44d528c60f7b8e5ec584b4835b3bd8e88R290 
A change was accidentally merged that made the `fromCache` parameter not respect the `Response.servedFromCache` event.
> fix: recover `fromCache` change

- tests/test_browsing_context.py
- tests/test_preload_script.py
Disable one of the tests as it's currently not possible to distinguish cache hits from misses.
Bug: #650
Follow-up-of: #742
> browsingContext.reload: add ignoreCache tests

- src/bidiMapper/domains/context/browsingContextImpl.ts
- tests/test_screenshot.py
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/capture_screenshot/frame.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/capture_screenshot/frame.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/capture_screenshot/frame.py.ini
`browsingContext.captureScreenshot`: more spec compliance
- Stop actively focusing the current tab.
- Use Page.getLayoutMetrics to retrieve the screenshot rect clip
- Pass sensible arguments to the CDP method.
Bug: #514
> `browsingContext.captureScreenshot`: more spec compliance

- .gitignore
- tests/test_screenshot.py
> `browsingContext.captureScreenshot`: add a method to E2E save images

- src/bidiMapper/CommandProcessor.ts
- src/protocol/protocol.ts
Inspired by https://github.com/w3c/webdriver-bidi/pull/439
I wanted to add "NewResult" to the enum but it's not available yet in mapper. So I just made some drive-by refactoring.
Spec: https://w3c.github.io/webdriver-bidi/#module-session
> improve Session spec compliance

- .pre-commit-config.yaml
This is needed when creating PRs that fully include the WPT repository (e.g. with `git subtree`) for debugging purposes such as #818, otherwise the pre-commit github action times out due to the numerous amount of files in the WPT repository.
> pre-commit: explicitly exclude wpt/ directory

- .github/workflows/pre-commit.yml
- npm cache
- wireit cache
This shaves a few seconds off the pre-commit action, and makes the file
consistent with the other ones in our repository.
> pre-commit: add caching to github action

- runWPT.sh
...to make it easier to run on gLinux out-of-the-box, without manually setting the browser path.
> linux: set `BROWSER_BIN` to a sensible default

- .eslintrc.js
- src/bidiMapper/BidiServer.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/PreloadScriptStorage.spec.ts
- src/bidiMapper/domains/context/PreloadScriptStorage.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/browsingContextStorage.ts
- src/bidiMapper/domains/context/cdpTarget.ts
- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/bidiMapper/domains/events/SubscriptionManager.ts
- src/bidiMapper/domains/input/ActionDispatcher.ts
- src/bidiMapper/domains/input/ActionOption.ts
- src/bidiMapper/domains/input/InputState.ts
- src/bidiMapper/domains/input/InputStateManager.ts
- src/bidiMapper/domains/log/logManager.ts
- src/bidiMapper/domains/network/networkProcessor.ts
- src/bidiMapper/domains/network/networkRequest.ts
- src/bidiMapper/domains/script/channelProxy.ts
- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/domains/script/realmStorage.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
- src/bidiServer/mapperServer.ts
- src/bidiTab/bidiTab.ts
- src/cdp/cdpConnection.ts
- src/protocol-parser/protocol-parser.ts
- src/utils/EventEmitter.ts
- src/utils/processingQueue.ts
- src/utils/websocketTransport.ts
Prefer to use "import type" when possible.
This allows transpilers to drop imports without knowing the types of the dependencies.
Docs: https://typescript-eslint.io/rules/consistent-type-imports/
> eslint: add consistent-type-imports

- src/bidiMapper/domains/context/browsingContextImpl.ts
The image was capturing empty parts if the content was overflowing.
Image has 200 boxes
> fix: screenshots failing when setViewport is used

- src/bidiServer/bidiServerRunner.ts
- src/bidiServer/mapperServer.ts
- src/bidiTab/bidiTab.ts
- src/cdp/cdpConnection.ts
The ◂▸ characters, used alongside sending and receiving debug messages, were ending up in the minified mapperTab.js file, which caused Windows presubmits on Chromium to fail due to some encoding error.
By completely removing unicode characters this problem is eliminated.
Closes: #858
> replace all unicode characters with ascii ones

- rollup.config.mjs
- src/bidiServer/bidiServerRunner.ts
- src/bidiServer/mapperServer.ts
- src/bidiTab/bidiTab.ts
- src/cdp/cdpConnection.ts
```
$ npm run build; npx is-ascii-safe-cli lib/iife/mapperTab.js
> chromium-bidi@0.4.12 build
> wireit
🏃 [tsc] Running command "tsc --build src/tsconfig.json --pretty"
✅ [tsc] Executed successfully
🏃 [rollup] Running command "rollup -c"
lib/cjs/bidiTab/bidiTab.js → lib/iife/mapperTab.js...
created lib/iife/mapperTab.js in 1.2s
✅ [rollup] Executed successfully
✅ [build] No command to execute
1 file(s) are ASCII-safe.
```
Bug: #858
> Restore non-ASCII characters where applicable, ensuring they get escaped during minification

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/bidiMapper/domains/network/networkRequest.ts
- src/protocol/protocol.ts
- tests/test_browsing_context.py
Unblocks `waitForNavigation` in Puppeteer.
After talking with @sadym-chromium we should only give navigation to the initial request (document request).
But all CDP requests triggered by initial parsing of the document have the LoaderId set, so we relay on requestId matching the loaderId.
> feat: add fragmentNavigated event

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/network/networkRequest.ts
The `Target.targetInfoChanged` does not have an SessionId as it happens on the top level.
I am was looking into the NavigationStarted (BiDi implementation) event when I notice that.
> chore: small fix

- README.md
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/cdpTarget.ts
- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/bidiMapper/domains/events/SubscriptionManager.ts
- src/cdp/cdpClient.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
- tests/screenshot/test_screenshot.py
- tests/test_cdp.py
- tests/test_network.py
- tests/test_subscription.py
Currently we if we want to get the CDP event we can only pass the `cdp` param. 
That will make all the event from CDP pass though the WebDriver BiDi socket connection.
We want to send only the events that the user is interested for Puppeteer `Tracing.tracingComplete`.
for that I remove the send all `cdp` and replace it with individual `cdp.Tracing.tracingComplete`.
That way only this specific event is send. 
Ref Puppeteer https://github.com/puppeteer/puppeteer/pull/10453 and logs:
> feat: make the BiDi+ events less "chatty"

- .github/workflows/e2e.yml
- .github/workflows/wpt.yml
- README.md
- src/bidiServer/bidiServerRunner.ts
- src/bidiServer/index.ts
- src/bidiServer/mapperServer.ts
- src/bidiTab/bidiTab.ts
- src/bidiTab/mapperTabPage.ts
- src/cdp/cdpConnection.ts
- src/utils/log.ts
As suggested by DEBUG we should have a common prefix for all our  statements, that also remove some clutter around 
`bidiMapper:mapperDebug` that has mapper 2 times.
in the feature we may want to change to something like `crbidi` compare to `bidi` to signify that it's chrome bidi over other bidi package.
CC @thiagowfx
> chore: use common prefix for debug

- tests/test_viewport.py
These are not intended to be exhaustive; for that, we rely on WPT.
Bug: #868
> fix: expand viewport validation tests

- src/bidiMapper/domains/network/networkRequest.ts
- tests/test_network.py
Note: In the absence of WPT tests that verify this field, it may be slightly off by a few bytes.
Bug: #765
> network: populate response headers size

- .vscode/settings.json
This is needed to avoid formatting WPT files (thus avoiding adding noise) when submitting upstream PRs.
> chore: vscode: remove auto format

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- tests/test_browsing_context.py
- tests/test_realm.py
BiDi defines that we should run the https://html.spec.whatwg.org/multipage/document-sequences.html#close-a-top-level-traversable, which tells us to run the unload events.
Should we also provide a way to `force close` in BiDi spec?
> fix: use non-force close for BrowsingContext.close

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/input/InputStateManager.ts
- src/bidiMapper/domains/network/networkProcessor.ts
- src/bidiMapper/domains/network/networkRequest.ts
- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/domains/script/realmStorage.ts
- src/cdp/cdpClient.ts
- src/cdp/cdpConnection.ts
- src/utils/EventEmitter.spec.ts
- src/utils/EventEmitter.ts
Recently we changed to use `Page.close` (#939) which does not destroy the target immediately.
In puppeteer some times we test timeouts of `1ms` which the command is send and failed on Puppeteer end (never awaited). The problem is we try close the page, but not forcing lets the navigation starting and some NetworkEvents to be sent though CDP, but due to being deferred they never resolve and the ProcessingQueue stops working.
> fix: Network Module clogging Processing Queue

- src/bidiMapper/domains/context/browsingContextImpl.ts
Bug: #518
Spec: https://github.com/w3c/webdriver-bidi/issues/473
WPT: https://github.com/web-platform-tests/wpt/pull/40872
> feat(print): throw unsupported operation when content area is empty

- src/bidiMapper/BidiNoOpParser.ts
- src/bidiMapper/BidiParser.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiTab/BidiParserImpl.ts
- src/protocol-parser/protocol-parser.ts
- tests/test_activate.py
WPT: https://github.com/web-platform-tests/wpt/pull/40964
Spec: https://github.com/w3c/webdriver-bidi/pull/453
> feat: implement browsingContext.activate

- tools/wpt-report-builder/builder.mjs
- tools/wpt-report-builder/formatter.mjs
- tools/wpt-report-builder/formatter.spec.mjs
"Tentative" means a WPT test was written even though consensus was never
reached in the spec whether it will actually take place.
Tentative tests will usually never pass and they are not final.
Since these are not spec finalized, they only add noise to the report.
Once (if ever) consensus is reached upon upstream, the tentative suffix
is removed from the WPT test file, then the tests appear in the report
as usual.
chore: misc changes
test: add unit test
docs: add jsdoc
> ci: wpt: exclude tentative tests from report

- .pre-commit-config.yaml
Rationale: It is the slowest hook.
> ci: move eslint to become the last step of pre-commit

- src/bidiMapper/domains/network/networkProcessor.ts
- src/utils/deferred.ts
If the promise was rejected multiple times and unhandled error was thrown.
> fix: Deferred no multiple resolved/rejects

- src/protocol-parser/protocol-parser.ts
- webdriver-bidi (autogenerated) uses `zod`
- protocol-parser (manual) uses `z`
Be consistent and use only one form.
> chore: import zod consistently as `z`

- src/bidiMapper/domains/script/ScriptProcessor.ts
- src/bidiMapper/domains/script/realm.ts
- tests/browsing_context/test_create.py
- tests/script/test_add_preload_script.py
- tests/script/test_call_function.py
The rest of tests will be covered by WPT.
> feat(script): implement user activation

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/cdpTarget.ts
- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/domains/log/logManager.ts
- src/bidiMapper/domains/network/NetworkManager.ts
- src/bidiMapper/domains/network/networkRequest.ts
- src/bidiMapper/domains/script/channelProxy.ts
- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/domains/session/SessionProcessor.ts
`EventManager` is internal class we should pass it instead of Interface as that way it improves the IDE, and remove an else unused interface
> chore: remove IEventManager as it provides no value

- tests/browsing_context/test_create.py
- tests/browsing_context/test_fragment_navigated.py
- tests/browsing_context/test_nested_browsing_context.py
- tests/script/test_add_preload_script.py
- tests/script/test_remove_preload_script.py
Use `goto_url` to simplify test code.
We should consider adding some for `script.evaluate` as we use that a lot.
> chore: use helper to navigate

- src/bidiMapper/domains/input/ActionDispatcher.ts
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/pointer_touch.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/pointer_touch.py.ini
If there are no buttons pressed, we do a no-op as specified in https://w3c.github.io/webdriver/#dfn-perform-a-pointer-move
> chore: no-op for trivial pen and touch movements

- src/bidiMapper/domains/input/ActionDispatcher.ts
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/pointer_touch.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/pointer_touch.py.ini
If there are no buttons pressed, we do a no-op as specified in https://w3c.github.io/webdriver/#dfn-perform-a-pointer-move
> fix: no-op for trivial pen and touch movements

- src/bidiMapper/domains/context/browsingContextImpl.ts
It's possible for more than one sandbox to be created due to provisional frames. In this case, it's always the first one (i.e. the oldest one) that is more relevant since the user may have set that one up already through evaluation.
> fix: remove sandbox check

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- src/bidiMapper/domains/network/NetworkManager.ts
- src/bidiMapper/domains/network/NetworkStorage.spec.ts
- src/bidiMapper/domains/network/NetworkStorage.ts
- src/utils/assert.ts
This should cover the base case of redirects, some edge cases may need to be fix similar to what to do with the `responseExtraInfo` that's emitted between events. Puppeteer sort handles them as Reponses.
> feat: add network redirects

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- tests/browsing_context/test_reload.py
Blocked until WPT tests are updated: https://github.com/GoogleChromeLabs/chromium-bidi/pull/1255#issuecomment-1707285470
Issue: https://github.com/w3c/webdriver-bidi/issues/527
Issue: #650
> feat: `browsingContext.reload`: return the navigation instead of empty

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/print/margin.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/print/margin.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/print/margin.py.ini
Revert "feat: throw InvalidArgument instead of UnsupportedOperation for print… (#1280)"
This reverts commit b32ea31ca346caacf4af673c857ab97cb1e9ba45.
test: update wpt expectations
Chicken-and-egg: This PR will not be needed if
https://github.com/web-platform-tests/wpt/pull/41945 is merged.
> test: fix browsingContext.print `test_margin_same_as_page_dimension`

- README.md
When rolling the mapper.
Fixed: #1306
> docs: document how to update WPT expectations metadata in chromium src/

- src/bidiMapper/domains/input/ActionDispatcher.ts
- src/bidiMapper/domains/input/InputSource.ts
- tests/input/__snapshots__/test_input.ambr
- tests/input/test_input.py
Previously, the click count was measured globally among all buttons. This was incorrect as browsers separate click count by button.
> fix: separate click count by button

- .github/workflows/puppeteer.yml
For node set-up cache to work you need to have a `package-lock.json`.
As we will run this infrequently we can opt to not use cache.
> ci: cache support is only top level

- .github/workflows/puppeteer.yml
We need to set up the correct directory to do this on else `.browser` file is not found as script look at `cwd()/.browser`.
> ci: script look relative to cwd

- src/bidiMapper/domains/input/ActionDispatcher.ts
The default in CDP (i.e. 1) causes the width to equal 2.
> fix: use 0.5 for default radiusX and radiusY

- .pre-commit-config.yaml
E.g. so that we can use `refactor:`.
> ci: pre-commit conventional-pre-commit: allow free-form prefixes

- tests/test_helpers.py
This added syntactic sugar is more flexible when we want to wait for any event from a given domain, e.g. "cdp" or "network".
> test: pytest `wait_for_event` helper: match prefixes

- src/bidiMapper/domains/context/CdpTarget.ts
- src/bidiMapper/domains/network/NetworkProcessor.ts
- src/bidiMapper/domains/network/NetworkRequest.ts
- src/bidiMapper/domains/network/NetworkStorage.spec.ts
- src/bidiMapper/domains/network/NetworkStorage.ts
- tests/conftest.py
- tests/network/test_add_intercept.py
- tests/network/test_continue_request.py
- tests/network/test_fail_request.py
- tests/network/test_remove_intercept.py
Furthermore, update some E2E tests so that they do not rely on CDP events.
Bug #644, #1080
Co-authored-by: Maksim Sadym <sadym@chromium.org>
Re-created from #1400.
> feat: unblock event queue when network events are blocked

- src/bidiServer/BrowserInstance.ts
- src/bidiServer/MapperCdpConnection.ts
- src/bidiServer/reader.ts
- src/bidiTab/bidiTab.ts
Preparation for multiple session support. http://go/webdriver:bidi-multiple-sessions-proposal
**_Step 1._** Simplify launching process. 
Switch Mapper Tab launch into 2 phases:
* Prepare all the handlers and transports.
* Launch the Mapper instance with some parameters (`selfTargetId ` for now).
> misc: Set `selfTargetId` via `evaluate`

- .github/dependabot.yml
Instead of receiving dozens of PRs per month, each one for an individual dependency, have dependabot group PRs into a single one per ecosystem.
Inspired by https://github.com/puppeteer/puppeteer/pull/11126
Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
> ci: introduce dependabot groups

- tests/conftest.py
- tests/network/test_add_intercept.py
- tests/network/test_remove_intercept.py
- tests/tools/local_http_server.py
Switch from `example.com` to local http server when possible.
Out of scope: 
* hardcoded addresses in url patterns.
Bug: #575
> test: use local http server when possible

- package.json
They are extremely flaky in CI.
Tested:
- Before: 268 passed, 11 skipped, 3 xfailed
- After: 262 passed, 11 skipped, 2 xfailed
Fixed: #1407, #1452
> ci: ignore input tests in headful mode

- src/bidiServer/BrowserInstance.ts
- src/bidiServer/MapperCdpConnection.ts
- src/bidiServer/SimpleTransport.ts
- src/bidiServer/WebSocketServer.ts
Preparation for multiple session support. http://go/webdriver:bidi-multiple-sessions-proposal
**_Step 3._** Use BiDi session to communicate to Mapper Tab.
* Extract a `BiDiSession` class and communicate via it.
* Remove `EventEmitter` from BrowserInstance and MapperCdpConnection.
> refactor: Extract BiDi session in server runner

- src/bidiTab/bidiTab.ts
Add back `window.setSelfTargetId` for backward compatibility with ChromeDriver Classic, until https://crrev.com/c/4952609 is landed in stable.
> fix: Add `window.setSelfTargetId` for backward compatibility with chrome driver

- src/bidiMapper/domains/network/NetworkRequest.ts
- src/utils/ProcessingQueue.ts
We are getting this error from Puppeteer `Promise rejection was handled asynchronously` the test in question is `should not leak listeners during navigation of 11 pages`.
The issue is that the `this.#getResponseReceivedEvent()` has an assert that for this test fails most likely the page gets destroyed by the time it hits it and then it fails due to the the deferred being cancelled.
I think I will want to refactor this further to make the function return `Result<>` rather than this assign. 
Just wanted to put a PR before moving to other things.
> chore: fix async code

- src/bidiMapper/domains/network/NetworkRequest.ts
- tests/network/test_continue_response.py
- tests/network/test_provide_response.py
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/capture_screenshot/capture_screenshot.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
> feat: network request: prioritize response status code over extraInfo

- src/bidiMapper/domains/script/PreloadScript.ts
- src/bidiMapper/domains/script/ScriptProcessor.ts
- tests/script/test_add_preload_script.py
This only makes the already created Contexts respect the PreloadScript, the newly create one will still run the script atm.
> feat: addPreloadScripts respects contexts param for old contexts

- tests/conftest.py
- tests/tools/local_http_server.py
Stop the request once the test finishes.
Bug: #575
> test: re-enable tests that use `hang_url`

- .pre-commit-config.yaml
c.f. https://github.com/pre-commit/mirrors-prettier/blob/main/.pre-commit-hooks.yaml and https://github.com/pre-commit/identify/blob/main/identify/extensions.py
> ci: speed up prettier/eslint pre-commit hooks and use types instead of files

- src/bidiMapper/domains/context/CdpTarget.ts
- src/bidiMapper/domains/script/PreloadScriptStorage.ts
- tests/script/test_add_preload_script.py
We should be OK using the global approach due to https://w3c.github.io/webdriver-bidi/#command-script-addPreloadScript 
Step 4  - making sure that the Context exits, if we don't already have it we in our storage.
Adding the note because on there was discussion around ID and sharing them between Multiple BiDi sessions. 
From Alex: The above is only true if we are adding the scripts to same origin iframes. This will not work for example for workers, cross-origin iframes and a like that create a new target, and per spec preload scripts should affect them as well.
Tracked at #1353
> feat: addPreloadScript respects new contexts

- tests/network/test_add_intercept.py
- tests/network/test_continue_request.py
- tests/network/test_continue_response.py
- tests/network/test_continue_with_auth.py
- tests/network/test_fail_request.py
- tests/network/test_provide_response.py
- tests/network/test_remove_intercept.py
In order to try to mitigate test flakiness.
Bug: #644, #1428
> ci: add wait=complete to all network intercept navigations

- src/bidiServer/WebSocketServer.ts
Example: <img width="731" alt="Screenshot 2023-10-27 at 11 05 56" src="https://github.com/GoogleChromeLabs/chromium-bidi/assets/2840106/fcca5904-8b11-48dc-9c58-1de56dbe9033">
Instead of having the output message string in a single line.
> feat(logging): pretty print received and sent bidi server messages

- tools/run-wpt.mjs
The current default of `8` seems to be slowing down CI significantly.
An increased timeout is useful for debugging purposes only.
> test(timeout): reset timeout multiplier to 4

- src/bidiMapper/domains/network/NetworkRequest.ts
Currently we ignore `favicon.ico` request. We should not block them for interception.
> fix: automatically continue ignored events

- src/bidiMapper/BidiNoOpParser.ts
- src/bidiMapper/BidiParser.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- src/bidiMapper/domains/context/BrowsingContextProcessor.ts
- src/bidiTab/BidiParser.ts
- src/protocol-parser/protocol-parser.ts
- tests/browsing_context/test_traverse_history.py
Fixed: https://github.com/GoogleChromeLabs/chromium-bidi/issues/1532
> feat: implement browsingContext.traverseHistory

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- tests/browsing_context/test_navigate.py
- tests/tools/local_http_server.py
If browsing context is closed, cancel all ongoing navigations.
Required for [Puppeteer tests](https://github.com/puppeteer/puppeteer/blob/9f161ec76b19c419bb1dd36357c09c044d5f82f4/test/src/launcher.spec.ts#L40).
> feat: abort navigation if network request failed

- tools/run-wpt.mjs
Docs: https://web-platform-tests.org/running-tests/command-line-arguments.html
Follow-up-of: #1544
> ci(wpt): add --retry-unexpected to complement --run-by-dir

- tools/run-wpt.mjs
Reverts GoogleChromeLabs/chromium-bidi#1549
WPT tests became false-positive: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/6868628016/job/18679609674
> Revert "ci(wpt): add --retry-unexpected to complement --run-by-dir"

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/BrowsingContextProcessor.ts
- src/bidiMapper/domains/context/CdpTarget.ts
- src/bidiServer/BrowserInstance.ts
- src/bidiServer/MapperCdpConnection.ts
- src/bidiServer/WebSocketServer.ts
- src/bidiTab/bidiTab.ts
- tests/browsing_context/__snapshots__/test_close.ambr
- tests/browsing_context/test_navigate.py
- tests/conftest.py
- tests/input/__snapshots__/test_input.ambr
- tests/network/test_fail_request.py
BREAKING CHANGE: `BidiServer.createAndStart` signature changed. New optional parameter `options` is added. Breaking change for Puppeteer, while ChromeDriver is not affected, as it uses the Mapper Tab.
When creating Mapper, add possibility to add `acceptInsecureCerts` parameter. Required to provide capability `acceptInsecureCerts`.
Alternative would be handling `session.new` command on the Mapper side, and forward capabilities there. But that would add an extra step to the ChromeDriver - Mapper link.
In order to respect capabilities from both Classic and Bidi, the Mapper launcher has to be refactored, so that it keeps sessions.
> feat!: `acceptInsecureCerts`

- README.md
docs: update WPT expectations regeneration in blink
Due to the remover of web_platform_tests_wptrunner.md, some links are
broken now. Fix those links with a new one.
We have also made a decision to not use metadata for WPTs. Updated the
instructions accordingly.
Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1474702
Fixed: #1306
Co-authored-by: Weizhong Xia <weizhong@google.com>
Pingback: https://crrev.com/c/5037684/
> docs: update WPT expectations regeneration in blink

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/domains/events/EventManager.ts
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/capture_screenshot/capture_screenshot.py.ini
Should help with #1079. Behavior should not have been changed as everything in the event emitter is synchronous
> refactor: try to break cycle

- .github/workflows/update-bidi-types.yml
Sometimes it is required to have types from not-yet merged branch of spec (https://github.com/GoogleChromeLabs/chromium-bidi/pull/1593). This PR provides a way to specify a branch of a specific commit to update types from.
> ci: extand `Update WebdriverBidi types` with a custom reference

- .github/workflows/e2e.yml
1. `pytest-rerunfailures` is not compatible with the `pytest-timeout plugin`: https://github.com/pytest-dev/pytest-rerunfailures/issues/99. This ends up with failing e2e with timeout with confusing output in [test runs](https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/6983089114/job/19003555638?pr=1593).
2. Rerun masks flaky tests, but should not: http://goto.google.com/webdriver:improve-operations.
> test: do not rerun e2e tests in CI

- src/bidiMapper/domains/context/BrowsingContextProcessor.ts
- src/bidiMapper/domains/context/BrowsingContextStorage.ts
- src/bidiMapper/domains/script/Realm.ts
- tests/script/__snapshots__/test_evaluate.ambr
- tests/script/test_evaluate.py
- tests/script/test_realm.py
- tests/test_helpers.py
Implements script evaluation for workers.
> feat: implement evaluate for dedicated workers

- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/traverse_history/context.py.ini
WPT `traverse_history/context.py` tests are flaky:
* https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/7220535002/job/19673658212
* https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/7220361889/job/19673108477
> test: skip flaky WPT `traverse_history/context.py` tests

- tests/script/test_evaluate.py
Sometimes the web worker may take some time before it's destroyed, so we need to increase the timeout for this test.
> chore: increase test_scriptEvaluate_dedicated_worker timeout

- src/bidiTab/bidiTab.ts
The required ChromeDriver change is landed in stable, so the method can be removed.
> chore: remove deprecated method

- .github/workflows/wpt-quick.yml
Exclude headful mapper WPT runner from quick WPT CI action, as:
1. Mapper config is not exposed to any external users, and is used only for dev purposes.
2. This configuration takes more then 7 minutes, while other configs are finished in under 5.
> test: don't run headful mapper in quick WPT

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/storage/StorageProcessor.ts
- tests/storage/__init__.py
- tests/storage/test_get_cookies.py
- tests/storage/test_set_cookies.py
- tests/test_helpers.py
Implement storage commands:
* `storage.getCookies`
* `storage.setCookie`
> feat: implement `storage.getCookies` and `storage.setCookie`

- package.json
The input is not part of the source tree so there is no need to wire it.
> chore: remove bidi-types from wireit

- src/bidiMapper/BidiNoOpParser.ts
- src/bidiMapper/BidiParser.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/input/InputProcessor.ts
- src/bidiMapper/domains/script/Realm.ts
- src/bidiTab/BidiParser.ts
- src/protocol-parser/protocol-parser.ts
- tests/input/__snapshots__/test_input.ambr
- tests/input/test_input.py
Spec: https://w3c.github.io/webdriver-bidi/#command-input-setFiles
Bug: https://github.com/GoogleChromeLabs/chromium-bidi/issues/1702
> feat: implement `Input.setFiles`

- tools/run-wpt.mjs
Store all logs under `logs` rather than under `out`. Also separates the headless and headful.
> chore: fix chromedriver log location

- .github/workflows/update-bidi-types.yml
Adding it along the lines with the existing workflow but I think it makes sense to move the generation to a script that can be easily run locally.
> ci: add automatic generation for permissions

- tools/generate-bidi-types.mjs
We should be using close when waiting for IO to be done. See https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/7582743061 for a successful run.
> ci: fix spawn

- src/bidiMapper/domains/storage/StorageProcessor.ts
- tests/storage/__init__.py
- tests/storage/test_get_cookies.py
- tests/storage/test_set_cookies.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/storage/set_cookie/partition.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/storage/set_cookie/partition.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/storage/set_cookie/partition.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/storage/set_cookie/partition.py.ini
Return all the cookies if `getCookies` is called with `BrowsingContextPartitionDescriptor` is called, not only a partitioned one originated from it.
As per spec:
> * Let browsing context be the result of [trying](https://w3c.github.io/webdriver/#dfn-try) to [get a browsing context](https://w3c.github.io/webdriver-bidi/#get-a-browsing-context) given partition spec["context"].
> * Let partition key be the [key](https://w3c.github.io/webdriver-bidi/#storage-partition-key) of browsing context’s [associated storage partition](https://w3c.github.io/webdriver-bidi/#associated-storage-partition).
> * Return [success](https://w3c.github.io/webdriver/#dfn-success) with data partition key.
While: 
> Each [browsing context](https://html.spec.whatwg.org/multipage/document-sequences.html#browsing-contex …
> feat: return all cookies for a given browsing context

- src/bidiMapper/domains/context/BrowsingContextProcessor.ts
the old headless has a different implementation.
Test coverage will be provided by WPT.
> fix: handle headless errors when creating a target

- .github/workflows/update-browser-version.yml
Don't override previous changes in the branch.
1. The action step ["Checkout `browser-automation-bot/update-browser-version` if exits"](https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/7693953409/job/20963706285) failed with "error: pathspec 'browser-automation-bot/update-browser-version' did not match any file(s) known to git". `fetch-depth: 0` should fix the issue.
2. The `Create Pull Request` step defaults base to the checked out branch, which is not correct in case of the task was run from a branch.
> chore: fix `update-browser-version`

- src/bidiMapper/domains/storage/StorageProcessor.ts
- tests/conftest.py
- tests/storage/test_get_cookies.py
- tests/storage/test_set_cookies.py
Get `userContext` from partition or from the linked browsing context.
> feat: support user context in cookies API

- src/cdp/CdpClient.spec.ts
There were errors coming from this UnitTest
```
(node:1270676) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
at handledRejection (node:internal/process/promises:173:23)
at promiseRejectHandler (node:internal/process/promises:119:7)
at Promise.then (<anonymous>)
at Proxy.<anonymous> (/usr/local/google/home/nvitkov/bidi/node_modules/chai-as-promised/lib/chai-as-promised.js:169:53)
at Proxy.<anonymous> (/usr/local/google/home/nvitkov/bidi/node_modules/chai-as-promised/lib/chai-as-promised.js:47:29)
at Proxy.methodWrapper (/usr/local/google/home/nvitkov/bidi/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
at Context.<anonymous> (/usr/local/google/home/nvitkov/bidi/src/cdp/CdpClient.spec.ts:223:53)
```
> test: fix Promise rejection was handled asynchronously

- src/bidiMapper/domains/script/DedicatedWorkerRealm.ts
Puppeteer tracks realms by `context` field instead of tracking `owners`. This commit adds a temp hack to allow Puppeteer that tracking.
> feat: add temp `context` into worker realm for Puppeteer

- .github/workflows/update-browser-version.yml
Roll back latest changes in `update-browser-version.yml`, as it creates closed PRs. https://github.com/GoogleChromeLabs/chromium-bidi/pull/1813
> ci: roll back browser update CI job

- .github/workflows/publish.yml
We don't need Python here and the unit test provide little value as they are not flaky and passed for release PR.
> ci: remove set-up in publish

- .bandit
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/browser/BrowserProcessor.ts
- tests/browser/test_create_user_context.py
- tests/conftest.py
- tests/tools/http_proxy_server.py
- tools/http-proxy.mjs
This PR adds a python proxy server wrapper over a Node.js proxy server to test the URLs.
> feat: allow Chrome-specific params in user contexts

- src/bidiMapper/domains/context/BrowsingContextProcessor.ts
- src/bidiMapper/domains/script/Realm.ts
- src/bidiMapper/domains/script/WorkerRealm.ts
- tests/script/test_evaluate.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/script/realm_created/realm_created.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/script/realm_destroyed/realm_destroyed.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/realm_created/realm_created.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/realm_destroyed/realm_destroyed.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/realm_created/realm_created.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/realm_destroyed/realm_destroyed.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/realm_created/realm_created.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/realm_destroyed/realm_destroyed.py.ini
This PR generalizes DedicatedWorkerRealm to other worker realms.
Also (hopefully) fixes the flaky test by ensuring the worker is actively doing something for the duration of the test.
Fixed: https://github.com/GoogleChromeLabs/chromium-bidi/issues/1166, https://github.com/GoogleChromeLabs/chromium-bidi/issues/1830
> feat: generalize worker realm

- src/bidiTab/mapperTabPage.ts
> fix: limit the mapper tab to 200 lines of logs

- src/bidiMapper/domains/permissions/PermissionsProcessor.ts
- src/protocol-parser/protocol-parser.ts
- tests/permissions/__init__.py
- tests/permissions/test_set_permission.py
This PR adds `goog:` prefixed user context to allow use cases required by Puppeteer. Once permissions spec issue is resolved https://github.com/w3c/permissions/pull/438 we can remove the prefix.
> feat: support user context in permissions

- pytest.ini
- tests/script/test_realm.py
Out of last `12` failures of e2e in main, `5` are because of the `test_realm_dedicated_worker` timeout. This is because of the worker's realm is not destroyed immediately. Increasing timeout of the test `test_realm_dedicated_worker` should address the flakiness.
> test: increase e2e test timeout to fight the flakiness

- tests/network/test_continue_request.py
- tests/network/test_continue_response.py
- tests/network/test_continue_with_auth.py
- tests/network/test_fail_request.py
- tests/network/test_provide_response.py
4 out of 12 last e2e failures in main was due to this problem in the following tests:
* test_continue_response_invalid_reason_phrase
* test_fail_request_with_auth_required_phase
* test_continue_request_invalid_phase_response_started
But this issue not specific for this tests. So disabling all the tests using `create_blocked_request` until the #1883 is addressed.
> test: disable flaky network interception tests

- README.md
- src/bidiMapper/BidiNoOpParser.ts
- src/bidiMapper/BidiParser.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/cdp/CdpProcessor.ts
- src/bidiTab/BidiParser.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/cdp.ts
- tests/script/test_realm.py
`cdp.resolveRealm` resolves a realm ID to an executionContextId.
This is needed for Puppeteer to adopt nodes from ARIA queries.
This is a workaround for https://crbug.com/326258571
> fix: add `cdp.resolveRealm` command

- package.json
- tools/bidi-server.mjs
- tools/run-bidi-server.mjs
- tools/run-e2e.mjs
Creates a separate E2E runner file. That way we can sync the output of `bidi-server.mjs` and `pytest`, which make is easier to see where a test starts and end in the logs.
E2E runs will only print PyTest output to reduce the time need to see what fails. The message logs will be uploaded as artifacts which can be downloaded. The `VERBOSE` is set to `true` always so we get the `CDP` logs as well.
> ci: better e2e logs

- .github/workflows/wpt-quick.yml
- .github/workflows/wpt.yml
The node js mapper runner is not used by real users,  and is there only for development purposes. The node js runner re-runs browser for each individual test, which makes it run for a long time and causes timeouts. Having that, there is no value in running headful mapper wpt tests in CI. Expectations are kept, as manual run is still possible.
> ci: don't run wpt headful mapper

- tools/run-wpt.mjs
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/invalid.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/invalid.py.ini
Currently if we encounter the WPT fixture that does `fetch` we wait for 12 sec before it fails, which is absurd amount of time.  
Extracting from other PR to see if anything fails.
> test: make test fail faster

- README.md
- tools/run-e2e.mjs
When running `npm run e2e` we only collect `Chromium-BiDi` log when the test fails rather then all the time. 
This reduces the overall size of logs to just a few KB compare to 7-8MB  previously, also this improves readability.
> ci: BiDi server logs only when test fail

- tools/run-e2e.mjs
The original RegEx did not catch single digit percentage and 100%.
> test: fix logging

- tools/wpt-report-builder/formatter.mjs
Sort tests in the html WPT test report to align with [wpt.fyi](https://wpt.fyi/results/webdriver/tests/bidi?label=master&label=experimental&aligned) and to ease analyses.
> ci: in wpt html report sort tests by path and name

- src/bidiMapper/domains/network/NetworkRequest.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
BiDi spec change at https://github.com/w3c/webdriver-bidi/pull/674. There is more info there.
> fix: add `authChallenges` to response

- tools/run-wpt.mjs
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/activate/activate.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/capture_screenshot/capture_screenshot.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/capture_screenshot/clip.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/capture_screenshot/frame.py.ini
With this PR, the headful mode actually runs the headful mode:
1) removed some failed test expectations that pass in headful
2) drive-by: full logging for wpt commands
> test: fix headful mode actually using new headless in WPT

- .github/workflows/wpt.yml
Proposal: let's switch the dashboard to report numbers from headful instead of headless as it is a configuration that matches the user experience the most?
> ci: show chromedriver headful results in wptreport site

- .github/workflows/wpt.yml
https://docs.github.com/en/actions/learn-github-actions/expressions#always
Currently if you cancel a run it will commit expectations which is bad as it make the PR useless.
> ci: don't commit for cancelled runs

- rollup.config.mjs
The third party will be further processed by a script to be incorporated into README.chromium of //third_party/bidimapper dependency. The JSON format is more convenient for scripting.
> build: output third party notices in custom format

- src/bidiMapper/domains/storage/StorageProcessor.ts
- tests/storage/test_delete_cookies.py
- tests/storage/test_get_cookies.py
- tests/storage/test_set_cookies.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/storage/delete_cookies/invalid.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/storage/get_cookies/invalid.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/storage/set_cookie/invalid.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/storage/delete_cookies/invalid.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/storage/get_cookies/invalid.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/storage/set_cookie/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/storage/delete_cookies/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/storage/get_cookies/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/storage/set_cookie/invalid.py.ini
Parse error when setting/getting cookies to catch `NoSuchUserContextException`.
+ updated `test_cookie_set_partition_user_context` to test what it was intended to.
> fix: correctly process `NoSuchUserContextException` in cookie operations

- .eslintrc.js
- package-lock.json
- package.json
This should prevent our production code from pulling `devDependencies`.
> chore: move deps and add rule

- src/bidiMapper/domains/context/CdpTarget.ts
- src/bidiMapper/domains/network/NetworkProcessor.ts
- src/bidiMapper/domains/network/NetworkRequest.ts
- src/bidiMapper/domains/network/NetworkStorage.spec.ts
- src/bidiMapper/domains/network/NetworkStorage.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/add_intercept/contexts.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/add_intercept/contexts.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/add_intercept/contexts.py.ini
This PR move the logic to for when to enable the Fetch Domain to the CdpTarget. That way we can manage interception more gradually. 
Also fixes an issue where if we `network.addInterception` then `network.subscribe`, the interception would have not been enabled.
Also fixes an issue if a CdpTarget is created later but network interception was enable globally before that.
> feat: add support for `contexts` in `addInterception`

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/script/ScriptProcessor.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/script/call_function/target.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/script/evaluate/target.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/call_function/target.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/evaluate/target.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/call_function/target.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/evaluate/target.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/call_function/target.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/evaluate/target.py.ini
Limitation to Zod.union is that i check the first one and cuts the object in its shape if it passes so we only get the `Realm`.
This works around this until we add a `type: 'realm'` and `type: 'context'` to the Script.Target https://github.com/w3c/webdriver-bidi/issues/635
> fix: workaround issue with Script.Target

- .github/workflows/update-bidi-types.yml
Required for https://github.com/google/cddlconv/pull/24
> ci: bump cddlconv to v 0.1.4

- tools/wpt-report-builder/labelled-tests.mjs
This ensures the previously hardcoded set of `chromium-bidi-2023` tests stays in sync with the upstream label, in case any tests get renamed, deleted, or added.
> chore: dynamically read `chromium-bidi-2023` label from upstream

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- src/protocol-parser/generated/webdriver-bidi.ts
- src/protocol/ErrorResponse.spec.ts
- src/protocol/ErrorResponse.ts
- src/protocol/generated/webdriver-bidi.ts
- tests/browsing_context/test_locate_nodes.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/locate_nodes/invalid.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/locate_nodes/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/locate_nodes/invalid.py.ini
Support `invalid selector` error code in [`browsingContext.locateNodes`](https://w3c.github.io/webdriver-bidi/#commands-browsingcontextlocatenodes).
This PR only partly updates the generated types with only relevant change.
> feat: `invalid selector` error

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- tests/browsing_context/test_locate_nodes.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/locate_nodes/invalid.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/locate_nodes/locator.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/locate_nodes/invalid.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/locate_nodes/locator.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/locate_nodes/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/locate_nodes/locator.py.ini
Implement XPath locator in [`browsingContext.locateNodes`](https://w3c.github.io/webdriver-bidi/#commands-browsingcontextlocatenodes) via [`XPathEvaluator`](https://developer.mozilla.org/en-US/docs/Web/API/XPathEvaluator) WebApi.
> feat: support xpath locators

- .github/workflows/wpt-quick.yml
We should have ran this check to merge a PR, so running it here does not give any value as we already run `WPT detailed` action. This should make allocating runners quicker for our other PRs.
> ci: don't run WPT quick on main

- package.json
- src/bidiServer/BrowserInstance.ts
- src/bidiServer/WebSocketServer.ts
- src/bidiServer/index.ts
- tests/conftest.py
- tools/run-wpt.mjs
This is a step towards e2e via chromedriver testing.
Head{less|ful} mode is now controlled via browser bin arguments passed in session capabilities.
> test: control head mode via capabilities

- src/bidiServer/WebSocketServer.ts
- tests/conftest.py
This is a step towards e2e via chromedriver testing.
* Add `session.end` command in nodejs runner.
* End session after each e2e test.
> test: add `session.end` support in nodejs runner

- .github/workflows/e2e.yml
- README.md
- package.json
- tests/conftest.py
- tools/bidi-server.mjs
- tools/run-e2e.mjs
- tools/run-wpt.mjs
Add ability to e2e tests run both with an **old** and a **new** headless. Do that on Ubuntu, and run only headful on macos. The CI combinations are:
* ubuntu, headful **4m 37s**
* ubuntu, new headless **3m 0s**
* ubuntu, old-headless **1m 56s**
* macos, headful **8m 49s**
Closes #1862
> test: add dedicated e2e runner for new and old headless modes

- README.md
- src/bidiServer/BrowserInstance.ts
- src/bidiServer/WebSocketServer.ts
- src/bidiServer/index.ts
- tools/bidi-server.mjs
- tools/path-getter/path-getter.mjs
- tools/run-bidi-server.mjs
- tools/run-e2e.mjs
Required for running e2e via chromedriver, as chromedriver uses browser binary form capabilities.
> chore: provide browser bin via capabilities or env var

- tools/wpt-report-builder/template.html
> docs: break long words

- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/invalid.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/invalid.py.ini
Will skip the test for `mapper` as they spawn a browser and that makes it slow
> test: enable skipped tests

- README.md
- package.json
- src/bidiServer/WebSocketServer.ts
- tests/conftest.py
- tests/test_helpers.py
- tools/bidi-server.mjs
- tools/run-e2e.mjs
Out of scope: running e2e chromedriver in CI, as some tests are failing
> test: support e2e running via `chromedriver`

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- src/bidiMapper/domains/context/BrowsingContextProcessor.ts
- src/bidiMapper/domains/script/SharedId.spec.ts
- src/bidiMapper/domains/script/SharedId.ts
- src/bidiMapper/domains/script/WindowRealm.ts
- src/bidiServer/WebSocketServer.ts
- tests/script/test_shared_id.py
- tests/test_helpers.py
As long as https://crrev.com/c/5094519 was landed in 122 which is stable now, we can remove the legacy shared id format support.
> chore: remove support of legacy shared id format

- tools/bidi-server.mjs
The logs were missing because of the wrong options were sent to `child_process.spawn`
> fix: get logs back

- src/bidiMapper/domains/script/WindowRealm.ts
bidiValue can be undefined as specified by it's type.
Fixed: https://github.com/puppeteer/puppeteer/issues/12111
> fix: check bidiValue before using

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- tests/browsing_context/test_locate_nodes.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/locate_nodes/invalid.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/locate_nodes/locator.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/locate_nodes/invalid.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/locate_nodes/locator.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/locate_nodes/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/locate_nodes/locator.py.ini
Start implement innerText locator in [`browsingContext.locateNodes`](https://w3c.github.io/webdriver-bidi/#commands-browsingcontextlocatenodes) using WebAPI.
Out of scope:
* `maxNodeCount`
* `maxDepth`
> feat: support `innerText` locators

- tools/bidi-server.mjs
Output only when `VERBOSE` is set explicitly or on CI
> chore: less local output

- .github/workflows/e2e.yml
- Pipfile
- Pipfile.lock
- tools/bidi-server.mjs
- tools/run-e2e.mjs
Use `pytest-shard` to shard e2e tests, decreasing e2e run time for headful Mac from 15 to 5 minutes.
> ci: shard e2e tests

- pytest.ini
>  timeout_func_only (bool):
>                        When set to True, defers the timeout evaluation to only the test function body, ignoring the time it takes when evaluating any fixtures used in the test.
For fixture evaluation, we should rely on the inner timeouts for fixture setup and teardown and most of them are already configured properly via the timeout for the execute_command and wait_for_command.
> test: apply timeouts to test functions only

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- src/bidiMapper/domains/context/BrowsingContextStorage.ts
- src/bidiMapper/domains/input/ActionDispatcher.ts
- src/bidiMapper/domains/input/InputProcessor.ts
- src/bidiMapper/domains/network/NetworkProcessor.ts
- src/bidiMapper/domains/script/Realm.ts
- src/bidiMapper/domains/script/ScriptProcessor.ts
- src/bidiMapper/domains/script/WindowRealm.ts
- tests/script/test_remove_preload_script.py
Moves the defaults to the `Realm` class rather then the `ScriptProcessor`, so we can use them from anywhere.
Also some small changes that I will mark as comments.
> refactor: move defaults to Realm

- src/bidiMapper/domains/network/NetworkRequest.ts
This should be no OK as the class itself does not relay on this property, only the `NetworkProcessor` (aka `commands`) do.
> fix: continue blocking if CDP command fails

- src/bidiMapper/domains/network/NetworkRequest.ts
We already check the encoding in the `NetworkProcessor`, not sure if we should move the logic to the `NetworkRequest`.
> fix: don't encode body 2 times

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/session/SessionProcessor.ts
Note that e2e or chromedriver tests would not work here since they override session.new call. This PR does not implement capability matching since this is not required by Puppeteer yet.
> feat: implement readonly capabilities

- src/bidiMapper/domains/network/NetworkRequest.ts
- tests/network/test_network.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_started/response_started.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
> fix: add fragment to url

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/modules/cdp/CdpTargetManager.ts
- src/bidiMapper/modules/context/BrowsingContextProcessor.ts
Extracts the `CdpTarget` creation and setup from `BrowsingContextProcessor`. 
Setting them up in the `BiDiServer`, so that the `CommandProcessor` only deals with commands.
> refactor: extract CdpTargetManager

- src/bidiMapper/modules/network/NetworkModuleMocks.spec.ts
- src/bidiMapper/modules/network/NetworkRequest.ts
- src/bidiMapper/modules/network/NetworkStorage.spec.ts
Currently we never await the `responseReceivedExtraInfo` as we destroy the BiDi `NetworkRequest` as soon as we see the redirect happening. This means that the conditions for emitting are never met.
We should eventually change this but having the `responseCompleted` event with missing headers is better then not having it at all.
Such change would mean that can never have order that matches the expectations
`beforeRequestSent` -> `responseCompleted` -> `beforeRequestSent`
As the `responseReceivedExtraInfo` comes after the second CDP `requestWillBeSent`
https://github.com/GoogleChromeLabs/chromium-bidi/issues/2035
> fix: emit `network.responseCompleted` for redirects

- tools/wpt-report-builder/template.html
After pressing shows only failing tests.
And deep as well
> docs: quick failures button

- src/bidiMapper/modules/context/BrowsingContextProcessor.ts
The test covering this is `[browser.spec] Browser specs Browser.process should keep connected after the last page is closed`
> fix: apply existing context check to default user context too

- src/bidiTab/mapperTabPage.ts
This allows you to quickly search for the same `ids`.
> chore: fix formatting

- .github/workflows/labeler.yml
- .github/workflows/puppeteer.yml
- .github/workflows/wpt.yml
Adding the label to the dependabot PR should work.
Updating the expectation and running the CI after committing is best guess effort.
> ci: add label for WPT expectations update

- src/bidiServer/MapperCdpConnection.ts
- src/bidiTab/bidiTab.ts
- src/bidiTab/mapperTabPage.ts
1. Add `onbeforeunload` handler to the mapper tab.
2. Click on the mapper tab, so that the `onbeforeunload` will be triggered.
Required follow up:
> chore: user prompt before the mapper tab closed

- .github/dependabot.yml
- .github/workflows/labeler.yml
Currently the label is added too late so that the GitHub Action event does not contain it.
This should add it as before that so the trigger will already have it in the JSON event struct.
> chore: add label at PR create time

- src/bidiMapper/modules/input/keyUtils.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/key_events.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/key_events.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/key_events.py.ini
Add missing parts from the WebDriver specification
> fix: added missing input transformations

- src/bidiMapper/modules/input/keyUtils.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/key_events.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/key_events.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/key_events.py.ini
The "Return" key code is not specified in https://www.w3.org/TR/uievents-key/ nor implemented in [Chrome](https://source.chromium.org/chromium/chromium/src/+/main:ui/events/keycodes/dom/dom_key_data.inc). Fall back to `Enter`.
> chore: fall back in case of not supported key input

- .github/workflows/wpt.yml
If WPT detailed task finished successfull, the expectations should not be updated. Tested in https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/9059738115
> chore: WPT detailed job commits only if the tests failed

- .github/workflows/wpt-quick.yml
- .github/workflows/wpt.yml
- tools/run-wpt.mjs
* `wpt-quick` now updates the expectations by label or a flag if run manually.
* `wpt` still updates expectations if run manually.
* `tools/run-wpt.mjs` supports the wpt report path as a CLI argument. This is required for running update expectations job in a `find` loop.
The update expectations job now is done in 8 minutes instead of 22.
Job without updating expectations: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/9080607825
Job with updating expectations: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/9080522732
> chore: update WPT expectations quickly

- src/bidiMapper/modules/input/ActionDispatcher.ts
- src/utils/GraphemeTools.spec.ts
- src/utils/GraphemeTools.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/key.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/pointer_pen.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/key.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/pointer_pen.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/key.py.ini
Allow graphemes in key input according to step 6 of https://w3c.github.io/webdriver/#dfn-process-a-key-action.
Use [`Intl.Segmenter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) to detect grapheme borders.
Follow up: update WPT tests.
> feat: support for graphemes in key input

- src/bidiServer/MapperCdpConnection.ts
As long as bidi tab is transparent for clients, having it active is unexpected. Required for input tests.
> build: in JS runner, activate the blank tab, not the mapper tab

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
Ref: https://github.com/web-platform-tests/wpt/pull/46441, this need to be merged else test will fail.
Also make the test run in CI.
> fix: report correct value for DefaultValue in UserPrompt

- src/bidiMapper/modules/context/BrowsingContextProcessor.ts
- tests/browsing_context/test_create.py
- tests/conftest.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/create/background.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/create/background.py.ini
1. Respect parameter `background` in `browsingContext.create` command.
2. Activate the newly created browsing context, if created not in background.
> feat: support creating tab in background

- tests/network/test_network.py
https://github.com/GoogleChromeLabs/chromium-bidi/issues/2263
> test: disable flaky `test_network_before_request_sent_event_with_cookies_emitted`

- src/bidiMapper/modules/cdp/CdpTargetManager.ts
- src/bidiMapper/modules/context/BrowsingContextImpl.ts
When target is attached, save it's url. This should address [puppeteer test](https://github.com/puppeteer/puppeteer/blob/88df4075171cdd87ad60241dd77028c96b1a7d9b/test/src/launcher.spec.ts#L890).
> fix: when reconnecting, save context's url

- .github/workflows/puppeteer.yml
Reverts GoogleChromeLabs/chromium-bidi#2272
Working dir is not actually supported :/
> Revert "ci: fix caching for Puppeteer job"

- src/bidiMapper/modules/cdp/CdpTarget.ts
Addressing https://github.com/GoogleChromeLabs/chromium-bidi/issues/2282
> feat: restore frame tree when reconnecting to browser

- src/bidiMapper/modules/input/ActionDispatcher.ts
- src/bidiMapper/modules/input/InputSource.ts
In order to provide proper DOM `touchend` event params, need to keep track of pressure and touch size of touch input events.
Tested via Puppeteer. To test e2e, extending http server with static page is required, so out of scope.
> fix: keep radius and force of input

- src/bidiMapper/modules/network/NetworkRequest.ts
- tests/network/test_continue_request.py
- tests/network/test_continue_response.py
- tests/network/test_continue_with_auth.py
- tests/network/test_provide_response.py
> fix: remove requests after they have been completed

- .github/workflows/unit.yml
- README.md
- codecov.yml
- package-lock.json
- package.json
The coverage reports are not used and not correct as we only run it for unit tests.
It's not a small effort if we want to do it for WPT and E2E test so removing seems the option for now.
> chore: remove `codecov`

- src/bidiMapper/modules/log/LogManager.ts
Ref: #2317
I think this should fix it.
> fix: catch error when logging args

- .eslintrc.js
- src/bidiMapper/modules/log/LogManager.ts
Closes #2317.
Closes #2320.
I missed the this in my last PR, but I added a EsLint rule to catch similar issue in the feature.
It's not 100% robust but it does the job if there is `then` in the called function.
> fix: handle `registerPromiseEvent` with errors

- tools/run-wpt.mjs
If we get `result === 0` that mean the command finished without needing to update.
This saves some time locally.
If we didn't run test, but we ran the command (`RUN_TEST=false`) we try to update the expectations (needed for CI).
> chore: run Update Expectations only when the run changes them

- src/bidiMapper/modules/cdp/CdpTarget.ts
- src/bidiMapper/modules/cdp/CdpTargetManager.ts
- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- src/protocol-parser/generated/webdriver-bidi.ts
- src/protocol/generated/webdriver-bidi.ts
- tests/browsing_context/__snapshots__/test_close.ambr
- tests/browsing_context/test_close.py
- tests/browsing_context/test_create.py
- tests/browsing_context/test_get_tree.py
- tests/browsing_context/test_navigate.py
- tests/browsing_context/test_nested_browsing_context.py
- tests/session/test_subscription.py
We should wait until https://github.com/w3c/webdriver-bidi/pull/730 is resolved.
Closes #2315
Closes #2296
> feat: add support for `originalOpener` in BrowsingContext.Info

- src/bidiMapper/modules/cdp/CdpTargetManager.ts
We should be able to track if what frame opened the new `BrowsingContext`.
> fix: openerFrameId whenever possible

- src/bidiMapper/modules/network/NetworkProcessor.ts
- src/bidiMapper/modules/network/NetworkRequest.ts
The main justification is we need to store the data from the interception as BiDi sends back the data for both request and response with the events. 
This PR does not introduce functional changes, Or are marked by comment.
> refactor: move the methods to request

- tests/browsing_context/test_close.py
- tests/browsing_context/test_create.py
- tests/browsing_context/test_fragment_navigated.py
- tests/browsing_context/test_get_tree.py
- tests/browsing_context/test_navigate.py
- tests/browsing_context/test_nested_browsing_context.py
- tests/browsing_context/test_reload.py
- tests/conftest.py
- tests/network/test_continue_request.py
- tests/network/test_continue_response.py
- tests/network/test_continue_with_auth.py
- tests/network/test_fail_request.py
- tests/network/test_network.py
- tests/network/test_provide_response.py
- tests/network/test_remove_intercept.py
- tests/permissions/test_set_permission.py
- tests/script/test_add_preload_script.py
- tests/tools/local_http_server.py
- tests/tools/test_local_http_server.py
- tools/run_local_http_server.py
* Hide `httpserver` in the `LocalHttpServer`.
* Unify `url` fixtures names.
* Add `url_bad_ssl` to `LocalHttpServer`.
> test: refactor local http server

- tests/browsing_context/test_create.py
- tests/browsing_context/test_get_tree.py
- tests/browsing_context/test_navigate.py
- tests/browsing_context/test_nested_browsing_context.py
- tests/browsing_context/test_traverse_history.py
- tests/conftest.py
- tests/log/test_log_entry_added.py
- tests/network/test_remove_intercept.py
- tests/script/test_realm.py
- tests/session/test_subscription.py
- tests/tools/local_http_server.py
- tests/tools/test_local_http_server.py
- tools/run_local_http_server.py
* Add possibility to provide a URL with a custom content.
* Remove `data:text/html` fixture
* Address concurrency issue in local http server by adding several instances.
> test: custom content in local http server

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/modules/cdp/CdpTarget.ts
- src/bidiMapper/modules/cdp/CdpTargetManager.ts
- tests/service_worker/test_navigate.py
- tests/tools/local_http_server.py
Addressing https://github.com/GoogleChromeLabs/chromium-bidi/issues/2357
* Fix the root cause.
* Add e2e.
Prerequisite: https://github.com/GoogleChromeLabs/chromium-bidi/pull/2368
> fix: the capability to ignore cert errors should be browser-wide 

- src/bidiMapper/modules/cdp/CdpTarget.ts
- src/bidiMapper/modules/context/BrowsingContextImpl.ts
Addressing #2362. 
NodeJS runner nor chromedriver don't support re-connecting, so tested via puppeteer.
> fix: restore OOPiF state

- src/bidiServer/WebSocketServer.ts
- tests/browsing_context/test_user_prompt.py
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/user_prompt_opened/handler.py.ini
Respect string value in `unhandledPromptBehavior`. Required to test backward compatibility with WebDriver Classic.
> chore: support string `unhandledPromptBehavior` in NodeJS runner

- src/bidiMapper/modules/network/NetworkRequest.ts
This PR adds vendor-prefixed security details to support Puppeteer use case until an alternative is part of the standard. The testing is planned via Puppeteer test suite.
> feat: include vendor-prefixed security details

- src/bidiMapper/modules/network/NetworkRequest.ts
- tests/network/test_add_intercept.py
- tests/network/test_continue_request.py
- tests/network/test_continue_response.py
- tests/network/test_continue_with_auth.py
- tests/network/test_fail_request.py
- tests/network/test_network.py
- tests/network/test_provide_response.py
- tests/network/test_remove_intercept.py
- 'goog:postData'
- 'goog:hasPostData'
- 'goog:resourceType'
The testing is planned via Puppeteer.
> feat: include vendor-prefixed additional request data

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- tests/browsing_context/test_user_prompt.py
https://w3c.github.io/webdriver/#dfn-get-the-prompt-handler 
Step 3.
> fix: support `default` for BeforeUnload prompt

- src/bidiMapper/modules/network/NetworkProcessor.ts
- src/bidiMapper/modules/network/NetworkRequest.ts
- src/bidiMapper/modules/network/NetworkUtils.ts
I still need to see why the data is not surfacing on the request correctly, but the feature should now work.
The WPT test will pass once we fix the `request->headers`.
> fix: support for cookies in ContinueRequest

- .pre-commit-config.yaml
Required to ease iterative development process. Partly reverts https://github.com/GoogleChromeLabs/chromium-bidi/commit/0cde2e4def56db9cddc17feaa36c199731b14c2e
> chore: run pre-commit hooks before push, not before commit

- .github/workflows/puppeteer.yml
- src/bidiMapper/modules/cdp/CdpTargetManager.ts
- tests/service_worker/test_navigate.py
- tests/session/test_cdp.py
- tests/test_helpers.py
- tools/bidi-server.mjs
- tools/run-e2e.mjs
This can be a workaround for https://github.com/GoogleChromeLabs/chromium-bidi/issues/2420
> fix: only auto-attach to a target once

- .github/workflows/wpt-quick.yml
The WPT reports artifacts already include the `out`  folder to the path as `out/out/<report>`.
> ci: fix artifacts path

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/modules/session/SessionProcessor.ts
- src/bidiServer/BrowserInstance.ts
- src/bidiServer/MapperCdpConnection.ts
- src/bidiServer/WebSocketServer.ts
- src/bidiTab/bidiTab.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/interop/beforeunload_prompt.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/interop/beforeunload_prompt.py.ini
This PR moves Mapper options to be processed inside session.new so that there is a single place on how these options have to be provided and that allows using the mapper in the same way as other protocol implementations.
ChromeDriver issue: https://crbug.com/356371297
> feat: implement capabilities handling in session.new

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/modules/session/SessionProcessor.ts
This PR improves capabilities matching to support capabilities that could be cross-browser for Puppeteer. It is not fully aligned with the spec though as we expect most of things to be handled by ChromeDriver.
> fix: improve capabilities matching

- package.json
- release-please-config.json
This PR switches versioning on the main branch to use alpha suffix indicating compatibility with canary browser builds.
chromium-bidi was already using a prerelease flag for release-please and so the appropriate versioning strategy should be in place.
I have already created two release branches `releases/m127` and `releases/m128` off the main branch. Currently, the main branch is using M129. As soon as we switch to M130, we need a new branch.
Related semver spec: https://semver.org/#spec-item-9
Related release-please versioning strategy: https://github.com/googleapis/release-please/blob/main/src/versioning-strategies/prerelease.ts#L175
> build: switch to pre-release versioning

- package.json
- release-please-config.json
Reverts GoogleChromeLabs/chromium-bidi#2512
it didn't work with release-please. See https://github.com/GoogleChromeLabs/chromium-bidi/pull/2514
> Revert "build: switch to pre-release versioning"

- src/bidiMapper/modules/input/ActionDispatcher.ts
Even if the pen is not touching the surface, the move events should be dispatched.
> fix: allow pen to hover over

- README.md
For example, the following diagram shows how release-branches are created:
```mermaid
gitGraph
commit id: "feat: featA"
commit id: "release: v0.5.0"
branch release/m129
checkout main
commit id: "feat: roll Chrome to M130 from 129"
commit id: "release: v0.6.0"
commit id: "fix: for m129"
checkout release/m129
cherry-pick id: "fix: for m129"
commit id: "release: v0.5.1 "
```
> docs: document how release branches should work

- package-lock.json
- package.json
- rollup.config.mjs
- src/bidiMapper/modules/network/NetworkProcessor.ts
- src/bidiServer/index.ts
- src/utils/UrlPattern-browser.ts
When we run Mapper Tab we can be sure that all Chrome APIs are there and we can use, so we can omit this.
The delta is around ~16K.
Note: we can't drop all together it as that will break Puppeteer.
> chore: reduce Mapper Tab size by not including Url Pattern polyfill

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- tests/browsing_context/test_locate_nodes.py
Addressing https://github.com/GoogleChromeLabs/chromium-bidi/issues/2539
According to the spec, the default `startNodes` of the `browsingContext.locateNodes` is `document`, not `document.body`.
> fix: css and xPath selector start node is document

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- tests/browsing_context/test_navigate.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigate/error.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigate/error.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigate/error.py.ini
Addressing https://github.com/GoogleChromeLabs/chromium-bidi/issues/2568
> fix: fail previous navigation on the next one

- src/bidiMapper/modules/log/LogManager.ts
- src/bidiMapper/modules/script/Realm.ts
- tests/script/test_add_preload_script.py
This change saves some CDP round trips on console log events, which improves Mapper performance in case of tons of console log events are written. This seems to be a bottleneck for testdriverJS BiDi.
> chore: heuristic in console log serialization

- tools/update_chrome_revision.mjs
Currently, the feat commits only generate a patch.
> build: mark roll of a new major browser version as breaking

- .github/workflows/update-browser-version.yml
With the move to pushing to fork we need to reaccept the runs, which means every other the PR resets.
We also don't merge it every time.
> ci: run browser update every 12 hours

- src/bidiMapper/modules/cdp/CdpTarget.ts
- src/bidiMapper/modules/context/BrowsingContextProcessor.ts
- src/cdp/CdpConnection.ts
If there are some pending commands at the moment a CDP session is ended, those commands will never end. This PR makes sure we don't have those hanging commands.
Motivation: this becomes critical for switching to tab targets, as the tab target can be closed when the page is closed.
> chore: reject pending cdp commands when the cdp session is destroyed

- src/bidiMapper/modules/cdp/CdpTarget.ts
- src/bidiMapper/modules/network/NetworkProcessor.ts
- src/bidiMapper/modules/network/NetworkRequest.ts
- src/bidiMapper/modules/network/NetworkStorage.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/remove_intercept/remove_intercept.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/remove_intercept/remove_intercept.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/remove_intercept/remove_intercept.py.ini
Closes https://github.com/GoogleChromeLabs/chromium-bidi/issues/2147
> fix: don't unblock on interception removed

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- tests/browsing_context/test_print.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/print/context.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/queue.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/print/context.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/queue.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/print/context.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/queue.py.ini
Restrict pdf printing only to top level browsing contexts. Required, as CDP method `Page.printToPDF` works only on the top-level targets, and don't allow printing not same-proccess nor OOPiF.
> chore: don't allow PDF printing of iframes

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- tests/browsing_context/test_navigate.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigate/error.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigate/error.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigate/error.py.ini
Related issue: https://github.com/GoogleChromeLabs/chromium-bidi/issues/2709
Should be reverted if https://github.com/w3c/webdriver-bidi/issues/799 is fixed
> feat: align abort navigation with the spec

- src/bidiMapper/modules/cdp/CdpTarget.ts
Reverts GoogleChromeLabs/chromium-bidi#2732
it looks like it might be actually making situation worse since some targets appear to be paused without emitting attached events.
> revert: "chore: exclude targets that we do not interact with"

- tools/install-browser.mjs
- tools/path-getter/path-getter.mjs
- tools/run-e2e.mjs
Download headless shell when `headless=old` is used. Required for https://github.com/GoogleChromeLabs/chromium-bidi/pull/2719.
> ci: download headless shell when needed

- README.md
Now that ChromeDriver issues are migrated we should use the new link, as there is a check that warns not to use old ones.
> docs: update roll bug link

- src/bidiMapper/modules/bluetooth/BluetoothProcessor.ts
- tests/bluetooth/test_emulation.py
Align with the spec (step 6) of [`bluetooth.simulateAdapter`](https://webbluetoothcg.github.io/web-bluetooth/#bluetooth-simulateAdapter-command).
> fix: allow setting `bluetooth.simulateAdapter` multiple times

- src/bidiServer/BrowserInstance.ts
To fix https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/11796904094/job/32864869059?pr=2758 short-term. Long-term the e2e server needs to support custom hosts.
> test: disable HttpsFirstBalancedModeAutoEnable

- src/bidiMapper/modules/browser/BrowserProcessor.ts
- tests/browser/test_get_client_windows.py
- tests/conftest.py
Addressing issue pointed in https://github.com/GoogleChromeLabs/chromium-bidi/pull/2780#discussion_r1844312850
> fix: `browser.getClientWindows` returns a unique per window value

- README.md
Extend readme with process of extending Mapper with a new WebDriver BiDi command.
> docs: adding new command

- tests/browsing_context/test_create.py
- tests/browsing_context/test_dom_content_loaded.py
- tests/browsing_context/test_load.py
- tests/browsing_context/test_navigate.py
- tests/conftest.py
- tests/test_helpers.py
* Added value stabilization. Required for improvement of e2e coverage of navigation.
* Improve assertion messages for `read_sorted_messages`.
> test: stabilize values

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- src/bidiMapper/modules/context/NavigationTracker.ts
- src/utils/time.spec.ts
- src/utils/time.ts
Move navigation logic to NavigationTracker. First step for addressing https://github.com/GoogleChromeLabs/chromium-bidi/issues/2856. No logical changes are expected, simply moved the logic to a dedicated class.
> chore: (no-op) move navigation logic to NavigationTracker

- .github/workflows/puppeteer.yml
Brings total duration from 7m to 3m.
> test: split puppeteer tests into 4 shards

- .github/workflows/labeler.yml
- .github/workflows/puppeteer.yml
This PR adds an automation label `puppeteer-required` that would make Puppeteer test failures to block the release PRs requiring suppressing the test failure in Puppeteer's main branch if a change with regressions needs to be released.
> test: make puppeteer tests required on releases

- src/bidiMapper/modules/context/NavigationTracker.spec.ts
- tests/browsing_context/__snapshots__/test_navigate_events.ambr
- tests/browsing_context/test_navigate_events.py
- tests/conftest.py
Address https://github.com/GoogleChromeLabs/chromium-bidi/issues/2900
+ remove extra `await` and `async` from unit tests
> test: make `test_scriptNavigate_checkEvents` stable

- src/bidiMapper/modules/context/NavigationTracker.spec.ts
- src/bidiMapper/modules/context/NavigationTracker.ts
- tests/browsing_context/__snapshots__/test_navigate_events.ambr
- tests/browsing_context/test_navigate_events.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigation_failed/navigation_failed.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigation_failed/navigation_failed.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigation_failed/navigation_failed.py.ini
WPT failures are due to the fact Chrome emits `frameNavigated` after receiving headers.
https://github.com/web-platform-tests/wpt/pull/49718
> feat: abort navigation only after frame navigated

- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/key_events.py.ini
> test: mark flaky from `test_non_printable_key_sends_events`

- src/bidiMapper/modules/input/ActionDispatcher.ts
- src/bidiMapper/modules/input/InputProcessor.ts
- tests/input/test_input.py
Get browsing context each time from the storage to guarantee it is not disposed.
+ e2e test
> feat: throw a proper error if the browsing context was destroyed during action dispatching

- .github/workflows/labeler.yml
Some race condition in GitHub Actions seems to prevent the Puppeteer workflow from detecting the Puppeteer label after the Puppeteer-Required label was added. Let us try to change the order
> ci: try adding the puppeteer label last

- .github/workflows/e2e.yml
- .github/workflows/selenium.yml
- .github/workflows/webdriverio.yml
- .github/workflows/wpt.yml
- src/bidiMapper/modules/context/NavigationTracker.spec.ts
- src/bidiMapper/modules/network/NetworkRequest.ts
- src/bidiMapper/modules/network/NetworkUtils.ts
- tests/network/test_network.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_started/response_started.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
+ make e2e test offline.
Tested manually + WPT.
> feat: provide proper network timings

- src/bidiMapper/modules/script/Realm.ts
- tests/script/test_serialization.py
Deeply nested nodes do not include values in CDP, thus, Object.hasOwn throws an error because only objects are allowed as the first arg.
Drive-by: improve types
Caused by: https://github.com/GoogleChromeLabs/chromium-bidi/pull/2622
Addresses: https://github.com/puppeteer/puppeteer/issues/13433
WPT test: https://github.com/web-platform-tests/wpt/pull/49821/files
> fix: regression in serialization

- src/bidiMapper/modules/network/NetworkRequest.ts
- tests/network/test_network.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_started/response_started.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
Add heuristic to support some of `initiatorType` and `destination` in network requests.
> feat: heuristic for request's `initiatorType` and `destination`

- src/bidiMapper/modules/network/NetworkRequest.ts
- src/bidiMapper/modules/network/NetworkStorage.spec.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/continue_request/url.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/continue_request/url.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/continue_request/url.py.ini
It seems that CDP does not report the correct URL on the response. Have to double check, but the other part of the WPT test pass so I am confident this is the case.
> fix(network): url for interception

- src/bidiMapper/modules/session/SubscriptionManager.spec.ts
- only check channels when the order of channels is relevant.
- use isSubscribeTo for the rest of tests
> test: rewrite unit tests for SubscriptionManager

- src/bidiMapper/modules/network/NetworkRequest.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/continue_request/headers.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/continue_request/headers.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/continue_request/headers.py.ini
We need to do proper deduplication for Binary Headers so this can land, feel free to take over.
> fix: multi headers reporting incorrectly

- src/bidiMapper/modules/context/BrowsingContextStorage.ts
This should address Puppeteer test failures: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/12827546451/job/35769733285?pr=2993
Tested manually. 1000 times run Puppeteer test "[locator.spec] Locator Locator.prototype.filter should resolve as soon as the predicate matches" with and without the change. Problem is gone.
> fix: wait for context should respect already existing contexts

- src/bidiMapper/CommandProcessor.ts
- src/bidiTab/Transport.ts
- src/utils/log.ts
Addressing https://github.com/GoogleChromeLabs/chromium-bidi/issues/2843.
Tested manually.
> chore: warn if legacy BiDi+ is used

- src/bidiMapper/BidiNoOpParser.ts
- src/bidiMapper/BidiParser.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/modules/session/EventManager.ts
- src/bidiMapper/modules/session/SessionProcessor.ts
- src/bidiMapper/modules/session/SubscriptionManager.spec.ts
- src/bidiMapper/modules/session/SubscriptionManager.ts
- src/bidiTab/BidiParser.ts
- src/protocol-parser/protocol-parser.ts
- tests/session/test_subscription.py
- tests/test_helpers.py
Issue https://github.com/GoogleChromeLabs/chromium-bidi/issues/2925
> feat: implement unsubscribe by id

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- tests/browsing_context/test_close.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/context_destroyed/context_destroyed.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/context_destroyed/context_destroyed.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/context_destroyed/context_destroyed.py.ini
According to the spec, max depth in browsingContext.contextDestroyed event should always be null.
> fix: handle max depth property

- eslint.config.mjs
- src/bidiMapper/modules/network/NetworkRequest.ts
- src/bidiMapper/modules/network/NetworkUtils.ts
- tests/network/test_provide_response.py
> fix: support correct to base64 for non-latin

- src/protocol-parser/protocol-parser.ts
in the spec, we prefer matching the subscription ID over the attributes. Our parser is removing the extra attributes so if the order is wrong, we will strip subscription ids. This PR enforces the specified order.
> fix: fix unsubscribe by id parser

- src/protocol/chromium-bidi.ts
- tests/bluetooth/test_handle_prompt.py
The specific event name was missing in the `EVENT_NAMES`, which made it impossible to subscribe to a specific event.
> fix: allow `bluetooth.requestDevicePromptUpdated` subscription

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/modules/browser/BrowserProcessor.ts
- src/bidiMapper/modules/browser/UserContextStorage.ts
- src/bidiMapper/modules/network/NetworkStorage.spec.ts
- src/bidiMapper/modules/session/EventManager.ts
- src/bidiMapper/modules/session/SessionProcessor.ts
- src/bidiMapper/modules/session/SubscriptionManager.spec.ts
- src/bidiMapper/modules/session/SubscriptionManager.ts
- tests/session/test_subscription.py
- Introduces UserContextStorage to abstract and re-use operations on user contexts. For now, only the get operation is moved. 
Issue https://github.com/GoogleChromeLabs/chromium-bidi/issues/2983
> feat: implement user context subscriptions

- src/bidiMapper/modules/input/InputProcessor.ts
- src/bidiMapper/modules/input/InputSource.ts
- tests/input/__snapshots__/test_input.ambr
- tests/input/test_input.py
Attempt to address https://github.com/GoogleChromeLabs/chromium-bidi/issues/3043.
Group clicks only in a single `input.performActions`.
> fix: group clicks in action

- .github/workflows/wpt.yml
If I understand  correctly what is happening is - GitHub action implicitly add `success()` if non of the special cases are in the if.
> ci: explicitly mark it update expectations

- src/bidiMapper/modules/browser/UserContextStorage.ts
- src/bidiMapper/modules/cdp/CdpTarget.ts
- src/bidiMapper/modules/cdp/CdpTargetManager.ts
- src/bidiMapper/modules/script/PreloadScript.ts
- src/bidiMapper/modules/script/PreloadScriptStorage.spec.ts
- src/bidiMapper/modules/script/PreloadScriptStorage.ts
- src/bidiMapper/modules/script/ScriptProcessor.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/script/add_preload_script/user_contexts.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/add_preload_script/user_contexts.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/add_preload_script/user_contexts.py.ini
Need to add Unit tests mayble.
> feat: support UserContext in PreloadScripts

- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/add_intercept/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/call_function/invalid.py.ini
We are seeing a lot of flake in Pure Mapper, and we should ignore them so that to make sure that every run on main succeeds.
> chore: mark as timeout as well

- tests/browsing_context/__snapshots__/test_navigate_events.ambr
- tests/browsing_context/test_navigate_events.py
- tests/conftest.py
Extend test coverage for navigation. Extracted from https://github.com/GoogleChromeLabs/chromium-bidi/pull/3104.
> test: extend navigation tests

- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/key.py.ini
This is flaky on `headful` as well.
> test: mark as flaky

- package-lock.json
- package.json
- rollup.config.mjs
- tsconfig.base.json
Required as a work-around for `keep-sorted` artifacts. [Example](https://crrev.com/c/6105891/1).
Keep license headers.
> build: remove comments from esm script

- tools/run-e2e.mjs
This can happen if your pipenv is missing dependencies, for example.
> chore: print an error for e2e launch failures

- src/bidiTab/Transport.ts
Currently, the CDP connection is exposed on the global object. With this change, the CDP connection's send method would be only internally available.
> fix: hide cdp.send after the mapper receives it

- src/bidiServer/BrowserInstance.ts
- tests/webExtension/test_web_extension.py
Somehow if the test fails too fast the websocket connection to WebDriver server fails.
> test: use sleep to mitigate a race condition

- src/bidiServer/BrowserInstance.ts
We should not unconditionally set `--remote-debugging-port`
> test: fix non-chromedriver WPT

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- src/bidiMapper/modules/context/NavigationTracker.spec.ts
- src/bidiMapper/modules/context/NavigationTracker.ts
- tests/browsing_context/__snapshots__/test_navigate_events.ambr
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigate/navigate_beforeunload.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/integration/navigation.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/integration/navigation.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/integration/navigation.py.ini
`Page.frameStartedNavigating` is emitted for new navigations, so we can rely on it.
Disabling Network domain is out of scope to reduce risks of the PR.
Cleaning up TargetEvents and CdpTarget is out of scope.
Addressing http://b/401500518
> chore: rely on Page.frameStartedNavigating CDP event

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/OutgoingMessage.ts
- src/bidiMapper/modules/network/NetworkStorage.spec.ts
- src/bidiMapper/modules/session/EventManager.ts
- src/bidiMapper/modules/session/SessionProcessor.ts
- src/bidiMapper/modules/session/SubscriptionManager.spec.ts
- src/bidiMapper/modules/session/SubscriptionManager.ts
- src/bidiTab/Transport.ts
- src/protocol/chromium-bidi.ts
- tests/session/test_protocol_basics.py
- tests/session/test_subscription.py
- tests/test_helpers.py
Addressing `channel` part of #2844.
> chore: remove support of legacy `channel` field

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/modules/cdp/CdpTarget.ts
- src/bidiMapper/modules/session/SubscriptionManager.ts
- src/bidiMapper/modules/session/events.spec.ts
- src/bidiMapper/modules/session/events.ts
- src/protocol/cdp.ts
- src/protocol/chromium-bidi.ts
- tests/session/test_cdp.py
- tests/session/test_subscription.py
Addressing https://github.com/GoogleChromeLabs/chromium-bidi/issues/2844
> chore: remove support of legacy `cdp.` commands

- .github/workflows/e2e.yml
- src/bidiServer/WebSocketServer.ts
- tests/browser/test_create_user_context.py
- tests/browsing_context/test_close.py
- tests/browsing_context/test_get_tree.py
- tests/browsing_context/test_navigate_events.py
- tests/browsing_context/test_nested_browsing_context.py
- tests/conftest.py
- tests/input/file_dialog/test_file_dialog_opened.py
- tests/input/test_input.py
- tests/permissions/test_set_permission.py
- tests/script/test_add_preload_script.py
- tests/script/test_get_realms.py
- tests/script/test_serialization.py
- tests/session/test_protocol_basics.py
- tests/session/test_subscription.py
Add e2e test runner with ChromeDriver. Some of the failing tests are disabled for now and should be addressed as a part of #3294. Nevertheless, having them run would decrease risk of regressions.
> ci: run e2e with chromedriver

- tests/browsing_context/__snapshots__/test_navigate_events.ambr
- tests/browsing_context/test_navigate_events.py
As long as the `browsingContext.navigationStarted` is now rely on the proper CDP event, there is no need in adding network event in the assertion. This should increase tests stability.
> test: remove `network.beforeRequestSent` from snapshot tests

- .github/dependabot.yml
When WPT module is updated, add `update-expectations` label to the PR so that the update WPT expectations PR is created.
> ci: update expectations for WPT bump

- .github/workflows/wpt.yml
- tests/network/test_network.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/emulation/set_geolocation_override/contexts.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/emulation/set_geolocation_override/coordinates.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/emulation/set_geolocation_override/invalid.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/emulation/set_geolocation_override/user_contexts.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/emulation/set_geolocation_override/contexts.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/emulation/set_geolocation_override/coordinates.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/emulation/set_geolocation_override/invalid.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/emulation/set_geolocation_override/user_contexts.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/emulation/set_geolocation_override/contexts.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/emulation/set_geolocation_override/coordinates.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/emulation/set_geolocation_override/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/emulation/set_geolocation_override/user_contexts.py.ini
#3305 + some fixes
Bumps [wpt](https://github.com/web-platform-tests/wpt) from `e06138a` to `41e905e`.
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/web-platform-tests/wpt/commit/41e905e5f5dacf58b1233b04b5959652d9165fa5"><code>41e905e</code></a> corner-shape: remove curvature adjustment</li>
<li><a href="https://github.com/web-platform-tests/wpt/commit/b8db5ed3913f91dfa7e3c95467eaf532bc347884"><code>b8db5ed</code></a> [animation-trigger] Restrict ActionAnimation to PhaseAndTime changes</li>
<li><a href="https://github.com/web-platform-tests/wpt/commit/84814093a84aca33105b57257e0d240d5c9b1398"><code>8481409</code></a> [gap-decorations] Making <code>PaintGaps</code> conform to collapsing border model</li>
<li><a …
> chore(deps): Bump wpt from e06138a to 41e905e

- .github/workflows/wpt.yml
Artifacts were renamed: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/14449529084/job/40518988172
> ci: fix "Generate HTML test report"

- src/bidiMapper/modules/session/SessionProcessor.ts
- tests/browsing_context/test_user_prompt.py
- wpt-metadata/chromedriver/headful/webdriver/tests/interop/beforeunload_prompt.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/user_prompt_opened/beforeunload.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/interop/beforeunload_prompt.py.ini
Align with the spec. If capability is set via string, the "beforeUnload" behavior should be "accept" regardless of the capability value.
WPT PR: https://github.com/web-platform-tests/wpt/pull/51998
> The steps to fire **beforeunload**
...
6.2. Let userPromptHandler be the result of [WebDriver BiDi user prompt opened](https://w3c.github.io/webdriver-bidi/#webdriver-bidi-user-prompt-opened) with document's [relevant global object](https://html.spec.whatwg.org/#concept-relevant-global), "beforeunload", and "".
...
6.4. If userPromptHandler is "none", then ...
...
> WebDriver BiDi user prompt opened
...
> 3. Let handler configuration be [get the prompt handler](https://w3c.github.io/webdriver/#dfn-get-the-prompt-handler) with type.
...
> 10. Return handler.
> 4. If type is "beforeUnload", …
> fix: string `unhandledPromptBehavior` capability implies `beforeUnload: accept` behavior

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- tests/browsing_context/test_user_prompt.py
Addressing https://github.com/GoogleChromeLabs/chromium-bidi/issues/3143.
> fix: emit `browsingContext.userPrompt` only once

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- tests/browsing_context/test_user_prompt.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/user_prompt_closed/user_prompt_closed.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/user_prompt_closed/user_prompt_closed.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/user_prompt_closed/user_prompt_closed.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
Addressing #3324. Use `frameId` introduced in crrev.com/c/6487891.
WPT test fix: https://github.com/web-platform-tests/wpt/pull/52200
> feat: provide proper context id in `browsingContext.userPrompt`

- package.json
- src/index.ts
The main entry and the type commonjs would allow older runtimes to import the CJS version. For ESM imports, the exports field is used.
This allows clients to import data using the module name.
> feat: create the main entrypoint module

- src/bidiMapper/modules/browser/BrowserProcessor.ts
- src/bidiMapper/modules/browser/BrowserProcessot.spec.ts
and return "unsupported" instead of "invalid argument" for unsupported cases
> chore: do not allow for `socksVersion` without `socksProxy`

- src/bidiMapper/CommandProcessor.ts
- tests/browsing_context/test_create.py
- tests/conftest.py
- tests/input/test_input.py
Namely:
* Retry session creation in case of timeouts to address [this kind of issues](https://github.com/user-attachments/files/20591312/test_input_performActionsEmitsDblClicks.log.txt).
* Return `no such frame` error if CDP command failed due to CDP session being closed during BiDi command processing. 
* Disable background tests for headless.
ChromeDriver headless tests passed 40 times: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/15446563361.
> ci: e2e test improvements

- src/bidiServer/MapperCdpConnection.ts
- tests/conftest.py
- tests/test_helpers.py
* Always hidden Mapper tab in Node runner.
* Improve conftest logging.
* Tolerate expected teardown exceptions.
Example run on headless ubuntu node: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/15486876047
> test: deflake tests

- tests/webExtension/test_web_extension.py
We have `sleep` introduced in https://github.com/GoogleChromeLabs/chromium-bidi/pull/3151. We have a bunch of other `xfail`s, but they don't cause problems. The specific failing e2e runs are already gone, but I assume it was some unrelated issue.
> test: remove sleep before pytest.xfail

- src/bidiMapper/BidiNoOpParser.ts
- src/bidiMapper/BidiParser.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/modules/browser/UserContextConfig.ts
- src/bidiMapper/modules/cdp/CdpTarget.ts
- src/bidiMapper/modules/emulation/EmulationProcessor.ts
- src/bidiTab/BidiParser.ts
- src/protocol-parser/generated/webdriver-bidi.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/generated/webdriver-bidi.ts
- tests/emulation/test_orientation.py
Implement [`emulation.setScreenOrientationOverride`](https://www.w3.org/TR/webdriver-bidi/#command-emulation-setScreenOrientationOverride).
> feat: support `emulation.setScreenOrientationOverride`

- src/bidiMapper/modules/emulation/EmulationProcessor.ts
- tests/emulation/test_timezone.py
Apparently CDP supports timezone offset emulations, they just have to be prefixed with `GTM`.
> feat: support timezone offset emulation

- tests/tools/local_http_server.py
- tests/tools/test_local_http_server.py
Trying to address e2e tests failures on MacOS started recently:
```
tests/bluetooth/test_characteristic_emulation.py::test_bluetooth_simulateCharacteristic[read] RERUN [  1%]
tests/bluetooth/test_characteristic_emulation.py::test_bluetooth_simulateCharacteristic[read] RERUN [  1%]
tests/bluetooth/test_characteristic_emulation.py::test_bluetooth_simulateCharacteristic[read] ERROR [  1%]
tests/bluetooth/test_characteristic_emulation.py::test_bluetooth_simulateCharacteristic[writeWithoutResponse] RERUN [  1%]
tests/bluetooth/test_characteristic_emulation.py::test_bluetooth_simulateCharacteristic[writeWithoutResponse] RERUN [  1%]
tests/bluetooth/test_characteristic_emulation.py::test_bluetooth_simulateCharacteristic[writeWithoutResponse] ERROR [  1%] …
```
> test: increase Flask server timeout

- src/bidiMapper/modules/cdp/CdpTarget.ts
There is no reason to fail target workflow if there was some error on the CDP level. For troubleshooting logs should be used and testing should rely on observable effects.
Related: https://github.com/GoogleChromeLabs/chromium-bidi/issues/3698
> fix: handle target config errors gracefully

- src/bidiMapper/modules/cdp/CdpTargetManager.ts
- src/bidiMapper/modules/script/RealmStorage.ts
- Why would findReam return nothing on more than one match?
- Add support for filtering for non-sandboxed realms.
- Use the first matching realm.
> fix: correct broken realm lookup
