GoogleChromeLabs/chromium-bidi

- src/cdp/cdpClient.ts
Rename DomainBase to DomainImpl to match name of CdpClientImpl.
Update the type of CdpClient so that all of its domain properties also extend DomainImpl. This lets callers access the EventEmitter methods like removeListener which will be useful later for implementing things like unsubscribe.
> Make domain objects extend DomainImpl

- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/scripts/eval.es
- tests/test_bidi.py
Unify  naming "seriali**S**e" -> "Seriali**Z**e".
Simply changed all the string constants to be the same.
> Unify "serialiSe" -> "SerialiZe".

- src/bidiMapper/bidiProtocolTypes.ts
- src/bidiMapper/commandProcessor.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- tests/test_bidi.py
> Typification

- src/bidiMapper/bidiProtocolTypes.ts
- src/bidiMapper/commandProcessor.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- tests/test_bidi.py
Rename method name according to https://github.com/w3c/webdriver-bidi/issues/140
> `PROTO.script.invoke` -> `PROTO.script.callFunction`

- src/bidiMapper/bidiProtocolTypes.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/scripts/eval.spec.ts
- tests/test_bidi.py
* Added `this` parameter to the command `script.callFunction`.
* Specified types (Primitive, Remote, Local).
* Added e2e tests to async functions.
> Add `this` parameter to `callFunction` command.

- src/bidiMapper/bidiProtocolTypes.ts
- src/bidiMapper/commandProcessor.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/scripts/eval.es
- tests/test_bidi.py
+ implement (with some suggestions) NodeRemoteValue serialization.
> Prototype `PROTO.browsingContext.findElement`.

- .github/workflows/e2e.js.yml
- .github/workflows/unit.js.yml
* Run tests for each push, not only to `main`.
* Run tests only once. Having both `push` and `pull_request` triggered each test run twice.
> Run tests for each pull_request, not only to `main`.

- src/bidiMapper/bidiProtocolTypes.ts
- src/bidiMapper/commandProcessor.ts
- src/bidiMapper/domains/context/browsingContextProcessor.spec.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/mapper.ts
- src/bidiMapper/utils/bidiServer.ts
- src/bidiServerRunner.ts
- tests/_helpers.py
- tests/test_browsing_context.py
- tests/test_events.py
- tests/test_protocol_basics.py
- tests/test_script.py
- tests/test_serialization.py
* Implement `session.subscribe` command.
* Added tests.
* Update tests.
* Remove redundancy in types. Move all the `BiDi` type definitions to `src/bidiMapper/bidiProtocolTypes.ts`.
> Implement `session.subscribe` command

- .gitignore
- README.md
I added instruction about running WPT tests locally. I'd really appreciate if you could try it out.
> Instructions how to run WPT locally

- examples/cross-browser.py
#83 removed extra "result" layer, which wasn't reflected in the example. Created and issue to add example to the CI as well: #107. This PR fixes the example script.
> fix example

- examples/app.html
- examples/cross-browser.py
Since we want to run this on CI, it’s better to have a fixed target page that is available locally than to have an ever-changing one that requires a network request to access.
Issue: #107
> Make examples/cross-browser.py hermetic

- examples/cross-browser.py
> Add logging to cross-browser example

- package.json
- src/bidiMapper/domains/context/browsingContextProcessor.spec.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- tests/test_browsing_context.py
Don't wait for Context to be initialized before updating context with new info.
> Update Context/target handling.

- src/bidiMapper/domains/context/browsingContextProcessor.spec.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/domains/protocol/bidiProtocolTypes.ts
- tests/test_browsing_context.py
Move waiting for initialization logic to context itself.
> Simplify Context

- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/context.ts
- src/bidiMapper/domains/context/frameContext.ts
- src/bidiMapper/domains/context/targetContext.ts
- src/bidiMapper/domains/log/logManager.ts
- src/bidiMapper/domains/protocol/bidiProtocolTypes.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
- tests/test_events.py
- tests/test_script.py
- tests/test_serialization.py
- wpt-metadata/webdriver/tests/bidi/script/call_function/call_function.py.ini
- wpt-metadata/webdriver/tests/bidi/script/evaluate/await_promise.py.ini
- wpt-metadata/webdriver/tests/bidi/script/evaluate/evaluate.py.ini
[Support `none` ownership type · Issue #211 · GoogleChromeLabs/chromium-bidi](https://github.com/GoogleChromeLabs/chromium-bidi/issues/211)
> Support `resultOwnership: none`

- examples/README.md
- runBiDiServer.sh
- runWPT.sh
- fix typos
- do not permanently change directories when executing run scripts
> Miscellaneous improvements

- src/bidiMapper/domains/script/scriptEvaluator.ts
- tests/_helpers.py
Serialization + deserialization should not wait for Promises.
Tested via WPT tests https://github.com/web-platform-tests/wpt/pull/34933
> Fix exception serialization

- README.md
- package.json
- src/cdp/cdpClient.ts
- utils/filter_protocol_commands.js
- utils/filter_protocol_commands.sh
Furthermore, prune even more fields than in https://github.com/GoogleChromeLabs/chromium-bidi/commit/b12c9ef6f91f2ff0f0ad55bbf3820731ce2d6319.
Pair programmed with @OrKoN.
> reduce mapper protocol domains size with native nodejs module

- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
- tests/_helpers.py
- tests/test_script.py
- wpt-metadata/webdriver/tests/bidi/script/disown/target.py.ini
Disown handles only in the realm where it was created.
> Track created handles

- README.md
- src/bidiMapper/utils/bidiServer.ts
- tests/test_protocol_basics.py
- tests/test_subscription.py
Empty string channel is ignored.
> Ignore empty string `channel`

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/protocol/bidiProtocolTypes.ts
https://w3c.github.io/webdriver-bidi/#command-browsingContext-create
> Add `referenceContext` param to `BrowsingContext.create` command

- .github/workflows/e2e.js.yml
- .github/workflows/wpt.yml
- package.json
Run WPT and e2e tests after each merge to main. Needed to keep a track of flaky tests.
> Run checks on main

- .npmrc
- package-lock.json
- package.json
package-lock.json reduces problems with reproducibility and improves security.
> Sort dev and prod dependencies + package-lock.json

- src/bidiMapper/domains/script/scriptEvaluator.ts
When serializing console event arguments, send only `objectId`, `unserializableValue` or `value` instead of sending back the whole received payload including preview etc.
> Reduce CDP traffic during log serialization

- .prettierrc.cjs
- package.json
Mirror puppeteer's approach ref.
https://github.com/puppeteer/puppeteer/pull/8542
> Use Google's TS style guide's format config

- src/bidiMapper/bidiMapper.ts
- src/bidiMapper/cdp.ts
- src/bidiMapper/commandProcessor.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/domains/log/logManager.ts
- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/utils/bidiServer.ts
This PR makes it explicit which CDP interfaces
the mapper implementation expects.
> Define CDP interfaces that mapper needs

- examples/requirements.txt
- tests/_helpers.py
- tests/requirements.txt
- tests/test_browsing_context.py
- tests/test_cdp.py
- tests/test_log_events.py
- tests/test_nested_browsing_context.py
- tests/test_protocol_basics.py
- tests/test_sandbox.py
- tests/test_script.py
- tests/test_serialization.py
- tests/test_subscription.py
Bump dependencies to support Python 3.10
> Support python 3.10

- .style.yapf
- examples/_helpers.py
- examples/console_log_example.py
- examples/script_example.py
- package.json
- tests/_helpers.py
- tests/test_browsing_context.py
- tests/test_cdp.py
- tests/test_log_events.py
- tests/test_nested_browsing_context.py
- tests/test_protocol_basics.py
- tests/test_sandbox.py
- tests/test_script.py
- tests/test_serialization.py
- tests/test_subscription.py
Use pep8 style to mirror Chromium, Devtools-Frontend and WPT: https://chromium.googlesource.com/chromium/src/+/master/styleguide/python/python.md
> Add YAPF python formatter integration

- .github/workflows/e2e.js.yml
- .github/workflows/publish-on-tag.yml
- .github/workflows/wpt.yml
- README.md
docs: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
> readme: add github status badges for tests

- src/bidiMapper/domains/script/scriptEvaluator.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
- tests/test_log_events.py
- tests/test_script.py
- tests/test_serialization.py
* Implement [`type` field of "ScriptEvaluateResult"](https://github.com/w3c/webdriver-bidi/pull/340).
> Add script result type

- examples/console_log_example.py
- examples/script_example.py
First step to address https://github.com/GoogleChromeLabs/chromium-bidi/issues/357.
Add simple assertions in the example scripts.
> Add assertions to the example scripts

- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/bidiMapper/domains/events/SubscriptionManager.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
- tests/test_browsing_context.py
- tests/test_cdp.py
- tests/test_log_events.py
- tests/test_serialization.py
- wpt-metadata/webdriver/tests/bidi/browsing_context/capture_screenshot/capture_screenshot.py.ini
- wpt-metadata/webdriver/tests/bidi/browsing_context/capture_screenshot/frame.py.ini
- wpt-metadata/webdriver/tests/bidi/browsing_context/capture_screenshot/invalid.py.ini
- wpt-metadata/webdriver/tests/bidi/browsing_context/classic_interop/window_handle.py.ini
- wpt-metadata/webdriver/tests/bidi/session/subscribe/events.py.ini
- wpt-metadata/webdriver/tests/bidi/session/unsubscribe/events.py.ini
Addressing https://github.com/GoogleChromeLabs/chromium-bidi/issues/353.
Implement subscription to the whole domain, not only specific event.
> Subscribe to the whole  domain

- src/bidiMapper/domains/events/SubscriptionManager.ts
- tests/_helpers.py
- tests/test_subscription.py
Subscription to a given event means subscription to all the nested events as well.
> Subscribe to context subscribes to nested contexts.

- configs/tsconfig.base.json
- src/bidiServer/bidiServerRunner.ts
docs: https://www.typescriptlang.org/tsconfig#noImplicitReturns
> tsconfig.base.json: add noImplicitReturns

- README.md
- examples/README.md
Main motivation for this PR is to prepare to add pre-commit instructions to the README (https://github.com/GoogleChromeLabs/chromium-bidi/pull/373)
> README: deduplicate examples/ and reorganize sections

- .github/workflows/e2e.js.yml
- .github/workflows/unit.js.yml
- .github/workflows/wpt.yml
This allows one to develop / open PRs in multiple branches at the same time in a chromium-like fashion (depot_tools)
> github workflows: standardize `on: pull request` for all branches

- src/bidiMapper/domains/script/scriptEvaluator.ts
> move all static readonly properties to module scope

- src/bidiMapper/domains/events/EventManager.ts
> make all EventManager properties and methods non-static

- src/bidiTab/bidiTab.ts
- src/bidiTab/mapperTabPage.ts
> eslint no-extraneous-class: improve mapperTabPage

- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
Bug: https://github.com/GoogleChromeLabs/chromium-bidi/issues/392
> make ScriptEvaluator non-static

- src/bidiMapper/BidiServer.ts
- src/bidiServer/bidiServerRunner.ts
- src/bidiTab/mapperTabPage.ts
> make a few more classes/methods non-static

- .eslintrc.js
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/events/SubscriptionManager.ts
- src/bidiMapper/domains/log/logManager.ts
- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
- src/bidiServer/index.ts
- src/cdp/cdpClient.spec.ts
- src/cdp/cdpConnection.spec.ts
- no-implicit-coercion
- no-undef
- func-names
- no-negated-condition
- no-duplicate-imports
Partially:
- require-await
> add a few ESLint rules

- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/domains/log/logHelper_getRemoteValuesText.spec.ts
- src/bidiMapper/domains/log/logHelper_logMessageFormatter.spec.ts
- src/bidiServer/bidiServerRunner.ts
- src/bidiServer/index.ts
- src/bidiTab/bidiTab.ts
- src/cdp/stubTransport.spec.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
- src/utils/deferred.ts
- src/utils/log.ts
- prefer ReadonlyMap over Readonly<Map>
- prefer unknown or specific types over any: https://google.github.io/styleguide/tsguide.html#any
> make a few TypeScript improvements not covered by ESLint

- .eslintrc.js
- rollup.config.js
- src/bidiMapper/BidiServer.ts
- src/bidiMapper/CdpConnection.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/bidiMapper/domains/events/SubscriptionManager.ts
- src/bidiMapper/domains/log/logManager.ts
- src/bidiMapper/domains/script/realm.ts
- src/bidiServer/bidiServerRunner.ts
- src/bidiServer/index.ts
- src/bidiServer/mapperServer.ts
- src/bidiTab/bidiTab.ts
- src/cdp/cdpClient.spec.ts
- src/cdp/cdpClient.ts
- src/cdp/cdpConnection.spec.ts
- src/cdp/cdpConnection.ts
- src/cdp/stubTransport.spec.ts
- src/protocol-parser/protocol-parser.ts
- src/utils/EventEmitter.spec.ts
- src/utils/buffer.spec.ts
- src/utils/processingQueue.spec.ts
- src/utils/processingQueue.ts
Docs: https://eslint.org/docs/latest/rules/sort-imports
> add ESLint rule: sort-imports

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/log/logManager.ts
- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/domains/script/realmStorage.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
With the intent to support the ability to run multiple bidi sessions simultaneously.
Closes #392
> make Realm.#realmMap non-static by moving it to RealmStorage

- .pre-commit-config.yaml
In particular, fix a regression related to the isort hook (https://github.com/PyCQA/isort/issues/2077)
> pre-commit: update all hooks

- src/bidiTab/mapperTabPage.ts
- src/utils/log.ts
> mapper tab logs: add type safety and add missing command parser

- .eslintrc.js
- src/bidiServer/index.ts
- src/bidiServer/mapperServer.ts
- src/bidiTab/bidiTab.ts
- src/cdp/cdpClient.ts
- src/cdp/cdpConnection.ts
- src/cdp/stubTransport.spec.ts
- src/cdp/websocketTransport.ts
- src/utils/processingQueue.spec.ts
Uniformize variable naming conventions in our codebase.
> eslint: add no-underscore-dangle rule

- test-report/htmlWptReport.mjs
Add missing DOCTYPE, language, and remove more optional start/end tags per Google HTML style guide.
https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags
> Improve HTML output for WPT report

- test-report/htmlWptReport.mjs
> Escape HTML in report

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
Use catch instead of reject.
Closes #411
> Do not trigger unhandled promise rejections in BidiMapper

- .github/workflows/e2e.yml
- .github/workflows/generate-wpt-report.yml
- .github/workflows/pre-commit.yml
- .github/workflows/publish-on-tag.yml
- .github/workflows/wpt-chromedriver.yml
This is merely for consistency with the other github actions in this repo.
Additionally, also for consistency, drop the single quotes around `'pip'`.
This is a trivial commit. Submitting it directly to avoid noise.
> pre-commit workflow: add missing pip cache to setup-python action

- src/bidiMapper/domains/context/browsingContextStorage.ts
> browsing context find: allow returning undefined

- README.md
> add generate WPT report badge to README

- .github/workflows/generate-wpt-report.yml
- README.md
- runWPT.sh
> wpt-metadata: adjust paths for #466

- examples/README.md
- examples/_helpers.py
- examples/classic_to_bidi_example.py
The example would work after ChromeDriver [implements `sharedId`](https://chromium-review.googlesource.com/c/chromium/src/+/4127223).
> Classic to BiDi example

- tests/requirements.txt
Reference: https://github.com/hjwp/pytest-icdiff
Split off: #479
> improve pytest ergonomics by adding pytest-icdiff for side-by-side diffs

- tests/test_browsing_context.py
- tests/test_script.py
This is the idiomatic way: https://docs.pytest.org/en/7.1.x/how-to/skipping.html
> pytest: use @pytest.mark.skip instead of _ignore_

- tests/test_subscription.py
If an operation failed for some reason (not subscribed, browsing context not found, etc), do not unsubscribe partially.
Bug: #482
> write a test to check for atomicity of session.unsubscribe

- .github/dependabot.yml
References:
- https://github.com/web-platform-tests/wpt/blob/master/.github/dependabot.yml
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
> dependabot: automatically update github actions and pip and npm packages

- .eslintrc.js
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/log/logManager.ts
- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
- src/bidiServer/mapperReader.ts
- src/bidiTab/bidiTab.ts
Docs: https://eslint.org/docs/latest/rules/no-return-await
> eslint: add no-return-await

- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/get_realms/sandbox.py.ini
> wpt: remove test expectations that are passing

- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/bidiMapper/domains/events/SubscriptionManager.ts
> session.unsubscribe atomicity: follow-up changes

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiTab/bidiTab.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
- tests/test_screenshot.py
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/capture_screenshot/capture_screenshot.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/capture_screenshot/frame.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/capture_screenshot/invalid.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/capture_screenshot/capture_screenshot.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/capture_screenshot/frame.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/capture_screenshot/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/capture_screenshot/capture_screenshot.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/capture_screenshot/frame.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/capture_screenshot/invalid.py.ini
Bug: #514
Spec: https://w3c.github.io/webdriver-bidi/#command-browsingContext-captureScreenshot
> Implement `browsingContext.captureScreenshot` command

- .prettierignore
- package.json
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/cdpTarget.ts
- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/domains/log/logManager.ts
- src/bidiMapper/domains/script/realm.ts
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/capture_screenshot/capture_screenshot.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/capture_screenshot/frame.py.ini
The change is needed to ease the enabling domains on-demand. It is required for network domain.
> Extract CdpTarget from BrowsingContext

- .github/workflows/e2e.yml
- README.md
- package-lock.json
- package.json
- runBiDiServer.sh
- src/bidiServer/index.ts
> Use @puppeteer/browsers for launching

- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/capture_screenshot/capture_screenshot.py.ini
> Update WPT expectations

- src/protocol-parser/protocol-parser.ts
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/print/invalid.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/print/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/print/invalid.py.ini
> `browsingContext.print`: fix a couple of unit tests (cont.)

- tests/test_browsing_context.py
- tests/test_helpers.py
- tests/test_nested_browsing_context.py
To ease reading and maintaining
> In e2e use `goto_url` where possible

- src/bidiMapper/domains/events/EventManager.ts
> EventManager: use composition instead of inheritance for IdWrapper

- .eslintrc.js
- src/bidiMapper/domains/context/browsingContextImpl.ts
Docs: https://eslint.org/docs/latest/rules/object-shorthand
> eslint: add "object-shorthand" rule

- src/bidiMapper/domains/script/realm.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
- tests/test_print.py
- tests/test_screenshot.py
> pre-refactor script evaluator for #319

- tests/conftest.py
- tests/test_helpers.py
Addressing comments from https://github.com/GoogleChromeLabs/chromium-bidi/pull/553
> Pytest leftovers

- examples/README.md
- examples/_helpers.py
- examples/screenshot_example.py
> Add example script for capture screenshot

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiTab/bidiTab.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/remove_preload_script/invalid_tentative.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/remove_preload_script/invalid_tentative.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/remove_preload_script/invalid_tentative.py.ini
Bug: #584
Spec: https://w3c.github.io/webdriver-bidi/#command-script-removePreloadScript
> Scaffold `script.removePreloadScript`

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
- tests/test_preload_script.py
Bug: #293
CDP: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-addScriptToEvaluateOnNewDocument
Spec: https://w3c.github.io/webdriver-bidi/#command-script-addPreloadScript
> Implement `script.addPreloadScript`

- .mocharc.json
- test-report/htmlWptReport.mjs
- test-report/htmlWptReportFormatter.mjs
- test-report/htmlWtpReport.spec.mjs
> Improve WPT report

- tests/conftest.py
- tests/test_browsing_context.py
- tests/test_helpers.py
- tests/test_log_events.py
- tests/test_nested_browsing_context.py
- tests/test_preload_script.py
- tests/test_script.py
- tests/test_serialization.py
- tests/test_shared_id.py
- tests/test_subscription.py
Docs: https://docs.pytest.org/en/latest/how-to/fixtures.html#fixture-parametrize
> pytest: misc fixture additions: html, iframe, parameterized fixtures

- src/bidiMapper/domains/log/logManager.ts
- src/bidiServer/bidiServerRunner.ts
- tests/test_helpers.py
- Bidi -> BiDi
- mypy: make `wait` navigation param an union of string literal instead of accepting any string
- move `execute_command` closer to `send_JSON_command`
> misc trivial changes

- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/domains/network/networkProcessor.ts
- src/utils/DefaultMap.spec.ts
- src/utils/DefaultMap.ts
It's like a plain ES6 Map, with the difference that it returns a default value whenever the key is absent from the Map.
This simplifies constructs like:
if (!this.has(key)) {
this.set(key, new Set());
}
this.get(key)!.add(1);
To simply:
this.get(key).add(1);
> Introduce Default Map, inspired by defaultdict in python

- .pre-commit-config.yaml
> pre-commit: prevent chai describe/it only() check-in

- .github/workflows/e2e.yml
- package-lock.json
- package.json
- runBiDiServer.sh
- src/bidiServer/index.ts
The goal is to provide verbose logs of e2e run to help investigate failures if any.
> Use `runBiDiServer.sh` as a single entry point

- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/print/context.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/print/margin.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/print/orientation.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/print/page.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/print/page_ranges.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/print/scale.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/call_function/result.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/evaluate/result.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/print/context.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/print/margin.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/print/orientation.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/print/page.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/print/page_ranges.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/print/scale.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/call_function/result.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/evaluate/result.py.ini
HEAD is currently broken. Some WPT tests related to printing are failing. Update WPT expectations to match that.
> Update WPT expectations at HEAD

- .github/workflows/e2e.yml
- .github/workflows/generate-wpt-report.yml
- .github/workflows/wpt-chromedriver.yml
- .github/workflows/wpt-mapper.yml
- package-lock.json
- package.json
Update @puppeteer/browsers to 1.0.0 given
https://github.com/puppeteer/puppeteer/pull/10108 is landed.
> CI: use chrome for testing instead of chromium

- .github/workflows/generate-wpt-report.yml
- .github/workflows/wpt-chromedriver.yml
- .github/workflows/wpt-mapper.yml
There are 1500 WPT tests now. Sometimes they take longer than 30min.
> CI: increase WPT test timeout to 60min

- src/bidiMapper/domains/context/PreloadScriptStorage.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextStorage.spec.ts
- src/bidiMapper/domains/context/cdpTarget.ts
- src/bidiMapper/domains/log/logManager.ts
- src/bidiMapper/domains/network/networkProcessor.ts
- src/bidiMapper/domains/network/networkRequest.ts
Recreating it from https://github.com/GoogleChromeLabs/chromium-bidi/pull/680
> TS: ensure all local imports have a .js suffix

- src/bidiMapper/domains/script/realm.ts
- tests/test_serialization.py
- tests/test_shared_id.py
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/call_function/arguments.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/call_function/result_node.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/call_function/sandbox.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/evaluate/result_node.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/evaluate/sandbox.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/call_function/arguments.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/call_function/result_node.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/call_function/sandbox.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/evaluate/result_node.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/evaluate/sandbox.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/call_function/arguments.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/call_function/result_node.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/call_function/sandbox.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/evaluate/result_node.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/evaluate/sandbox.py.ini
`sharedId` was set inside value, but it has to be set on the top level, next to type.
> Fix `sharedId`

- README.md
- src/bidiMapper/bidiMapper.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/script/scriptEvaluator.ts
- src/bidiServer/bidiServerRunner.ts
- src/bidiTab/bidiTab.ts
- tests/conftest.py
- tests/test_browsing_context.py
- tests/test_nested_browsing_context.py
- tests/test_network.py
- tests/test_preload_script.py
- TODO: means it's typically something we intend to address to achieve spec compliance
- XXX: means "nice to have" or "maybe we will eventually address it", but it's not essential
Roughly inspired by
https://drewdevault.com/2023/03/09/2023-03-09-Comment-or-no-comment.html
Furthermore:
- remove specific usernames from TODOs
- add missing TODOs (e.g. in skipped tests)
> standardize TODOs in our codebase

- .github/workflows/e2e.yml
- .github/workflows/generate-wpt-report.yml
- .github/workflows/wpt.yml
> Make "Install Chromium" CI step failable

- .github/workflows/e2e.yml
- .github/workflows/generate-wpt-report.yml
- .github/workflows/wpt.yml
- package.json
- runWPT.sh
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/events/SubscriptionManager.ts
- src/bidiMapper/domains/network/networkRequest.ts
- src/cdp/cdpClient.spec.ts
- test-report/htmlWptReportFormatter.mjs
- test-report/htmlWtpReport.spec.mjs
c.f. individual commits for the full changes
> miscellaneous ESLint and CI changes

- .eslintrc.js
- install-browser.mjs
- package.json
- runWPT.sh
- src/bidiMapper/CdpConnection.ts
- src/bidiMapper/domains/context/PreloadScriptStorage.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/network/networkRequest.ts
- src/cdp/cdpClient.ts
- src/cdp/cdpConnection.ts
- src/protocol/protocol.ts
- test-report/htmlWptReport.mjs
- test-report/htmlWptReportFormatter.mjs
- tests/test_screenshot.py
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_started/__dir__.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/network/response_started/__dir__.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/classic_interop/__dir__.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/classic_interop/node_shared_id.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_started/__dir__.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/classic_interop/__dir__.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/classic_interop/node_shared_id.py.ini
See commit message for the changes.
> miscellaneous changes

- src/bidiMapper/domains/context/browsingContextImpl.ts
- tests/test_browsing_context.py
Bug: #650
CDP: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-reload
Spec: https://w3c.github.io/webdriver-bidi/#command-browsingContext-reload
> Handle browsing context reload `wait` param

- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/cdpTarget.ts
- tests/test_preload_script.py
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/add_preload_script/add_preload_script.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/add_preload_script/sandbox.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/remove_preload_script/remove_preload_script.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/add_preload_script/add_preload_script.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/add_preload_script/sandbox.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/remove_preload_script/remove_preload_script.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/add_preload_script/add_preload_script.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/add_preload_script/sandbox.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/remove_preload_script/remove_preload_script.py.ini
> Fix more WPT preload script tests

- .eslintrc.js
- package-lock.json
- package.json
- src/bidiServer/bidiServerRunner.ts
- src/bidiServer/index.ts
- src/cdp/cdpConnection.spec.ts
- src/cdp/cdpConnection.ts
- src/utils/buffer.ts
- src/utils/deferred.spec.ts
- src/utils/deferred.ts
And fix a couple additional eslint issues.
This is meant to catch more potential promise errors.
> eslint: add promise plug-in

- src/bidiMapper/domains/context/PreloadScriptStorage.spec.ts
> preload script storage: write unit tests

- README.md
PR https://github.com/GoogleChromeLabs/chromium-bidi/pull/756 made pre-commit unhappy.
> pre-commit: format README.md

- .github/workflows/publish-on-tag.yml
- .github/workflows/unit.yml
- .github/workflows/wpt.yml
- README.md
- package.json
- runWPT.sh
See commit history for changes.
Bug: #361
> npm: add `wpt` target and ensure build is up-to-date when running WPT

- .github/workflows/e2e.yml
- .github/workflows/wpt.yml
> wpt: support optional verbose logging and custom tests

- .github/workflows/e2e.yml
- .github/workflows/wpt.yml
> make a few fixes on workflow_dispatch options for verbose and auto-commit

- src/bidiMapper/CommandProcessor.ts
- src/protocol/protocol.ts
Bug: https://github.com/GoogleChromeLabs/chromium-bidi/issues/749
> Update protocol with Input module types

- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
Bug: #296
Spec: https://w3c.github.io/webdriver-bidi/#type-script-ChannelValue
> channels: maxDepth -> SerializationOptions

- .github/workflows/pre-commit.yml
> add PIP_DISABLE_PIP_VERSION_CHECK to pre-commit github action

- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/__dir__.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/invalid.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/key_events.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/key_modifier.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/pointer_mouse_modifier.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/pointer_pen.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/pointer_touch.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/wheel.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/__dir__.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/key.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/key_events.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/key_modifier.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/pointer_mouse_modifier.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/pointer_pen.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/pointer_touch.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/wheel.py.ini
> input: enable a few WPT tests

- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/key_events.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/key_events.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py.ini
Follow-up-of: https://github.com/GoogleChromeLabs/chromium-bidi/pull/835
> input: enable a few more WPT tests

- src/bidiMapper/domains/context/browsingContextImpl.ts
- tests/test_viewport.py
Follow-up to https://github.com/GoogleChromeLabs/chromium-bidi/pull/817
> test: add a test for unsupported viewports

- src/bidiMapper/domains/context/browsingContextImpl.ts
- tests/test_viewport.py
Reverts GoogleChromeLabs/chromium-bidi#886
> chore: Revert "test: add a test for unsupported viewports"

- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/protocol/protocol.ts
- tests/test_browsing_context.py
Still test need to be added, but wanted to see if the implementation makes sense.
> feat: add `browsingContext.navigationStarted`

- README.md
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/cdpTarget.ts
- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/bidiMapper/domains/events/SubscriptionManager.ts
- src/bidiTab/bidiTab.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/protocol.ts
- tests/test_cdp.py
- tests/test_network.py
> chore: refine BiDi+

- runWPT.sh
> chore: use `sysctl` for macOS

- codecov.yml
The intent is to disable this kind of comment: https://github.com/GoogleChromeLabs/chromium-bidi/pull/920#issuecomment-1613744317
Bug: #17
> ci: codecov: disable comments

- src/protocol/protocol.ts
Bug: https://github.com/w3c/webdriver-bidi/pull/452
> feat: protocol: add WindowProxyProperties

- pytest.ini
- tests/requirements.txt
Docs: https://pypi.org/project/pytest-timeout/
> test: pytest adjustments to deal with timeouts

- src/bidiMapper/domains/context/browsingContextImpl.ts
- tests/test_browsing_context.py
> fix: stop fragmentNavigated from emitting for normal navigation

- .pre-commit-config.yaml
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/cdpTarget.ts
- src/bidiMapper/domains/events/EventManager.ts
- src/bidiMapper/domains/events/SubscriptionManager.spec.ts
- src/bidiMapper/domains/log/logManager.ts
- src/bidiMapper/domains/script/realm.ts
- src/protocol/protocol.ts
- tests/test_log_events.py
> chore: refactoring for network request intercept

- .github/workflows/e2e.yml
- .github/workflows/wpt.yml
- install-browser.mjs
- runBiDiServer.sh
> ci: npm run e2e runs local CfT

- src/bidiMapper/domains/context/bidiPreloadScript.ts
- tests/test_preload_script.py
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/add_preload_script/sandbox.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/remove_preload_script/sandbox.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/add_preload_script/sandbox.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/script/remove_preload_script/sandbox.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/add_preload_script/sandbox.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/script/remove_preload_script/sandbox.py.ini
Bug: #293
Docs: go/chrome-devtools:preload-script-world-name
> feat: preload scripts: support sandboxes

- examples/preload_script_example.py
This closes the preload script milestone: https://github.com/GoogleChromeLabs/chromium-bidi/milestone/15
Closes: #293
> docs: add preload script example

- src/bidiMapper/domains/events/EventManager.ts
Follow-up-of: https://github.com/GoogleChromeLabs/chromium-bidi/pull/971/files
> chore: align with go/tsstyle-oss

- src/bidiMapper/domains/script/realm.ts
- tests/test_serialization.py
Bug: #562
Tested: Works for Map and Set iterators. Array and String iterators will need a separate change in V8.
> feat: support iterator serialization

- .github/workflows/e2e.yml
- package.json
- tools/install-browser.mjs
- tools/run-bidi-server.mjs
- tools/run-wpt.mjs
> ci: add windows

- package-lock.json
- package.json
Docs: https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
> build: remove deprecated 'codecov' package

- package-lock.json
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/context/cdpTarget.ts
- src/bidiMapper/domains/script/PreloadScriptStorage.spec.ts
- src/bidiMapper/domains/script/PreloadScriptStorage.ts
- src/bidiMapper/domains/script/ScriptProcessor.ts
- src/bidiMapper/domains/script/bidiPreloadScript.ts
As per our offline discussion we should split all the logic not to be handled by the browingContextProcessor and have one processor per Module.
> chore: extract Script commands into separate processor

- .github/workflows/chromium-roll-reminder.yml
- README.md
> ci: create a Roll reminder

- .github/workflows/puppeteer.yml
Similar to the Devtools one we created we should have one for Puppeteer here.
> ci: add Puppeteer label

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/domains/context/browsingContextImpl.ts
- src/bidiMapper/domains/context/browsingContextProcessor.ts
- src/bidiMapper/domains/script/realm.ts
- src/bidiTab/bidiTab.ts
- src/bidiTab/mapperTabPage.ts
- src/cdp/cdpConnection.ts
- src/utils/log.ts
- src/utils/processingQueue.ts
While trying it use it I found it hard to understand all the different types
also having them with capital letters needs more typing.
Spaces in the log name also behave strange paired with filter.
> chore: rename logging

- src/bidiServer/bidiServerRunner.ts
- src/bidiServer/index.ts
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/set_viewport/set_viewport.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/set_viewport/set_viewport.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/set_viewport/set_viewport.py.ini
> fix: ignore cert errors in the test driver

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/events/EventManager.ts
- src/bidiTab/bidiTab.ts
- src/utils/log.ts
- src/utils/processingQueue.spec.ts
- src/utils/processingQueue.ts
This will show the last event to be pick up by the processing queue if the Class gets stuck. 
Encountered a new issue where it's stuck in Puppeteer test:  `Locator should work with OOPIF` , need a way to debug.
> chore: way to debug stuck Processing Queue

- .github/workflows/update-bidi-types.yml
> chore: use main for `cddlconv`

- src/bidiMapper/domains/network/NetworkRequest.ts
- tests/network/test_network.py
> fix: filter only sent cookies

- tools/wpt-report-builder/formatter.mjs
Removes some `prefixes` in order to be more digestible and closer to the wpt.fyi dashboard that way it's easy to compare.
> chore: remove some prefixes for website

- src/bidiMapper/domains/network/NetworkProcessor.ts
- src/bidiMapper/domains/network/NetworkStorage.spec.ts
- src/bidiMapper/domains/network/NetworkStorage.ts
- tests/network/test_add_intercept.py
Issue #1183
Spec: https://w3c.github.io/webdriver-bidi/#match-url-pattern:~:text=If%20scheme%20is%20special%2C%20append%20%22//%22%20to%20pattern%20url.
> feat: Network Intercept: handle special schemes

- src/bidiMapper/domains/network/NetworkRequest.ts
> feat: add url getter to NetworkRequest

- .github/workflows/e2e.yml
- .github/workflows/wpt.yml
- src/bidiMapper/BidiServer.ts
- src/bidiMapper/domains/context/BrowsingContextProcessor.ts
- src/bidiMapper/domains/script/ChannelProxy.ts
- src/bidiMapper/domains/script/Realm.ts
- src/bidiServer/MapperServer.ts
- src/bidiServer/bidiServerRunner.ts
- src/bidiTab/bidiTab.ts
- src/bidiTab/mapperTabPage.ts
- src/cdp/cdpConnection.ts
- src/utils/log.ts
- tools/run-bidi-server.mjs
- tools/run-wpt.mjs
Some variable renaming cleanup
> chore: fix logging issues

- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/reload/reload.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/reload/reload.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/reload/reload.py.ini
Following https://github.com/web-platform-tests/wpt/issues/41083#issuecomment-1709816660 and https://github.com/web-platform-tests/wpt/pull/41841
> test: reenable browsing context reload test

- src/bidiMapper/domains/context/CdpTarget.ts
This PR fixes an issue where Node.js throws from unhandled promises in the array due to the `await` from sending 'Runtime.runIfWaitingForDebugger'.
> fix: unhandled promises in CDP targets

- .github/workflows/e2e.yml
- .github/workflows/wpt.yml
Some object/arrays are reported as `[Object]/[Array]`.
> ci: deeper logs

- src/bidiMapper/domains/network/NetworkManager.ts
- src/bidiMapper/domains/network/NetworkRequest.ts
- src/bidiMapper/domains/network/NetworkStorage.spec.ts
- src/bidiMapper/domains/network/NetworkStorage.ts
- src/utils/processingQueue.spec.ts
- src/utils/processingQueue.ts
- tests/network/test_network.py
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/network/before_request_sent/__dir__.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
I found out my changes from Network Redirects were omitted and never found.
I re-added them here, but still investigating it this is the correct approach.
> feat: restore network redirects

- package-lock.json
- package.json
- src/bidiMapper/domains/network/NetworkProcessor.ts
- src/bidiMapper/domains/network/NetworkStorage.spec.ts
- src/bidiMapper/domains/network/NetworkStorage.ts
- src/utils/UrlPattern.spec.ts
- src/utils/UrlPattern.ts
Uses dependency: https://www.npmjs.com/package/urlpattern-polyfill
Issue: #1183
Spec: https://w3c.github.io/webdriver-bidi/#get-the-network-intercepts
WPT: https://github.com/web-platform-tests/wpt/pull/41662/
> feat: add get network intercepts method

- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/reload/frame.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/reload/frame.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/reload/frame.py.ini
Bug: https://github.com/web-platform-tests/wpt/issues/41083
> test: enable browsing_context/reload/frame.py

- src/bidiMapper/domains/context/BrowsingContextProcessor.ts
- src/bidiMapper/domains/script/Realm.ts
- src/utils/CdpErrorConstants.ts
Docs: https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/core/protocol_client/InspectorBackend.ts;l=36-40;drc=7bb9852d623d0a3480677ebce55c8b87ca8cc4ae
> chore: introduce a CdpErrorConstants class

- src/bidiMapper/domains/network/NetworkProcessor.spec.ts
> test: add unit tests for network processor parseUrlPatterns

- src/bidiMapper/domains/network/NetworkManager.ts
- src/bidiMapper/domains/network/NetworkRequest.ts
- src/bidiMapper/domains/network/NetworkStorage.ts
- src/bidiTab/Transport.ts
- tests/network/test_add_intercept.py
- tests/network/test_remove_intercept.py
- tests/test_helpers.py
> feat: handle `Fetch.requestPaused` event

- src/bidiMapper/domains/context/CdpTarget.ts
- src/bidiMapper/domains/network/NetworkManager.ts
- src/bidiMapper/domains/network/NetworkProcessor.ts
- src/bidiMapper/domains/network/NetworkRequest.ts
- src/bidiMapper/domains/network/NetworkStorage.spec.ts
- src/bidiMapper/domains/network/NetworkStorage.ts
- tests/conftest.py
- tests/network/test_fail_request.py
Bug: #644
Spec: https://w3c.github.io/webdriver-bidi/#command-network-failRequest
> feat: implement network interception fail request

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
The other values are deprecated.
> chore: use `cssVisualViewport`

- src/bidiTab/mapperTabPage.ts
In the Mapper tab, there should be a single `CDP`, and a single `BiDi` section instead of `cdp:SEND ▸`, `cdp:RECV ◂` etc. 
https://github.com/GoogleChromeLabs/chromium-bidi/pull/891/files#r1334118898
Adding e2e test would prevent from braking this functionality, but it's complicated. So for now we have to manually check if the mapper tab works.
> fix: mapper tab debugging logs

- src/bidiMapper/domains/input/ActionDispatcher.ts
> fix: round tilt values

- src/bidiMapper/domains/input/ActionDispatcher.ts
> fix: part 2 of #1391

- src/bidiMapper/domains/network/NetworkManager.ts
- src/bidiMapper/domains/network/NetworkProcessor.spec.ts
- src/bidiMapper/domains/network/NetworkProcessor.ts
- src/bidiMapper/domains/network/NetworkRequest.ts
- src/bidiMapper/domains/network/NetworkStorage.spec.ts
- src/bidiMapper/domains/network/NetworkStorage.ts
- src/bidiMapper/domains/network/NetworkUtils.spec.ts
- src/bidiMapper/domains/network/NetworkUtils.ts
- tests/browsing_context/test_nested_browsing_context.py
- tests/conftest.py
- tests/network/test_continue_request.py
- tests/network/test_fail_request.py
- tests/test_helpers.py
Bug: #644
Spec: https://w3c.github.io/webdriver-bidi/#command-network-continueRequest
> feat(network interception): implement continue request

- src/bidiServer/BrowserInstance.ts
Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1458533#c11
> chore: disallow chrome browser signin

- tests/browsing_context/test_set_viewport.py
- tests/network/test_add_intercept.py
- tests/network/test_continue_request.py
- tests/network/test_fail_request.py
- tests/network/test_remove_intercept.py
- tests/script/test_disown.py
- tests/script/test_remove_preload_script.py
- tests/script/test_shared_id.py
- tests/session/test_subscription.py
Docs: https://stackoverflow.com/a/56569533/1745064
> test: use `match` argument in `pytest.raises` to simplify assertions

- tests/browsing_context/test_get_tree.py
- tests/browsing_context/test_nested_browsing_context.py
- tests/conftest.py
- tests/network/test_add_intercept.py
- tests/network/test_continue_request.py
- tests/network/test_fail_request.py
- tests/network/test_network.py
- tests/network/test_remove_intercept.py
This is in anticipation to switch them to local URLs.
Related to Issue #575.
> test: move all non-local URLs to pytest fixtures

- tests/network/test_remove_intercept.py
> test: `add test_remove_intercept_does_not_affect_another_intercept`

- tests/network/test_network.py
> chore: add test for SharedWorker

- tests/network/test_fail_request.py
> test: add wait=complete to navigation to try to mitigate flakiness

- src/bidiMapper/domains/network/NetworkProcessor.ts
- src/bidiMapper/domains/network/NetworkRequest.ts
- src/bidiMapper/domains/network/NetworkStorage.spec.ts
- src/bidiMapper/domains/network/NetworkStorage.ts
- src/bidiMapper/domains/network/NetworkUtils.spec.ts
- src/bidiMapper/domains/network/NetworkUtils.ts
- tests/network/__init__.py
- tests/network/test_continue_response.py
> feat: implement network interception continue response

- src/bidiMapper/domains/network/NetworkProcessor.ts
- src/bidiMapper/domains/network/NetworkRequest.ts
- tests/network/test_continue_response.py
- tests/network/test_provide_response.py
> feat: implement network interception provide response

- package.json
> ci: make --watch work with npm run wpt

- .eslintrc.js
- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- src/bidiMapper/domains/context/BrowsingContextProcessor.ts
- src/bidiMapper/domains/log/LogManager.ts
- src/bidiMapper/domains/script/ChannelProxy.ts
- src/bidiMapper/domains/script/Realm.ts
- src/bidiMapper/domains/script/ScriptProcessor.ts
- src/bidiServer/BrowserInstance.ts
- src/bidiServer/MapperCdpConnection.ts
- src/bidiServer/reader.ts
EsLint never fixed the issue that it could auto resolve. Also we had situation where its possible to have 2 different version of EsLint and Prettier to the installed via npm. 
Note: wait for all test to pass + Puppeteer run, before merging.
> chore: use local EsLint/Prettier for hook

- tests/network/test_continue_request.py
- tests/network/test_continue_response.py
- tests/network/test_fail_request.py
- tests/network/test_provide_response.py
- tests/network/test_remove_intercept.py
Use BiDi event instead of CDP event.
Bug: #644
> test: use "network.fetchError" instead of "cdp.Network.loadingFailed"

- src/bidiMapper/domains/script/ScriptProcessor.ts
WPT should cover this case https://github.com/web-platform-tests/wpt/pull/41932
Tracked at #1353
> chore: parse addPreloadScript params

- .pre-commit-config.yaml
In some edge cases the current format may not be correct.
> chore: fix order of pre-commit

- src/bidiMapper/domains/network/NetworkProcessor.ts
- tests/network/test_continue_with_auth.py
> feat: add network intercept continue with auth

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/network/NetworkProcessor.ts
- src/bidiMapper/domains/network/NetworkRequest.ts
- src/bidiMapper/domains/network/NetworkUtils.ts
- tests/network/test_continue_with_auth.py
> feat(network intercept): implement continue with auth (cont.)

- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/create/background.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/create/background.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/create/background.py.ini
Example success (current expectation is FAIL): https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/6705104284/job/18218872567?pr=1500
> test(wpt): update flaky expectations for " test_background[True-window]"

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/CdpTarget.ts
- src/bidiMapper/domains/network/NetworkManager.ts
- src/bidiMapper/domains/network/NetworkRequest.ts
- src/bidiMapper/domains/network/NetworkStorage.spec.ts
- src/bidiMapper/domains/network/NetworkStorage.ts
- tests/network/test_add_intercept.py
- tests/network/test_continue_request.py
- tests/network/test_fail_request.py
- tests/network/test_remove_intercept.py
Bug: https://github.com/GoogleChromeLabs/chromium-bidi/issues/644
> feat(network intercept): populate "intercepts" in base event params

- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/add_intercept/url_patterns.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/network/add_intercept/url_patterns.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/add_intercept/url_patterns.py.ini
> test(network intercept): enable add intercept url_patterns tests

- tests/network/test_network.py
> test(e2e): add test for `network.responseStarted`

- tests/conftest.py
- tests/network/test_continue_request.py
- tests/network/test_continue_with_auth.py
- tests/network/test_fail_request.py
> test(network intercept): enable tests with auth URL

- src/bidiMapper/domains/script/Realm.ts
- tests/script/test_serialization.py
Addressing [the concern](https://github.com/w3c/webdriver-bidi/pull/583#issuecomment-1783023695):
> I still worry a bit that we'll find cases where any client returning a string in a known, but unspecified, format will cause authors to depend on that format (e.g. Chrome returning the string representation of an integer will cause people to write tests that depend on the string representing an integer), but so far I don't think we have consensus that all ids should be UUIDs to avoid this problem.
Make `internalId` a `UUID`, so that clients will not depend on the specific format.
> feat: make `internalId` `UUID`

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- tests/browsing_context/test_navigate.py
- tests/tools/local_http_server.py
Reverts GoogleChromeLabs/chromium-bidi#1539
> Revert "feat: abort navigation if network request failed"

- tools/run-wpt.mjs
Docs: https://web-platform-tests.org/running-tests/command-line-arguments.html
> ci(wpt): add --run-by-dir

- tools/run-wpt.mjs
Attempt to solve the WPT flakiness.
> test: don't run WPT tests in parallel

- .github/workflows/wpt.yml
- tools/run-wpt.mjs
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/activate/activate.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/classic_interop/window_handle.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/create/background.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/handle_user_prompt/handle_user_prompt.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/print/context.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/key_modifier.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/pointer_mouse_modifier.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/pointer_mouse_multiclick.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/release_actions/sequence.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/classic_interop/node_shared_id.py.ini
> ci: respect CHROMEDRIVER parameter in WPT run. Simplified.

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- src/bidiMapper/domains/context/BrowsingContextProcessor.ts
- tests/script/test_realm.py
Reverts GoogleChromeLabs/chromium-bidi#1565
e2e tests started constantly timing out.
> Revert "feat: implement dedicated workers"

- src/bidiMapper/BidiMapper.ts
Export `MapperOptions` type for being able to use from Puppeteer
> feat: export `MapperOptions` TS type

- tests_external/selenium.mjs
- tools/path-getter/path-getter.mjs
Required for https://github.com/GoogleChromeLabs/chromium-bidi/pull/1615. 
Can be used in CI as well.
> chore: extract getting path to browser, ChromeDriver and Mapper logic

- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/traverse_history/context.py.ini
https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/7221021787/job/19675104731
> test: disable flaky test

- .github/workflows/e2e.yml
- .github/workflows/pre-commit.yml
- .github/workflows/publish.yml
- .github/workflows/puppeteer.yml
- .github/workflows/selenium.yml
- .github/workflows/unit.yml
- .github/workflows/update-bidi-types.yml
- .github/workflows/update-browser-version.yml
- .github/workflows/webdriverio.yml
- .github/workflows/wpt.yml
Updated `actions/download-artifact`.
For `actions/checkout` the comment was incorrect, at some point the hash and version deviated and dependabot stopped updating it.
> build(website): fix uploading

- tests/session/test_cdp.py
https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/7453624958/job/20279407730?pr=1673
> test: unflake test

- src/bidiMapper/BidiNoOpParser.ts
- src/bidiMapper/BidiParser.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/network/NetworkRequest.ts
- src/bidiTab/BidiParser.ts
- src/protocol-parser/generated/webdriver-bidi.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/ErrorResponse.spec.ts
- src/protocol/ErrorResponse.ts
- src/protocol/generated/webdriver-bidi.ts
* Add cookies types from BiDi spec.
* Fix build.
* Add work around for https://github.com/google/cddlconv/issues/19.
> build(spec): add Cookies types

- src/bidiServer/MapperCdpConnection.ts
Add log listeners before the Mapper is launched, so that do not skip any message. This relates only to NodeJS runner.
> feat: provide logs before Mapper is launched via NodeJS runner

- src/bidiServer/WebSocketServer.ts
- src/bidiServer/index.ts
Comments on places where changes were made.
> refactor: create an instance

- src/bidiMapper/domains/network/NetworkStorage.spec.ts
- src/bidiMapper/domains/network/NetworkStorage.ts
In BiDi nothing is preventing you from setting X amount of interception with same logic, you should get unique handle each time, so if one unsubscribes the reset continue blocking the request.
> refactor: types + logic fix

- .github/workflows/puppeteer.yml
This will run the Puppeteer tests if the label is present on each push as well. not only label event
> ci: fix Puppeteer label

- .github/workflows/puppeteer.yml
This will make all test pass rather than some failing due to wrong set-up.
> ci: fix runner to match Puppeteer one

- package-lock.json
- package.json
\+ regenerated the lock file to avoid vulnerable packages.
> build: bump browsers package

- tests/browsing_context/test_create.py
Deflake e2e test `test_browsingContext_create_withUserGesture_eventsEmitted`
> test: fix flaky e2e test

- package-lock.json
- package.json
- rollup.config.mjs
Context https://bugs.chromium.org/p/chromedriver/issues/detail?id=4729
> build: output third party notices

- tests/permissions/test_set_permission.py
Raised in https://github.com/GoogleChromeLabs/chromium-bidi/pull/1805
> test: apply comments to set_permission

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
> chore: order for reload

- src/bidiMapper/domains/context/BrowsingContextProcessor.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/create/invalid.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/create/user_context.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/create/invalid.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/create/user_context.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/create/invalid.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/create/user_context.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/create/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/create/user_context.py.ini
Closes https://github.com/GoogleChromeLabs/chromium-bidi/issues/1849
> test: fix user context tests

- README.md
- tools/bidi-server.mjs
- tools/run-e2e.mjs
Adds the ability to filter by folder, test file or test name.
> test: add test filter to e2e

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/context/BrowsingContextStorage.ts
- src/bidiMapper/domains/network/NetworkProcessor.ts
- src/bidiMapper/domains/script/ScriptProcessor.ts
- src/bidiTab/BidiParser.ts
- src/protocol-parser/protocol-parser.ts
This is only verification no update to the logic after.
> chore: verify browsing context

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/domains/storage/StorageProcessor.ts
- tests/storage/test_delete_cookies.py
Implement `storage.deleteCookies`.
WPT tests are on their way in https://github.com/GoogleChromeLabs/chromium-bidi/pull/1914
> feat: implement `storage.deleteCookies`

- tools/wpt-report-builder/builder.mjs
- tools/wpt-report-builder/formatter.mjs
Get commit hash either from GitHub env variable or from CLI
> ci: in wpt html report provide a link to the commit

- src/bidiServer/SimpleTransport.ts
- src/bidiTab/mapperTabPage.ts
- src/utils/UrlPattern.ts
- tools/run-e2e.mjs
Caught when trying to run ESM test.
> chore: misc fixes

- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/remove_intercept/remove_intercept.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/remove_intercept/remove_intercept.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/remove_intercept/remove_intercept.py.ini
Test is falky will investigate.
> chore: disable flaky WPT test

- tests/script/test_evaluate.py
We wait for each command to evaluate instead of just waiting for the promise to ensure scripts are evaluated in order (previously this may have not been the case due to how workers work)
Fixed: https://github.com/GoogleChromeLabs/chromium-bidi/issues/1830
> test: ensure execution of sequence of commands

- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/remove_intercept/remove_intercept.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/remove_intercept/remove_intercept.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/remove_intercept/remove_intercept.py.ini
Marks as flaky. I look at the code its related to us not handling inflight request correctly. That's a known issue that we consider a edge case and low priority at this time.
> chore: mark WPT test as flaky

- tools/wpt-report-builder/formatter.mjs
Also made it a little bit more pretty.
> docs: add expand button

- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/set_viewport/device_pixel_ratio.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/wheel.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/wheel.py.ini
- wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/set_viewport/device_pixel_ratio.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/wheel.py.ini
Try to unskip some test if flaky I will mark them as such.
> chore: unskip WPT tests

- tests/browser/test_close.py
- tests/browsing_context/test_reload.py
Failing run: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/8174594366?pr=1957
> test: skip flaky e2e tests

- tests/session/test_protocol_basics.py
Try to reproduce https://github.com/GoogleChromeLabs/chromium-bidi/issues/1870
> test: unknown command

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- src/protocol-parser/generated/webdriver-bidi.ts
- src/protocol/generated/webdriver-bidi.ts
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/locate_nodes/ownership.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/locate_nodes/sandbox.py.ini
* Remove `ownership` and `sandbox` params.
* Bump WPT
> chore: update `browsingContext.locateNodes`

- src/bidiMapper/domains/network/NetworkProcessor.ts
- src/bidiMapper/domains/network/NetworkUtils.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/add_intercept/url_patterns.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/add_intercept/url_patterns.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/add_intercept/url_patterns.py.ini
The only test left is `https://{wpt_host}/??-https://{wpt_host}/?` but did not find a elegant solution for it yet.
> fix: the pattern matching logic

- src/bidiMapper/domains/network/NetworkProcessor.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/add_intercept/url_patterns.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/add_intercept/url_patterns.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/add_intercept/url_patterns.py.ini
This should have been included in the other PR.
> chore: forgotten change

- src/bidiMapper/domains/network/NetworkRequest.ts
Should mitigate #1975. Will need to investigate a repo and add unit testing before closing.
> fix: don't throw unhandled errors

- tools/wpt-report-builder/formatter.mjs
> docs: fix long name issues

- .eslintrc.js
- tools/wpt-report-builder/builder.mjs
- tools/wpt-report-builder/formatter.mjs
- tools/wpt-report-builder/template.html
> chore: add chrome version to website

- tools/wpt-report-builder/builder.mjs
- tools/wpt-report-builder/formatter.mjs
- tools/wpt-report-builder/template.html
> chore: add wpt hash to runner

- src/bidiMapper/domains/context/BrowsingContextImpl.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/locate_nodes/serialization_options.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/locate_nodes/serialization_options.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/locate_nodes/serialization_options.py.ini
Some WPT tests are still failing due to https://github.com/web-platform-tests/wpt/pull/45247
> feat: support `maxDepth` and `serializationOptions` in `browsingContext.locateNodes`

- src/bidiMapper/domains/network/NetworkRequest.ts
- src/bidiMapper/domains/network/NetworkStorage.spec.ts
> fix: emit `network.beforeRequestSent` event for data urls

- src/bidiMapper/domains/network/NetworkProcessor.ts
- src/bidiMapper/domains/network/NetworkRequest.ts
> feat: support body in `network.continueRequest`

- src/bidiMapper/domains/network/NetworkRequest.ts
- src/bidiMapper/domains/network/NetworkStorage.spec.ts
> fix: don't block data url events when interception is enabled

- src/bidiMapper/modules/cdp/CdpTarget.ts
- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- src/bidiMapper/modules/network/NetworkProcessor.ts
- src/bidiMapper/modules/network/NetworkStorage.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/add_intercept/contexts.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/add_intercept/contexts.py.ini
> fix(network): support Interception for OOPIF

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/set_viewport/viewport.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/set_viewport/viewport.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/set_viewport/viewport.py.ini
> fix: sending undefined viewport should keep previously set viewport

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
Save some memory as we don't need the data.
> chore: remove object from deferred

- tools/run-wpt.mjs
Required for easier debugging WPT over chromedriver
> chore: allow to specify chromedriver path

- .github/workflows/update-bidi-types.yml
Sometimes the PR would require manual fixes.
> ci: continue-on-error for types roller

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
Fixes [OOM](https://crbug.com/336718011) from trying to re-build a11y caches.
> performance: turn on a11y caches

- .github/workflows/wpt.yml
We already checked for that the first `if` for the Job.
> ci: remove second check

- .github/workflows/labeler.yml
Don't trigger it on new commits.
> ci: fix labeler again

- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/wheel.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/wheel.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/wheel.py.ini
Issue: https://github.com/GoogleChromeLabs/chromium-bidi/issues/2169
> chore: mark test unstable

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- src/bidiMapper/modules/log/LogManager.ts
- src/bidiMapper/modules/network/NetworkStorage.ts
Only remove types that can be inferred.
> chore: let emitted value be inferred

- .github/workflows/wpt.yml
- tools/run-wpt-all.mjs
- tools/wpt-report-builder/builder.mjs
- tools/wpt-report-builder/formatter.mjs
- tools/wpt-report-builder/template.html
- wpt-metadata/chromedriver/headful/webdriver/tests/interop/frames.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/interop/shared_id_node.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/interop/shared_id_window.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/interop/frames.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/interop/shared_id_node.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/interop/shared_id_window.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/interop/frames.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/interop/shared_id_node.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/interop/shared_id_window.py.ini
This add the changes only to the CI we run on the `main` branch a follow up will add it to `wpt-quick`.
New Website image:
Issue: #2133
> ci: add Interop test to `main` CI

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- src/utils/Deferred.spec.ts
- src/utils/Deferred.ts
Addressing https://github.com/GoogleChromeLabs/chromium-bidi/issues/2275. 
Cannot reproduce in nodejs or chromedriver runners.
> fix: wait for default realm to be created before evaluating script

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- src/protocol-parser/generated/webdriver-bidi.ts
- src/protocol/generated/webdriver-bidi.ts
- tests/browsing_context/test_close.py
- tests/browsing_context/test_user_prompt.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
> chore: update BiDi types

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- src/protocol-parser/generated/webdriver-bidi.ts
- src/protocol/generated/webdriver-bidi.ts
Base on https://github.com/GoogleChromeLabs/chromium-bidi/pull/2365
> build(spec): update WebDriverBidi types

- src/bidiMapper/modules/network/NetworkRequest.ts
This PR, just moves some methods to getters and consolidates them at the top. 
Also removes some unnecessary `assert`, the required ones are on the correct level now.
> refactor: move methods around

- tools/wpt-report-builder/builder.mjs
- tools/wpt-report-builder/filter-2023.mjs
- tools/wpt-report-builder/formatter.mjs
Addressing failing [wpt detailed](https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/9793601171) CI jobs.
> ci: tolerate missing interop WPT report

- .github/workflows/wpt-quick.yml
- .github/workflows/wpt.yml
- tools/run-wpt.mjs
- tools/wpt-report-builder/builder.mjs
Part of https://github.com/GoogleChromeLabs/chromium-bidi/issues/2240
> chore: update builder to support quick build

- .github/workflows/wpt-quick.yml
- tools/run-wpt.mjs
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigation_failed/navigation_failed.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/integration/cookies_with_network_events.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigation_failed/navigation_failed.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/integration/cookies_with_network_events.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigation_failed/navigation_failed.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/integration/cookies_with_network_events.py.ini
> chore: fix wpt output

- .github/workflows/wpt-quick.yml
- tools/run-wpt.mjs
> ci: fix log overwriting

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/modules/script/ScriptProcessor.ts
Closes https://github.com/GoogleChromeLabs/chromium-bidi/issues/1078
> fix: emit realm events when subscribing

- tools/bidi-server.mjs
- tools/run-bidi-server.mjs
- tools/run-e2e.mjs
> build: fix dangling process

- src/bidiServer/WebSocketServer.ts
Do not crash node JS server on an invalid request.
Even though the NodeJS runner is used only for debugging purposes and as e2e runner, this issue causes some confusion.
> chore: don't crash nodejs server on invalid request

- .github/dependabot.yml
Add some specific times to send PRs.
> chore: update time for dependabot

- src/bidiMapper/modules/input/ActionDispatcher.ts
Align with WPT: https://github.com/web-platform-tests/wpt/pull/47790
+ update default `altitudeAngle`
> fix: do not emit pen events if it is not detected by digitizer.

- tools/update_chrome_revision.mjs
> chore: log Chrome version in `update_chrome_revision.mjs`

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- tests/browsing_context/test_navigate.py
Rely on `Page.frameRequestedNavigation` and `Page.frameScheduledNavigation`.
> fix: always provide url in `browsingContext.navigationStarted`

- tools/bidi-server.mjs
- tools/run-e2e.mjs
- tools/run-wpt.mjs
> test: provide the location of the logs in case of failure

- tests/conftest.py
- tests/test_helpers.py
Required to provide custom Chrome CLI flags via test fixtures.
> test: merge capabilities recursively

- .gitignore
- .mocharc.cjs
- .mocharc.json
- .vscode/launch.template.json
- package-lock.json
- package.json
- rollup.config.mjs
- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- src/bidiMapper/modules/input/ActionDispatcher.ts
- src/bidiMapper/tsconfig.cjs.json
- src/bidiMapper/tsconfig.json
- src/bidiServer/tsconfig.json
- src/bidiTab/tsconfig.cjs.json
- src/bidiTab/tsconfig.json
- src/cdp/tsconfig.cjs.json
- src/cdp/tsconfig.json
- src/protocol-parser/tsconfig.cjs.json
- src/protocol-parser/tsconfig.json
- src/protocol/tsconfig.cjs.json
- src/protocol/tsconfig.json
- src/tsconfig.cjs.json
- src/tsconfig.json
- src/utils/GraphemeTools.spec.ts
- src/utils/tsconfig.cjs.json
- src/utils/tsconfig.json
- tools/bidi-server.mjs
- tools/generate-module-package-json.mjs
- tsconfig.base.json
- tsconfig.cjs.json
Also makes the MapperTab use ESM rather then CommonJS which is smaller.
> feat: support ESM module

- tests/script/test_serialization.py
Assert the iframe is serialized properly.
> test: iframe serialization

- .github/workflows/update-browser-version.yml
Fix access to the script output message to be used in the commit.
> ci: fix `update-browser-version.yml`

- src/bidiMapper/modules/context/BrowsingContextProcessor.ts
- tests/browsing_context/test_traverse_history.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/traverse_history/context.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/traverse_history/context.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/traverse_history/context.py.ini
Align with the spec https://github.com/w3c/webdriver-bidi/pull/770 and WPT https://github.com/web-platform-tests/wpt/pull/48260
> feat: `browsingContext.traverseHistory` only for top-level navigables

- .github/dependabot.yml
Try to fix dependabot be touching it
> ci: touch dependabot

- src/bidiMapper/modules/log/LogManager.ts
There are other APIs that are reported differently on CDP level.
> fix: show correct log method

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/modules/cdp/CdpTarget.ts
- src/bidiMapper/modules/cdp/CdpTargetManager.ts
- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- src/bidiMapper/modules/context/BrowsingContextProcessor.ts
- src/bidiMapper/modules/context/BrowsingContextStorage.ts
- src/protocol/generated/webdriver-bidi.ts
- tests/browsing_context/test_create.py
- tests/browsing_context/test_navigate.py
- tests/script/test_add_preload_script.py
Support for [MPArch](https://docs.google.com/document/d/1NginQ8k0w3znuwTiJ5qjYmBKgZDekvEPC22q0I4swxQ/edit?tab=t.0#heading=h.w1qo2n6sr8wn) sessions.
* This enables prerendering. 
* Some workarounds for [pause page creation with MPArch tab session \[372842894\]](https://crbug.com/372842894) were introduced.
> feat: support MPArch sessions

- src/bidiMapper/modules/input/ActionDispatcher.ts
- tests/conftest.py
- tests/input/test_input.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py.ini
Respect frame offset relative to the target.
> chore: respect iframe offset in input events

- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigate/error.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigate/error.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigate/error.py.ini
* https://github.com/GoogleChromeLabs/chromium-bidi/issues/2743
* https://github.com/GoogleChromeLabs/chromium-bidi/issues/2724
> chore: mark WPT tests as flaky

- .github/workflows/e2e.yml
- .github/workflows/selenium.yml
- .github/workflows/webdriverio.yml
- .github/workflows/wpt.yml
- tools/install-browser.mjs
Required for https://github.com/GoogleChromeLabs/chromium-bidi/pull/2719
> ci: install headless shell when required

- src/bidiMapper/BidiNoOpParser.ts
- src/bidiMapper/BidiParser.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiTab/BidiParser.ts
- src/protocol-parser/protocol-parser.ts
> chore: parse bluetooth commands

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/modules/browser/BrowserProcessor.ts
- tests/browser/test_get_client_windows.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browser/get_client_windows/get_client_windows.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browser/get_client_windows/get_client_windows.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browser/get_client_windows/get_client_windows.py.ini
Addressing https://github.com/GoogleChromeLabs/chromium-bidi/issues/2777
> feat: implement `browser.getClientWindows`

- tests/browsing_context/test_create.py
Repro for https://github.com/GoogleChromeLabs/chromium-bidi/issues/2793
> test: test no events for initial navigation

- src/bidiMapper/CommandProcessor.ts
- src/protocol-parser/generated/webdriver-bidi.ts
- src/protocol/generated/webdriver-bidi.ts
Note (to self) to build the CDDL you need to build the HTML first...
In BiDi there are no domains, they are called modules reflect that in the comment.
The `session.end` is not an Unknown command its not implemented make the difference.
> chore: fix types again

- tests/browsing_context/test_create.py
- tests/browsing_context/test_dom_content_loaded.py
- tests/browsing_context/test_load.py
- tests/browsing_context/test_navigate.py
- tests/conftest.py
- tests/test_helpers.py
Checking values across all the keys is required uniqueness checks.
Unblocks using snapshot assertions in e2e
> test: make stable value unique across different keys

- README.md
- tests/browsing_context/__snapshots__/test_navigate_events.ambr
- tests/browsing_context/test_navigate_events.py
- tools/run-e2e.mjs
Some of the tests are flaky due to racy implementation. The behavior is not guaranteed to be correct, but required for consistency check.
> test: snapshot test navigation

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/locate_nodes/locator.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/locate_nodes/locator.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/locate_nodes/locator.py.ini
Spec https://w3c.github.io/webdriver-bidi/#locate-the-container-element
> feat: implement context locator

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/OutgoingMessage.ts
- src/bidiMapper/modules/network/NetworkStorage.spec.ts
- src/bidiMapper/modules/session/EventManager.ts
- src/bidiMapper/modules/session/SessionProcessor.ts
- src/bidiMapper/modules/session/SubscriptionManager.spec.ts
- src/bidiMapper/modules/session/SubscriptionManager.ts
- src/bidiTab/Transport.ts
- src/protocol/chromium-bidi.ts
- tests/session/test_subscription.py
- tests/test_helpers.py
Step towards addressing https://github.com/GoogleChromeLabs/chromium-bidi/issues/2840
> feat: support `goog:channel` along with `channel`

- .github/dependabot.yml
It seems to have deactivated on its own.
> chore: touch dependabot.yml

- .github/workflows/e2e.yml
- .github/workflows/puppeteer.yml
- .github/workflows/wpt.yml
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#always
> ci: don't use always()

- tests/network/test_provide_response.py
> test: fix flake

- tools/run-wpt-all.mjs
- tools/run-wpt.mjs
This script didn't run pure mapper at all.
> chore: fix run all

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- src/bidiMapper/modules/context/NavigationTracker.ts
- tests/browsing_context/__snapshots__/test_navigate_events.ambr
- tests/browsing_context/test_navigate.py
- tests/browsing_context/test_navigate_events.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigate/navigate.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/reload/wait.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/fetch_error/fetch_error.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigate/navigate.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/reload/wait.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/fetch_error/fetch_error.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigate/navigate.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/reload/wait.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/fetch_error/fetch_error.py.ini
Refactor NavigationTracker will be in a follow-up. 
Tested with https://github.com/web-platform-tests/wpt/pull/50527.
> feat: wait `none` waits for navigation to be committed

- src/bidiMapper/modules/network/NetworkProcessor.ts
- tests/network/test_continue_request.py
Will also be better if https://chromium-review.googlesource.com/c/chromium/src/+/6244143 lands
> fix(network): propagate unsafe header error as invalid 

- src/bidiMapper/modules/cdp/CdpTarget.ts
- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- src/bidiMapper/modules/session/SubscriptionManager.ts
- src/protocol-parser/generated/webdriver-bidi.ts
- src/protocol/chromium-bidi.ts
- src/protocol/generated/webdriver-bidi.ts
- tests/input/file_dialog/__snapshots__/test_file_dialog_opened.ambr
- tests/input/file_dialog/test_file_dialog_opened.py
Implementation of https://github.com/w3c/webdriver-bidi/pull/883
> feat: `input.fileDialogOpened` + `unhandledPromptBehavior.file`

- src/bidiMapper/CommandProcessor.ts
- src/protocol-parser/generated/webdriver-bidi.ts
- src/protocol/generated/webdriver-bidi.ts
Manual roll with https://github.com/w3c/webdriver-bidi/pull/892
> build: update types

- src/bidiMapper/BidiServer.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/modules/browser/UserContextConfig.ts
- src/bidiMapper/modules/browser/UserContextStorage.ts
- src/bidiMapper/modules/cdp/CdpTarget.ts
- src/bidiMapper/modules/cdp/CdpTargetManager.ts
- src/bidiMapper/modules/context/BrowsingContextImpl.ts
- src/bidiMapper/modules/context/BrowsingContextProcessor.ts
- tests/browsing_context/test_set_viewport.py
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/set_viewport/invalid.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/set_viewport/user_contexts.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/set_viewport/invalid.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/set_viewport/user_contexts.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/set_viewport/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/set_viewport/user_contexts.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/integration/set_viewport_with_preload_script.py.ini
* Introduce `UserContextConfig`
* Move `setViewport` to `CdpTarget`.
> feat: support UserContext in setViewport

- tests/network/test_network.py
Failure: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/14375034202/job/40305339042?pr=3298
> test: deflake test_network_global_subscription_enabled_in_new_context

- Pipfile
- Pipfile.lock
- tests/network/test_network.py
- tools/bidi-server.mjs
- tools/run-e2e.mjs
https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/14382330213/job/40329009483?pr=3303
+ add `--repeat-times=X` argument to e2e script.
> test: deflake test_network_should_not_block_queue_shared_workers_with_data_url

- src/bidiMapper/modules/browser/UserContextConfig.ts
- src/bidiMapper/modules/cdp/CdpTarget.ts
- src/bidiMapper/modules/emulation/EmulationProcessor.ts
- src/protocol-parser/generated/webdriver-bidi.ts
- src/protocol-parser/protocol-parser.ts
- src/protocol/generated/webdriver-bidi.ts
- tests/emulation/__snapshots__/test_geolocation.ambr
- tests/emulation/test_geolocation.py
Spec is landed in https://github.com/w3c/webdriver-bidi/pull/911
> feat: emulate geolocation positionUnavailable

- src/bidiMapper/BidiNoOpParser.ts
- src/bidiMapper/BidiParser.ts
- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/modules/bluetooth/BluetoothProcessor.ts
- src/bidiTab/BidiParser.ts
- src/protocol-parser/protocol-parser.ts
- tests/bluetooth/__init__.py
- tests/bluetooth/test_emulation.py
- tests/bluetooth/test_gatt_connection.py
- tests/bluetooth/test_service_emulation.py
Support bluetooth.simulateGattDisconnection and bluetooth.simulateService commands
> feat: support GATT disconnection and service simulation

- Pipfile
- tests/conftest.py
- tests/network/test_network.py
- tests/tools/local_http_server.py
- tests/tools/test_local_http_server.py
Attempt to address e2e issues with `pytest_httpserver` and replace it with flask.
> test: flask e2e local http server

- .github/workflows/e2e.yml
- tools/bidi-server.mjs
- tools/run-e2e.mjs
Temporary solution for https://github.com/GoogleChromeLabs/chromium-bidi/issues/3412
> test: rerun node e2e tests

- tests/input/file_dialog/__snapshots__/test_file_dialog_opened.ambr
- tests/input/file_dialog/test_file_dialog_opened.py
- tests/permissions/test_set_permission.py
- tests/script/__snapshots__/test_serialization.ambr
- tests/script/test_serialization.py
- tests/test_helpers.py
`stabilize_key_values` now sorts keys before stabilization.
> test: re-enable the rest of the e2e in cd

- tests/browsing_context/test_fragment_navigated.py
Verify https://github.com/GoogleChromeLabs/chromium-bidi/issues/2425 is addressed.
> test: no `browsingContext.fragmentNavigated` on `history.pushState`

- tests/browser/test_create_user_context.py
- tests/tools/http_proxy_server.py
- tools/http-proxy.mjs
The test is flaky due to proxy not responding.
> test: wait for proxy to start + use `http://httpbin.org/get`

- src/bidiMapper/modules/context/BrowsingContextImpl.ts
WPT: https://github.com/web-platform-tests/wpt/pull/54054
Closes https://github.com/GoogleChromeLabs/chromium-bidi/issues/3603
> fix: allow svg element as a start node

- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/locate_nodes/start_nodes.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/emulation/set_locale_override/contexts.py.ini
- wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/add_data_collector/invalid.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/locate_nodes/start_nodes.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/emulation/set_locale_override/contexts.py.ini
- wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/add_data_collector/invalid.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/locate_nodes/start_nodes.py.ini
- wpt-metadata/mapper/headless/webdriver/tests/bidi/network/add_data_collector/invalid.py.ini
Closes https://github.com/GoogleChromeLabs/chromium-bidi/pull/3615
> chore(deps): Bump wpt from `bd85360` to `e0329ea`

- GEMINI.md
- src/bidiMapper/modules/browser/BrowserProcessor.ts
- src/bidiMapper/modules/browser/ContextConfig.ts
- src/bidiMapper/modules/browser/ContextConfigStorage.spec.ts
- src/bidiMapper/modules/browser/ContextConfigStorage.ts
Addressing Puppeteer failures: https://github.com/puppeteer/puppeteer/actions/runs/16803966784/job/47591715262.
> fix: do not override context config with undefined

- src/bidiMapper/CommandProcessor.ts
- src/bidiMapper/modules/browser/BrowserProcessor.ts
- src/bidiMapper/modules/browser/ContextConfig.ts
- src/bidiMapper/modules/browser/ContextConfigStorage.ts
- tests/browsing_context/test_download.py
- tests/conftest.py
Spec: https://github.com/w3c/webdriver-bidi/pull/970
> feat: implement `browser.setDownloadBehavior`

- src/bidiMapper/modules/network/NetworkRequest.ts
Closes: https://github.com/GoogleChromeLabs/chromium-bidi/issues/3762
> fix: don't report interception for DataUrl and servedFromCache
